import {fixedResultLabel} from '../fixedResultRead';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useClimateWorkspace} from '../useClimateWorkspace';
import {defaultClimateQuery,normalizeClimateQuery,queryIssue,queryKey,climateHours,climateHoursLabel,climateYearsLabel,climateSourceLabel,climateHourSupport,selectedClimateHours,hourLevelIds,type ClimateBounds} from '../climateDomain';
import {climateViewModel,climateGrains,annualQuarterViewModel} from './weather/sources/climateSummary';
import {checkedRose} from './weather/climateDistributions';
import {mountWeather} from './weather/runtime';
import {ClimateFlightHandoff} from '../ClimateFlightHandoff';
function FixtureWeatherScreen({saved,onView,handoff,background}:{saved:any;onView:(v:any)=>void;handoff:(v:any)=>void;background:boolean}){
 const host=useRef<HTMLDivElement>(null),current=useRef({onView,handoff});current.current={onView,handoff};
 useEffect(()=>{const locationState=saved?'?restore='+encodeURIComponent(JSON.stringify({kind:'synthetic-climate-proposal',returnState:saved})):'';const runtime=mountWeather(host.current!,{location:{search:locationState,origin:location.origin},background,handoff:(p:any)=>current.current.handoff(p)});let alive=true;const element=host.current!;const capture=()=>queueMicrotask(()=>{if(alive)current.current.onView(runtime.snapshot());});element.addEventListener('click',capture);element.addEventListener('change',capture);element.addEventListener('input',capture);return()=>{alive=false;element.removeEventListener('click',capture);element.removeEventListener('change',capture);element.removeEventListener('input',capture);runtime.dispose();};},[background]);
 return <div ref={host} className="weather-screen"/>;
}

export function WeatherScreen(props:{saved:any;onView:(v:any)=>void;handoff:(v:any)=>void;background:boolean;mode?:'fixture'|'climate'}){return props.mode==='climate'?<ClimateWeatherScreen {...props}/>:<FixtureWeatherScreen {...props}/>;}
function ClimateWeatherScreen({saved,onView,background,handoff}:{saved:any;onView:(v:any)=>void;background:boolean;handoff:(v:any)=>void}){
 const ws=useClimateWorkspace(saved,onView),host=useRef<HTMLDivElement>(null),runtime=useRef<any>(null),[portal,setPortal]=useState<HTMLElement|null>(null),current=useRef(ws);current.current=ws;
 const [flightPortal,setFlightPortal]=useState<HTMLElement|null>(null);
 const projection=useMemo(()=>{if(!ws.artifact)return {vm:null,error:''};try{const models=Object.fromEntries(climateGrains(ws.artifact).map(g=>{const vm=climateViewModel(ws.artifact!,g);checkedRose(vm);return [g,vm];}));if(ws.artifact.summary.annual_quarters)models.quarter=annualQuarterViewModel(models.half,ws.artifact);return {vm:models,error:''};}catch(e){return {vm:null,error:e instanceof Error?e.message:String(e)};}},[ws.artifact]);
 useEffect(()=>{const r=mountWeather(host.current!,{mode:'climate',background,saved:ws.view,onView:(v:any)=>current.current.show(v),allHours:()=>{const q=current.current.view.draft_query;if(q)current.current.editQuery({...q,hours_utc:undefined});},apply:()=>current.current.retryPressure(),level:(id:number)=>current.current.selectPressure(id),point:(id:number)=>current.current.selectPoint(id),retryPoint:()=>current.current.retryPoint()});runtime.current=r;setPortal(r.preparationElement);setFlightPortal(r.flightElement);return()=>{runtime.current=null;r.dispose();};},[background]);
 const q=ws.view.draft_query,d=ws.sources.find(s=>s.source_id===q?.source_id),bounds=q?.bounds??d?.bounds,issue=q&&d?queryIssue(q,d):'利用可能な資料を選択してください。',draftDiff=!!ws.artifact&&queryKey(q)!==queryKey(ws.artifact.query),[localBounds,setLocalBounds]=useState<Record<string,string>|null>(null),[localError,setLocalError]=useState('');
 useEffect(()=>{setLocalBounds(null);setLocalError('');},[q?.source_id]);
 const editBounds=(key:keyof ClimateBounds,value:string)=>{if(!q||!bounds)return;const fields={...Object.fromEntries(Object.entries(bounds).map(([k,v])=>[k,String(v)])),...localBounds,[key]:value};setLocalBounds(fields);if(Object.values(fields).some(v=>v.trim()===''||!Number.isFinite(Number(v)))){setLocalError('範囲を数値で入力してください。途中の空欄は集計・保存へ適用していません。');return;}setLocalError('');ws.editQuery({...q,bounds:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,Number(v)])) as ClimateBounds});};
 const selectedCount=d&&bounds?d.native_grid.filter(c=>c.lon>=bounds.west&&c.lon<=bounds.east&&c.lat>=bounds.south&&c.lat<=bounds.north).length:0;
 const canApply=(!ws.busy||!!ws.pressure)&&!issue&&!localError&&draftDiff;
 const otherDraftChanged=!!ws.artifact&&!!q&&queryKey(normalizeClimateQuery({...q,level_id:ws.artifact.query.level_id,rose_cell_id:ws.artifact.query.rose_cell_id}))!==queryKey(ws.artifact.query);
 const pendingLabel=q?`${climateHoursLabel(q)}${bounds?` / ${bounds.south}–${bounds.north}°N・${bounds.west}–${bounds.east}°E`:''}`:'';
 useEffect(()=>{runtime.current?.sync(projection.vm,ws.view,{status:projection.error||ws.status,restoreLabel:ws.view.applied&&!ws.artifact?fixedResultLabel(ws.restoreRead):null,levelId:ws.view.draft_query?.level_id,sourceId:ws.view.draft_query?.source_id,canApply,otherDraftChanged,pendingLabel,busy:ws.busy,pressure:ws.pressure,point:ws.point,pointAvailable:ws.sources.some(s=>s.source_id===ws.artifact?.query.source_id&&s.capabilities.wind_rose_point_select===true)});},[projection,ws.view,ws.status,ws.restoreRead,canApply,otherDraftChanged,pendingLabel,ws.busy,ws.pressure,ws.point,ws.sources]);
 return <><div ref={host} className="weather-screen climate-screen"/>{portal&&createPortal(<>
 <fieldset><legend>集計する資料</legend><label>保存資料 <select value={q?.source_id??''} onChange={e=>{const source=ws.sources.find(s=>s.source_id===e.target.value);if(source)ws.editQuery(defaultClimateQuery(source));}}><option value="" disabled>資料を選択</option>{q&&!d&&<option value={q.source_id} disabled>保存時の資料・集計方式（現在の一覧にありません）— 現在の資料を選択</option>}{ws.sources.map(s=><option key={s.source_id} value={s.source_id}>{climateSourceLabel(s)} · {climateYearsLabel(s.capabilities.years_fixed)} · {s.dataset_sha256.slice(0,8)}</option>)}</select></label><button onClick={()=>void ws.refreshSources()}>資料の状態を再確認</button><p>{d?climateYearsLabel(d.capabilities.years_fixed):'対象年を確認中'}（この資料では年の部分選択はできません）。</p><fieldset className="climate-hours"><legend>気象場の有効時刻</legend><div className="climate-hour-options">{climateHours.map(h=><label key={h}><input type="checkbox" disabled={!q||!d?.capabilities.hour_filter} checked={!!q&&selectedClimateHours(q).includes(h)} onChange={e=>{if(q){const old=selectedClimateHours(q);ws.editQuery({...q,hours_utc:e.target.checked?[...old,h]:old.filter(x=>x!==h)});}}}/>UTC {String(h).padStart(2,'0')}時 <small>（JST {h===18?'翌03':String((h+9)%24).padStart(2,'0')}時）</small></label>)}</div><button disabled={!q} onClick={()=>q&&ws.editQuery({...q,hours_utc:undefined})}>全4時刻に戻す</button><p>{d?climateHourSupport(d):'資料の時間帯別支持を確認中です。'}</p><small>気象場が表す時刻です。放球時刻ではありません。半月はUTC 1–15日 / 16–月末。JST翌03時も元のUTC期間に含みます。</small></fieldset>{ws.sourceErrors.map((e,i)=><p key={i} role="status">{e}</p>)}{!ws.sources.length&&!ws.sourceErrors.length&&<p>利用できる実資料がないか、資料一覧を確認中です。人工データへは自動で切り替えません。</p>}</fieldset>
 <fieldset><legend>対象の元格子と表示面</legend><p>範囲内に中心がある格子を集計します。選択予定 {selectedCount} / {d?.native_grid_count??'—'}格子。</p><div className="climate-bounds">{(['west','east','south','north'] as const).map((key,i)=><label key={key}>{['西経度','東経度','南緯度','北緯度'][i]}<input type="number" step="any" value={localBounds?.[key]??bounds?.[key]??''} onChange={e=>editBounds(key,e.target.value)}/></label>)}</div><button disabled={!q} onClick={()=>{if(q){setLocalBounds(null);setLocalError('');ws.editQuery({...q,bounds:null});}}}>全元格子へ戻す</button><label>地域図・風配の気圧面 <select value={q?.level_id??''} disabled={!d} onChange={e=>q&&ws.editQuery({...q,level_id:Number(e.target.value)})}>{d&&[...d.levels].sort((a,b)=>b.level_hpa-a.level_hpa).map(l=><option key={l.level_id} value={l.level_id}>{l.level_hpa} hPa · ISA {(l.isa_alt_m/1000).toFixed(2)} km</option>)}</select></label></fieldset>
 <div className="climate-actions">{q?.hours_utc&&d&&!hourLevelIds(d).includes(q.level_id)&&<p className="climate-stale">選択した気圧面は時間帯別の支持外です。{d.levels.some(l=>l.level_hpa===300&&hourLevelIds(d).includes(l.level_id))&&<button onClick={()=>ws.editQuery({...q,level_id:d.levels.find(l=>l.level_hpa===300)!.level_id})}>300 hPaへ切り替える（未適用）</button>}</p>}<button className="primary" disabled={(ws.busy&&!ws.pressure)||!!issue||!!localError} onClick={()=>void ws.calculate()}>{ws.busy&&!ws.pressure?'集計を確認中…':ws.busy?'この対象で再集計（気圧面探索を置換）':'この対象で再集計'}</button><p role="status">{ws.status}</p>{ws.view.applied&&!ws.artifact&&<p role="status">{fixedResultLabel(ws.restoreRead)}。保存した図の識別と草案条件を保持しています。{ws.restoreRead?.state!=='loading'&&<button onClick={()=>void ws.restoreSaved()}>保存した図を再読込（再集計なし）</button>}</p>}{(issue||localError)&&<p>{localError||issue}</p>}{(ws.error||projection.error)&&<p role="alert">{ws.error||projection.error}</p>}{draftDiff&&<p className="climate-stale">入力は未適用です。図と図保存は表示中の固定集計を使います。</p>}{ws.artifact&&<details><summary>表示中の固定集計と出典</summary><p>作成 {ws.artifact.created_at} / {ws.artifact.summary.population.selected_cell_count}元格子 / {climateHoursLabel(ws.artifact.query)} / 期間の細かさは図ごとに選択（年間は原標本で48区分にも対応）</p><p className="climate-identity">analysis {ws.artifact.analysis_id}<br/>query {ws.artifact.query_hash}<br/>result {ws.artifact.result_hash}</p><p>保存した計画の再読は固定結果のGETだけで、DBからの再集計を行いません。</p></details>}</div>
 </>,portal)}{flightPortal&&createPortal(<ClimateFlightHandoff artifact={ws.artifact??null} view={ws.view} onView={v=>ws.show(v)} handoff={handoff}/>,flightPortal)}</>;
}
