"use strict";
const D=window.DEMO_DATA,FM=window.FORECAST_MATH;
const fixtures=Object.fromEntries(D.cases.map(c=>[c.id,c]));
const sampleCache=new WeakMap();
const modelLabel={simple:'Tawhiri型・定上昇率',isothermal:'等温・定Cd',season:'凍結気柱・季節試算'};
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const q=(arr,p)=>{if(!arr.length)return null;const a=[...arr].sort((a,b)=>a-b),i=(a.length-1)*p,j=Math.floor(i);return a[j]+(a[Math.min(j+1,a.length-1)]-a[j])*(i-j);};
const minutes=v=>{const m=/^(\d{2}):(\d{2})$/.exec(v||'');return m&&+m[1]<24&&+m[2]<60?+m[1]*60 + +m[2]:NaN;};
const timeString=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const geo=(e,n,origin)=>[origin[0]+n/111.2,origin[1]+e/(111.2*Math.cos(origin[0]*Math.PI/180))];
const jstStamp=c=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(c?.date||'')||!Number.isFinite(minutes(c?.time)))return NaN;const n=Date.parse(`${c.date}T${c.time}:00+09:00`);return Number.isFinite(n)&&new Date(n+540*60000).toISOString().slice(0,16)===`${c.date}T${c.time}`?n:NaN;};
function shiftLaunch(c,delay){const stamp=jstStamp(c);if(!Number.isFinite(stamp))return{date:c.date,time:c.time};const s=new Date(stamp+(delay+540)*60000).toISOString();return{date:s.slice(0,10),time:s.slice(11,16)};}
function unsupported(c){if(!c||!['simple','isothermal'].includes(c.model)||!Number.isFinite(c.mass)||c.mass<.5||c.mass>2||!Array.isArray(c.origin)||c.origin.length!==2||!c.origin.every(Number.isFinite)||c.origin[0]<42.7||c.origin[0]>43.7||c.origin[1]<140.8||c.origin[1]>142.8||!Number.isFinite(jstStamp(c))||c.forecast!=='人工 R1'||c.burstDiameter!==8)return '有効なJST日時、0.5–2.0 kg、42.7–43.7°N / 140.8–142.8°Eを指定してください。実気象の時刻支持は未接続です。';return '';}
function transformedSamples(result){if(sampleCache.has(result))return sampleCache.get(result);const c=result.conditions,elapsed=(jstStamp(c)-Date.parse('2026-09-24T09:00:00+09:00'))/60000,delay=120*Math.sin(elapsed*Math.PI/1680),dm=c.mass-1;
 const out=fixtures[result.fixture].samples.map((s,i)=>{const z1=(i%12-5.5)/5.5,z2=Math.sin(i*1.7),de=.22*delay+3*dm+2*z1*delay/60,dn=-.10*delay+1.5*dm+z2*delay/60;let distance=0,prev=null;const history=s.history.map(r=>{const f=Math.min(1,r.t/s.duration),e=r.e+f*de,n=r.n+f*dn,step=prev?Math.hypot(e-prev.e,n-prev.n):0;distance+=step;const x={...r,e,n,distance,speed:prev?step*1000/60:0,u:r.u+de/(s.duration*60)*1000,v:r.v+dn/(s.duration*60)*1000};prev=x;return x;});const end=history[s.duration],loc=geo(end.e,end.n,c.origin);return{...s,history,lat:loc[0],lon:loc[1],inputZ1:z1,inputZ2:z2};});sampleCache.set(result,out);return out;}
function parseKML(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('DOCTYPE / ENTITYを含むKMLは受け付けません。');const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.querySelector('parsererror'))throw Error('KMLのXML構文が不正です。');if(xml.getElementsByTagNameNS('*','NetworkLink').length)throw Error('NetworkLinkは未対応です。ローカルPolygonだけを読み込んでください。');if(['Point','LineString','Track','Model','GroundOverlay'].some(n=>xml.getElementsByTagNameNS('*',n).length))throw Error('KMLのPolygon以外の図形は未対応です。');if([...xml.getElementsByTagNameNS('*','altitudeMode')].some(n=>n.textContent.trim()!=='clampToGround'))throw Error('2D着地判定のためclampToGround以外のaltitudeModeは未対応です。');const nodes=[...xml.getElementsByTagNameNS('*','Polygon')];if(!nodes.length)throw Error('KML Polygonがありません。');const features=nodes.map((poly,i)=>{const boundaries=[...poly.children].filter(x=>['outerBoundaryIs','innerBoundaryIs'].includes(x.localName));const outer=boundaries.filter(x=>x.localName==='outerBoundaryIs');if(outer.length!==1)throw Error('各Polygonに外周が一つ必要です。');const ordered=[outer[0],...boundaries.filter(x=>x.localName==='innerBoundaryIs')];const coordinates=ordered.map(b=>{const coords=b.getElementsByTagNameNS('*','coordinates');if(coords.length!==1)throw Error('各環にcoordinatesが一つ必要です。');return coords[0].textContent.trim().split(/\s+/).map(v=>{const parts=v.split(',');if(parts.some(x=>!x.trim()))throw Error('空のKML座標です。');const values=parts.map(Number);if(values.length<2||values.length>3||!values.every(Number.isFinite))throw Error('KML座標が不正です。');if(values.length===3&&values[2]!==0)throw Error('非ゼロ高度のKMLは未対応です。地表の2D領域を指定してください。');return values.slice(0,2);});});const pm=poly.closest('Placemark');return{type:'Feature',properties:{name:pm?.getElementsByTagNameNS('*','name')[0]?.textContent||'KML領域 '+(i+1)},geometry:{type:'Polygon',coordinates}};});return FM.parseGeoJSON({type:'FeatureCollection',features});}
function selfIntersects(p){const orient=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){if(j===i+1||i===0&&j===p.length-1)continue;const a=p[i],b=p[(i+1)%p.length],c=p[j],d=p[(j+1)%p.length];if(orient(a,b,c)*orient(a,b,d)<0&&orient(c,d,a)*orient(c,d,b)<0)return true;}return false;}
function within(point,polygon){const [x,y]=point;let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const[xi,yi]=polygon[i],[xj,yj]=polygon[j],cross=(x-xi)*(yj-yi)-(y-yi)*(xj-xi);if(Math.abs(cross)<1e-10&&x>=Math.min(xi,xj)&&x<=Math.max(xi,xj)&&y>=Math.min(yi,yj)&&y<=Math.max(yi,yj))return true;if((yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)inside=!inside;}return inside;}
const demoZones={type:'FeatureCollection',features:[{type:'Feature',properties:{name:'人工の指定領域（穴あり）'},geometry:{type:'Polygon',coordinates:[[[141.83,43.16],[142.05,43.16],[142.05,43.38],[141.83,43.38],[141.83,43.16]],[[141.88,43.23],[141.93,43.23],[141.93,43.28],[141.88,43.28],[141.88,43.23]]]}},{type:'Feature',properties:{name:'人工の重複領域'},geometry:{type:'MultiPolygon',coordinates:[[[[141.99,43.24],[142.13,43.24],[142.13,43.44],[141.99,43.44],[141.99,43.24]]],[[[141.4,43.4],[141.5,43.4],[141.5,43.5],[141.4,43.5],[141.4,43.4]]]]}}]};
