// Derived from the archived 0.40.1 r2 screen; see frontend/SCREEN_PROVENANCE.md.
export function install(scope) {
const {window,document}=scope;
(function(root){
'use strict';
const EPS=1e-10;
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function onSegment(p,a,b){return Math.abs(cross(a,b,p))<=EPS&&p[0]>=Math.min(a[0],b[0])-EPS&&p[0]<=Math.max(a[0],b[0])+EPS&&p[1]>=Math.min(a[1],b[1])-EPS&&p[1]<=Math.max(a[1],b[1])+EPS;}
function relation(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[j],b=ring[i];if(onSegment(p,a,b))return 0;if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside?1:-1;}
function intersects(a,b,c,d){return onSegment(a,c,d)||onSegment(b,c,d)||onSegment(c,a,b)||onSegment(d,a,b)||(cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0);}
function ringsTouch(a,b){return a.some((p,i)=>b.some((q,j)=>intersects(p,a[(i+1)%a.length],q,b[(j+1)%b.length])));}
function validateRing(raw){if(!Array.isArray(raw)||raw.length<4||raw.length>5000)throw Error('環は閉じた4〜5000点が必要です。');const ring=raw.map(p=>{if(!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite)||Math.abs(p[0])>180||Math.abs(p[1])>85)throw Error('有限の [経度,緯度]（緯度±85°内）を指定してください。');return [...p];});if(ring[0][0]!==ring.at(-1)[0]||ring[0][1]!==ring.at(-1)[1])throw Error('環が閉じていません。');ring.pop();for(let i=0;i<ring.length;i++){const next=ring[(i+1)%ring.length];if(Math.abs(ring[i][0]-next[0])>180)throw Error('日付変更線をまたぐ環は未対応です。');if(ring[i][0]===next[0]&&ring[i][1]===next[1])throw Error('連続する重複点があります。');for(let j=i+1;j<ring.length;j++){if(j===i+1||i===0&&j===ring.length-1)continue;if(intersects(ring[i],next,ring[j],ring[(j+1)%ring.length]))throw Error('自己交差・自己接触する環は未対応です。');}}let area=0;ring.forEach((p,i)=>{const q=ring[(i+1)%ring.length];area+=p[0]*q[1]-p[1]*q[0];});if(Math.abs(area)<EPS)throw Error('面積がゼロの環です。');return ring;}
function validatePolygon(coords){if(!Array.isArray(coords)||!coords.length)throw Error('空のPolygonです。');const rings=coords.map(validateRing);for(let i=1;i<rings.length;i++){if(ringsTouch(rings[0],rings[i])||relation(rings[i][0],rings[0])!==1)throw Error('穴が外周に触れるか、外側にあります。');for(let j=1;j<i;j++)if(ringsTouch(rings[i],rings[j])||relation(rings[i][0],rings[j])!==-1||relation(rings[j][0],rings[i])!==-1)throw Error('穴同士の交差・包含は未対応です。');}return rings;}
function parseGeoJSON(j){if(!j||typeof j!=='object'||j.crs)throw Error('WGS84のGeoJSONだけに対応します（crs指定は未対応）。');const feats=j.type==='FeatureCollection'?j.features:j.type==='Feature'?[j]:[{type:'Feature',geometry:j}];if(!Array.isArray(feats)||!feats.length||feats.length>100)throw Error('1〜100領域に限定しています。');let vertices=0;return feats.map((f,i)=>{const g=f.geometry;if(!g||!['Polygon','MultiPolygon'].includes(g.type))throw Error('Polygon / MultiPolygonだけに対応します。');const polys=(g.type==='Polygon'?[g.coordinates]:g.coordinates).map(validatePolygon);if(!polys.length)throw Error('空のMultiPolygonです。');vertices+=polys.flat(2).length;if(vertices>10000)throw Error('合計10000頂点までです。');return{id:'Z'+(i+1),name:String(f.properties?.name||'領域 '+(i+1)).slice(0,80),polygons:polys};});}
// Outer AND hole boundaries count as hit; hole interiors do not.
function polygonHit(p,rings){const outer=relation(p,rings[0]);if(outer<0)return false;if(outer===0)return true;for(const h of rings.slice(1)){const r=relation(p,h);if(r===0)return true;if(r===1)return false;}return true;}
const regionHit=(p,region)=>region.polygons.some(poly=>polygonHit(p,poly));
function classify(samples,regions){const hits=[],outside=[],stopped=[],unknown=[],perRegion=regions.map(r=>({id:r.id,name:r.name,ids:[]}));for(const s of samples){if(s.status!=='landed'){(s.status==='horizontal_boundary'||s.status==='boundary'||String(s.status).includes('stop')?stopped:unknown).push(s.id);continue;}if(!Number.isFinite(s.lat)||!Number.isFinite(s.lon)){unknown.push(s.id);continue;}let hit=false;regions.forEach((r,i)=>{if(regionHit([s.lon,s.lat],r)){hit=true;perRegion[i].ids.push(s.id);}});(hit?hits:outside).push(s.id);}return{hits,outside,stopped,unknown,perRegion,total:samples.length,landed:hits.length+outside.length};}
function ellipse(samples,p){if(samples.length<3)return null;const lat=samples.reduce((a,s)=>a+s.lat,0)/samples.length,lon=samples.reduce((a,s)=>a+s.lon,0)/samples.length,kx=111.2*Math.cos(lat*Math.PI/180),ky=111.2,xy=samples.map(s=>[(s.lon-lon)*kx,(s.lat-lat)*ky]);let a=0,b=0,c=0;for(const [x,y]of xy){a+=x*x;b+=x*y;c+=y*y;}a/=xy.length-1;b/=xy.length-1;c/=xy.length-1;const det=a*c-b*b;if(det<=1e-10)return null;const scores=xy.map(([x,y],i)=>({id:samples[i].id,d:(c*x*x-2*b*x*y+a*y*y)/det})).sort((x,y)=>x.d-y.d),rank=Math.max(1,Math.ceil(p*samples.length)),threshold=scores[rank-1].d,l11=Math.sqrt(a),l21=b/l11,l22=Math.sqrt(c-l21*l21),radius=Math.sqrt(threshold),points=[];for(let i=0;i<=128;i++){const angle=2*Math.PI*i/128,x=radius*l11*Math.cos(angle),y=radius*(l21*Math.cos(angle)+l22*Math.sin(angle));points.push([lat+y/ky,lon+x/kx]);}return{p,rank,count:scores.filter(x=>x.d<=threshold+1e-9).length,ids:scores.filter(x=>x.d<=threshold+1e-9).map(x=>x.id),threshold,points};}
root.FORECAST_MATH={relation,intersects,validatePolygon,parseGeoJSON,polygonHit,regionHit,classify,ellipse};
})(typeof window==='undefined'?globalThis:window);

}
