import {climateGrainLabel,climatePeriodLabel,climateHoursLabel,climateYearsLabel,climateWeightLabel,type ClimateArtifact,type ClimateMoment,type ClimateCell,type ClimateGrain,type ClimatePeriod} from '../../../climateDomain';
import type {WindViewModel,DisplayCell,WindValue} from '../viewModel';
import {niceSpeedMax} from '../viewModel';
import {checkedMonthlyProfiles} from '../monthlyProfiles';
/** The 48 raw-day groups belong to the annual chart only. They are not
 * spatial/rose groups or the half-month flight-interest contract. */
export function annualQuarterViewModel(base:WindViewModel,a:ClimateArtifact):WindViewModel {
 const q=a.summary.annual_quarters;
 if(!q||q.schema!=='climate-annual-quarters/1'||q.date_convention!=='UTC'||q.calendar_definition.version!=='utc-half-nested-quarters/1'||q.timebins.length!==48)throw Error('年間48区分の暦・集計がありません。');
 const rows=new Map(q.annual.map(r=>[r.timebin_id+':'+r.level_id,r]));
 if(rows.size!==q.annual.length||rows.size!==48*base.levels.length)throw Error('年間48区分の高度・期間に欠落または重複があります。');
 const periods=q.timebins.map((p,i)=>{
  if(p.timebin_id!==i||p.month!==Math.floor(i/4)+1||!Number.isInteger(p.n_analyses_expected)||p.n_analyses_expected<=0)throw Error('年間48区分の所属または標本数が不正です。');
  return {id:p.timebin_id,month:p.month,label:climatePeriodLabel(p),description:`UTC ${p.start_day}–${p.end_day_min}日${p.end_day_max!==p.end_day_min?`（閏年${p.end_day_max}日まで）`:''} / ${climateYearsLabel(a.summary.population.years_fixed)}`,timeCount:p.n_analyses_expected};
 });
 const annual=periods.map(p=>base.levels.map(l=>{const r=rows.get(p.id+':'+l.id);if(!r||r.time_count!==p.timeCount||r.valid_time_count!==p.timeCount||r.missing_time_count!==0||r.cell_count!==base.cells.length)throw Error('年間48区分の参照・標本数が一致しません。');return value(r,r.pooled_constancy,r.spatial_mean_speed_range);}));
 return {...base,annual,annualPeriods:periods,spatial:[],spatialPeriods:[],windRose:undefined,
  annualSpeedMax:niceSpeedMax(finite(q.display_scales.annual_mean_speed_max)),annualRangeMax:niceSpeedMax(finite(q.display_scales.spatial_mean_speed_range_max)),
  populationLabel:base.populationLabel.replace('半月24区分','月内4区分・年48区分'),
  annualDefinition:`UTC月内4区分：1–7日 / 8–15日 / 16–22日 / 23–月末。原時刻別の風から直接集計し、各半月の内側を2分します。ISO週ではなく、人工例のJST端数配分とも区間が異なります。Rは面積重み付き地域平均U/V/Sから算出します。細分化だけで独立標本が増えるわけではありません。`,
  metadata:{...base.metadata,grain:'quarter',period_membership:q.timebins,calendar_definition:q.calendar_definition,wind_rose:undefined}};
}
function finite(x:unknown){if(typeof x!=='number'||!Number.isFinite(x))throw new Error('保存集計に有限でない値があります。');return x;}
export function nativeDisplayCells(grid:ClimateCell[],bounds:WindViewModel['nativeBounds']):DisplayCell[]{const xs=[...new Set(grid.map(c=>finite(c.lon)))].sort((a,b)=>a-b),ys=[...new Set(grid.map(c=>finite(c.lat)))].sort((a,b)=>a-b);if(xs.length<2||ys.length<2||xs.length*ys.length!==grid.length||new Set(grid.map(c=>c.lon+','+c.lat)).size!==grid.length)throw new Error('今回の色セル表示は直交した元格子に対応します。');return grid.map(c=>{const x=xs.indexOf(c.lon),y=ys.indexOf(c.lat);return {id:c.cell_id,lat:c.lat,lon:c.lon,label:`${c.lat.toFixed(3)}°N / ${c.lon.toFixed(3)}°E`,west:x?(xs[x-1]+c.lon)/2:bounds.west,east:x<xs.length-1?(c.lon+xs[x+1])/2:bounds.east,south:y?(ys[y-1]+c.lat)/2:bounds.south,north:y<ys.length-1?(c.lat+ys[y+1])/2:bounds.north};});}
function value(r:ClimateMoment,R:number|null,range?:number):WindValue {return {u:finite(r.mean_u),v:finite(r.mean_v),s:finite(r.mean_speed),R:R===null?null:finite(R),dir:r.from_deg===null?null:finite(r.from_deg),timeCount:finite(r.time_count),...(range===undefined?{}:{spatialRange:finite(range)})};}
export function climateGrains(a:ClimateArtifact):ClimateGrain[]{return ['half',...(['month','season'] as const).filter(g=>!!a.summary.summaries_by_grain?.[g])] as ClimateGrain[];}
export function climatePeriods(a:ClimateArtifact,grain:ClimateGrain):ClimatePeriod[]{if(grain==='half')return a.summary.population.timebins;const group=a.summary.summaries_by_grain?.[grain];if(!group)throw Error('この固定集計には'+climateGrainLabel[grain]+'別の結果がありません。新しい集計で追加できます。');return group.timebins;}
export function climateViewModel(a:ClimateArtifact,grain:ClimateGrain='half'):WindViewModel {
 const original=a.summary,group=grain==='half'?null:original.summaries_by_grain?.[grain];
 if(grain!=='half'&&!group)throw Error('この固定集計には'+climateGrainLabel[grain]+'別の結果がありません。新しい集計で追加できます。');
 const s=group?{...original,annual:group.annual,spatial:{...original.spatial,rows:group.spatial_rows},display_scales:group.display_scales}:original;
 const years=climateYearsLabel(s.population.years_fixed),periods=climatePeriods(a,grain).map(t=>({id:t.timebin_id,month:t.month??t.months?.[0]??1,label:climatePeriodLabel(t),description:grain==='half'?`UTC ${t.start_day}–${t.end_day_min}日${t.end_day_max!==t.end_day_min?`（閏年${t.end_day_max}日まで）`:''} / ${years}`:`UTC ${climatePeriodLabel(t)} / 元半月ID ${(t.member_timebin_ids??[]).join(',')} / ${years}`,timeCount:t.n_analyses_expected}));
 const levels=[...s.levels].sort((a,b)=>a.isa_alt_m-b.isa_alt_m).map(l=>({id:l.level_id,pressure:l.level_hpa,height:l.isa_alt_m/1000,heightDescription:l.alt_geom_mean_m!==null&&l.alt_geom_min_m!==null&&l.alt_geom_max_m!==null?`ISA ${(l.isa_alt_m/1000).toFixed(2)} km / 元DB全域・全期間の幾何高度 平均${(finite(l.alt_geom_mean_m)/1000).toFixed(2)} km（${(finite(l.alt_geom_min_m)/1000).toFixed(2)}–${(finite(l.alt_geom_max_m)/1000).toFixed(2)} km）`:`ISA ${(l.isa_alt_m/1000).toFixed(2)} km（参考高度のみ／実高度未取得）`}));
 const keys=new Set(s.population.selected_cell_ids),cells=nativeDisplayCells(s.source.native_grid,s.source.bounds).filter(c=>keys.has(c.id));if(cells.length!==s.population.selected_cell_count||!cells.length)throw new Error('固定集計の対象格子と元格子が一致しません。');const am=new Map(s.annual.map(r=>[r.timebin_id+':'+r.level_id,r])),sm=new Map(s.spatial.rows.map(r=>[r.timebin_id+':'+r.cell_id,r]));if(am.size!==levels.length*periods.length||sm.size!==cells.length*periods.length)throw new Error('固定集計の面・時期・格子に欠落または重複があります。');const levelIndex=levels.findIndex(l=>l.id===s.spatial.level_id);if(levelIndex<0)throw new Error('固定集計の気圧面がありません。');
 const annual=periods.map(p=>levels.map(l=>{const r=am.get(p.id+':'+l.id);if(!r)throw new Error('年間集計の参照がありません。');return value(r,r.pooled_constancy,r.spatial_mean_speed_range);})),spatial=periods.map(p=>cells.map(c=>{const r=sm.get(p.id+':'+c.id);if(!r)throw new Error('地域集計の参照がありません。');return value(r,r.constancy);}));const q=s.query.bounds??s.source.bounds,edge={west:Math.min(q.west,...cells.map(c=>c.west)),east:Math.max(q.east,...cells.map(c=>c.east)),south:Math.min(q.south,...cells.map(c=>c.south)),north:Math.max(q.north,...cells.map(c=>c.north))};const padX=(edge.east-edge.west)*.06,padY=(edge.north-edge.south)*.06;
 return {kind:'climate',monthlyProfiles:checkedMonthlyProfiles(a),windRose:group?group.wind_rose:original.wind_rose,identity:{analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,source_id:s.source.source_id},populationLabel:`${years} · ${climateHoursLabel(s.query)} · ${climateGrainLabel[grain]}${periods.length}区分 · 対象${cells.length}/${s.source.native_grid_count}元格子${s.query.hours_utc?` · 時間帯別${Math.max(...levels.map(l=>l.pressure))}–${Math.min(...levels.map(l=>l.pressure))} hPa`:''}`,countDefinition:'時刻数は各格子のUTC解析時刻数。格子数との積は独立な気象標本数ではありません。',heightDefinition:'固定ISA参考高度の表示軸（地表・実際の場の高さではない）。実高度の取得状況は各面の説明へ。',annualDefinition:`年間ヒートマップでは、隣接面の中点で色帯を分け、端は元の面まで。UTC暦の${climateGrainLabel[grain]}別。半月は1–15日 / 16–月末。月・季節は時刻数で平均U/V/Sを結合。Rは${climateWeightLabel(s.population.spatial_weighting)}の地域平均U/V/Sから求め、各格子や半月のRの平均ではありません。${grain==='season'?' 冬は選択暦年内の12/1/2月。年をまたぐ一続きの冬標本ではありません。':''}`,spatialDefinition:'色セルは元格子中心に対応する表示上の区画。範囲内の中心を集計し、物理的な4D場の支持領域を表しません。',levels,levelIndex,annualPeriods:periods,spatialPeriods:periods,annual,spatial,cells,mapBounds:{west:edge.west-padX,east:edge.east+padX,south:edge.south-padY,north:edge.north+padY},selectionBounds:q,nativeBounds:s.source.bounds,annualSpeedMax:niceSpeedMax(s.display_scales.annual_mean_speed_max),annualRangeMax:niceSpeedMax(s.display_scales.spatial_mean_speed_range_max),spatialAllMax:niceSpeedMax(s.display_scales.all_level_cell_mean_speed_max),spatialLevelMax:niceSpeedMax(s.display_scales.selected_level_cell_mean_speed_max),metadata:{schema:'balloon.wind-figure/1',artificial:false,grain,period_membership:climatePeriods(a,grain),wind_rose:group?group.wind_rose:original.wind_rose,source:s.source,query:s.query,population:s.population,levels:s.levels,provenance:s.provenance,analysis_id:a.analysis_id}};
}
