import {mountClimate} from './climateController';
export {climateDisplayState} from './climateController';
import {aggregateFixture,fixtureViewModel} from './sources/fixtureSummary';
import {annualPlots,spatialPlot,spatialDefinition,colorbar,geographyFrame,boundaryMarkup,glyphCells} from './plots';
import {createWindExport,embedWindBackground} from './export';
// Active 0.40.1 weather screens, mounted inside the shared React platform.
export function mount(scope, bridge) {
if(bridge.mode==='climate')return mountClimate(scope,bridge);
const {window,document,setTimeout,clearTimeout,requestAnimationFrame,cancelAnimationFrame,addEventListener,MutationObserver,ResizeObserver}=scope;
const location=bridge.location||globalThis.location;
let disposed=false;const tileProbes=new Set();
const ImpactMap=window.ImpactMap;
const scrollTo=globalThis.scrollTo.bind(globalThis);
/* 0.37: geographic analysis workspace, intentionally synthetic. */
'use strict';
const controller=(()=>{
 const F=window.WindFixture,D=window.WindDirection,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const state={view:'annual',monthly:'profile',spatial:'wind',annualGrain:'quarter',spatialScale:'all',impactBase:'std',impactRoutes:false,impactView:null,level:8,point:4,from:2020,to:2025,hours:[3,9,15,21],roseGrain:'month',mapGrain:'month',landingGrain:'month',season:6,trialN:2,trialPoint:[0,0],monthlyPage:0,spatialPage:0,revision:0};
 const restoreText=new URLSearchParams(location.search).get('restore');let restored=false;
 if(restoreText){try{const payload=JSON.parse(restoreText),s=payload.returnState;if(s&&payload.kind==='synthetic-climate-proposal'){
  for(const [k,allowed] of Object.entries({view:['annual','monthly','spatial','landing'],monthly:['profile','rose'],spatial:['wind','steady'],annualGrain:['quarter','half'],spatialScale:['all','level'],impactBase:['std','photo'],roseGrain:['month','half','season'],mapGrain:['month','half'],landingGrain:['month','half']}))if(allowed.includes(s[k]))state[k]=s[k];
  for(const [k,min,max] of [['level',0,15],['point',0,8],['from',2020,2025],['to',2020,2025],['season',0,23],['monthlyPage',0,23],['spatialPage',0,23]])if(Number.isInteger(s[k])&&s[k]>=min&&s[k]<=max)state[k]=s[k];
  if(state.from>state.to){state.from=2020;state.to=2025;}state.season=Math.min(state.season,state.landingGrain==='half'?23:11);
  if(Array.isArray(s.hours)&&s.hours.length&&s.hours.every(h=>F.hours.includes(h)))state.hours=[...new Set(s.hours)];if([2,4,6].includes(s.trialN))state.trialN=s.trialN;
  if(Array.isArray(s.trialPoint)&&s.trialPoint.length===2&&F.supported(...s.trialPoint))state.trialPoint=[...s.trialPoint];state.impactRoutes=s.impactRoutes===true;if(s.impactView&&Array.isArray(s.impactView.center)&&s.impactView.center.every(Number.isFinite)&&Number.isFinite(s.impactView.zoom))state.impactView=s.impactView;restored=true;
 }}catch{}}
 const pointNames=['南西','南中央','南東','西中央','中央','東中央','北西','北中央','北東'];let cache=null,uid=0,resizeFrame=0,renderFrame=0,trialCache=null,selectedTrialCache=null;
 const fmt=(x,n=1)=>Number.isFinite(x)?x.toFixed(n):'—',text=(x,y,s,size=10,extra='')=>`<text x="${x}" y="${y}" font-size="${size}" ${extra}>${esc(s)}</text>`,line=(x1,y1,x2,y2,color='#c5d5d9',width=1,extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${extra}/>`;
 const svg=(w,h,b,label,extra='')=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" font-family="system-ui,Yu Gothic,sans-serif" role="img" aria-label="${esc(label)}" ${extra}>${b}</svg>`;
 const blue=(v,max)=>{let f=Math.max(0,Math.min(1,v/max));return `rgb(${Math.round(233-220*f)},${Math.round(246-159*f)},${Math.round(250-112*f)})`;};
 const classes=[{lo:.5,hi:5,label:'0.5–5',color:'#cbe9ee'},{lo:5,hi:10,label:'5–10',color:'#87c9dc'},{lo:10,hi:20,label:'10–20',color:'#49a6c8'},{lo:20,hi:30,label:'20–30',color:'#267cab'},{lo:30,hi:40,label:'30–40',color:'#174d81'},{lo:40,hi:Infinity,label:'40+',color:'#102953'}];
 const periodName=(grain,i)=>grain==='quarter'?`${Math.floor(i/4)+1}月 第${i%4+1}区分`:grain==='half'?`${Math.floor(i/2)+1}月${i%2?'後半':'前半'}`:grain==='season'?['冬 12–2月','春 3–5月','夏 6–8月','秋 9–11月'][i]:`${i+1}月`;
 const rowsFor=(grain,i)=>grain==='quarter'?cache.quarter[i]:grain==='half'?cache.half[i]:grain==='season'?cache.seasons[i]:cache.months[i],statsFor=(grain,i)=>grain==='quarter'?cache.quarterStats[i]:grain==='half'?cache.halfStats[i]:grain==='season'?groupStats(cache.seasons[i]):cache.monthStats[i];
 function groupStats(records){return aggregateFixture(F,records);}
 const windView=()=>fixtureViewModel(F,cache,state);
 function rebuild(){const start=performance.now(),selected=F.select({years:[state.from,state.to],hours:state.hours}),quarter=Array.from({length:48},(_,i)=>selected.filter(r=>r.quarter===i)),half=Array.from({length:24},(_,i)=>selected.filter(r=>r.bin===i)),months=Array.from({length:12},(_,i)=>selected.filter(r=>r.month===i)),seasons=Array.from({length:4},(_,i)=>selected.filter(r=>Math.floor(((r.month+1)%12)/3)===i));
  cache={selected,points:F.points.map(p=>p.id),half,quarter,months,seasons,quarterStats:quarter.map(groupStats),halfStats:half.map(groupStats),monthStats:months.map(groupStats)};cache.profileMax=Math.ceil(Math.max(...cache.monthStats.flat().filter(Boolean).map(q=>q.p90),...cache.halfStats.flat().filter(Boolean).map(q=>q.median))*1.05/5)*5;state.revision++;trialCache=null,selectedTrialCache=null;if(!restored)state.monthlyPage=state.spatialPage=0;
  const desc=`${state.from}–${state.to}年 · ${state.hours.map(h=>String(h).padStart(2,'0')).join('/')}時 JST · 全域9元格子`;
  $('#applied-summary').textContent=desc;$('#population-line').textContent=`適用中：${desc} ／ ${selected.length.toLocaleString()} 気象時刻 × 9点（各高度・等重み）`;
  $('#population-status').textContent='適用済み';$('#work-status').textContent=`日付付き人工標本を再集計 ${Math.round(performance.now()-start)} ms。図の操作は集計済みデータを利用。Nは試算地点だけを変更。`;renderAll();
 }
 const bar=colorbar;
 function levelLabels(){$$('.level-label').forEach(e=>e.textContent=`${F.pressures[state.level]} hPa（約${fmt(F.heights[state.level])} km）`);$$('.level-slider').forEach(e=>e.value=state.level);}
 const altitudeEdges=F.heights.map((h,i)=>({lo:i?(F.heights[i-1]+h)/2:h,hi:i<F.heights.length-1?(h+F.heights[i+1])/2:h}));
 const selectedYears=()=>F.years.filter(y=>y>=state.from&&y<=state.to);
 function periodDescription(grain,i){return F.periodRanges(grain,i,selectedYears()).map(r=>`${r.year}年${r.month+1}月${r.from}–${r.to}日`).join(' / ');}
 function annual(){$('#annual-plots').innerHTML=annualPlots(windView(),D);}
 function geoFrame(w,h,bounds={xmin:-46,xmax:46,ymin:-46,ymax:46}){const sw=F.geo(bounds.xmin,bounds.ymin),ne=F.geo(bounds.xmax,bounds.ymax),frame=geographyFrame(w,h,{west:sw.lon,east:ne.lon,south:sw.lat,north:ne.lat},scope.local.backgroundEnabled),P=(x,y)=>{const p=F.geo(x,y);return frame.project(p.lat,p.lon);},lo=F.geo(-40,-40),hi=F.geo(40,40);return {...frame,P,boundary:boundaryMarkup(frame.project,{west:lo.lon,east:hi.lon,south:lo.lat,north:hi.lat})};}
 function miniMap(){const W=190,H=108,g=geoFrame(W,H),b=g.b+g.boundary+F.points.map(p=>{const [x,y]=g.P(p.x,p.y);return `<circle cx="${x}" cy="${y}" r="${p.id===state.point?6:3}" fill="${p.id===state.point?'#dd7333':'#416c7b'}" stroke="white" stroke-width="1.4"/>`;}).join('');
  $('#point-minimap').innerHTML=`<button id="choose-point" class="point-picker-button" aria-haspopup="dialog" aria-controls="point-dialog" aria-label="地図を拡大して風配図の元格子点を選ぶ">${svg(W,H,b,'現在選択した元格子点の位置')}<span>地点を選ぶ ▾</span></button>`;$('#choose-point').onclick=openPointDialog;$('#rose-point-name').textContent=`対象：${pointNames[state.point]} ${fmt(F.points[state.point].lat,3)}°N / ${fmt(F.points[state.point].lon,3)}°E（元格子）`;
 }
 function openPointDialog(){const W=440,H=300,g=geoFrame(W,H),map=$('#point-dialog-map');map.innerHTML=svg(W,H,g.b+g.boundary,scope.local.backgroundEnabled?'地理院標準地図上の9元格子点':'背景未接続の9元格子点')+F.points.map(p=>{const [x,y]=g.P(p.x,p.y);return `<button class="point-hit" data-native-point="${p.id}" style="left:${x/W*100}%;top:${y/H*100}%" aria-pressed="${p.id===state.point}" aria-label="${pointNames[p.id]} ${fmt(p.lat,3)}度N ${fmt(p.lon,3)}度Eを選ぶ"><span>${pointNames[p.id]}</span></button>`;}).join('');
  $('#point-coordinates').textContent='方位名の付いた地点を選ぶと風配図へ戻ります。';$$('#point-dialog [data-native-point]').forEach(e=>{const p=F.points[+e.dataset.nativePoint];e.onfocus=e.onmouseenter=()=>$('#point-coordinates').textContent=`${pointNames[p.id]}：${fmt(p.lat,4)}°N / ${fmt(p.lon,4)}°E`;e.onclick=()=>{const y=scrollY;state.point=p.id;$('#point-dialog').close();monthly();requestAnimationFrame(()=>{scrollTo(0,y);$('#choose-point').focus({preventScroll:true});});};});showMapDialog('point-dialog','close-point-dialog');
 }
 function pageConfig(section,total,pageKey){
  document.querySelectorAll(".workspace-context").forEach(e=>e.textContent=`${state.from}–${state.to}年・${state.hours.map(h=>String(h).padStart(2,"0")).join("/")}時 JST・全域9元格子・${cache.selected.length.toLocaleString()}気象時刻（人工）`);
  const target=$(`#${section}-plots`),toolbar=$(`#${section} .workspace-toolbar`),nav=$('#view-nav').getBoundingClientRect().height;
  const available=Math.max(240,innerHeight-nav-toolbar.getBoundingClientRect().height-56),width=target.getBoundingClientRect().width;
  // The comparison unit is twelve periods. Geometry may adapt; the unit must not.
  const capacity=Math.min(12,total),pages=Math.ceil(total/capacity),choices=capacity===4?[4,2,1]:[6,4,3,2,1];
  const candidates=choices.map(cols=>{const rows=Math.ceil(capacity/cols),cellW=(width-(cols-1)*8)/cols,plotH=(available-(rows-1)*8)/rows-30;return {cols,rows,scale:Math.min((cellW-12)/190,plotH/175),cellW,plotH};}).filter(q=>q.cellW>=150);
  const best=(candidates.length?candidates:[{cols:1,rows:capacity,scale:1,cellW:width,plotH:175}]).sort((a,b)=>b.scale-a.scale)[0],cols=best.cols,rows=best.rows;
  // Narrow phones retain the same twelve-period page and scroll; never hide periods.
  const plotHeight=Math.max(145,Math.min(270,best.plotH,(best.cellW-12)*175/190));
  state[pageKey]=Math.min(state[pageKey],pages-1);const start=state[pageKey]*capacity;
  target.style.setProperty('--columns',cols);target.style.setProperty('--plot-height',plotHeight+'px');target.dataset.columns=cols;target.dataset.rows=rows;target.dataset.capacity=capacity;
  return {cols,rows,capacity,pages,start,end:Math.min(total,start+capacity)};
 }
 function pager(section,cfg,key,grain,fn){const node=$(`#${section}-pager`);node.innerHTML=`<button data-page-prev ${state[key]===0?'disabled':''}>←</button><span class="page-label">${periodName(grain,cfg.start)} ～ ${periodName(grain,cfg.end-1)} ／ ${state[key]+1} / ${cfg.pages}頁</span><button data-page-next ${state[key]===cfg.pages-1?'disabled':''}>→</button>`;node.querySelector('[data-page-prev]').onclick=()=>{state[key]--;fn();};node.querySelector('[data-page-next]').onclick=()=>{state[key]++;fn();};}
 function profile(m){const W=190,H=175,x0=30,y0=14,pw=153,ph=130,X=v=>x0+v/cache.profileMax*pw,Y=l=>y0+ph-F.heights[l]/34*ph;let b='';for(let k=0;k<=3;k++){const v=cache.profileMax*k/3;b+=line(X(v),y0,X(v),y0+ph)+text(X(v),y0+ph+13,fmt(v,0),11,'text-anchor="middle"');}for(let h=0;h<=30;h+=10){let y=y0+ph-h/34*ph;b+=line(x0,y,x0+pw,y)+text(25,y+3,h,11,'text-anchor="end"');}const q=cache.monthStats[m];b+=`<polygon fill="#ccd7d8" points="${q.map((s,l)=>`${X(s.p10)},${Y(l)}`).concat([...q].reverse().map((s,i)=>`${X(s.p90)},${Y(15-i)}`)).join(' ')}"/>`;[cache.halfStats[2*m],cache.halfStats[2*m+1]].forEach((a,j)=>b+=`<polyline data-profile-line="true" points="${a.map((s,l)=>`${X(s.median)},${Y(l)}`).join(' ')}" fill="none" stroke="${j?'#d07032':'#087f83'}" stroke-width="1.8"/>`);b+=text(1,11,'約km',11)+text(107,172,'風速 [m/s]',11,'text-anchor="middle"');return svg(W,H,b,`${m+1}月 高度プロファイル`,'data-profile="true" data-month="'+m+'" data-axis-max="'+cache.profileMax+'"');}
 function roseCounts(grain,i){const records=rowsFor(grain,i),bins=Array.from({length:16},()=>Array(classes.length).fill(0));let calm=0;for(const r of records){const [u,v]=F.value(r,state.point,state.level),speed=Math.hypot(u,v);if(speed<.5){calm++;continue;}const dir=(Math.atan2(-u,-v)*180/Math.PI+360)%360,sector=Math.floor((dir+11.25)%360/22.5),klass=classes.findIndex(c=>speed>=c.lo&&speed<c.hi);bins[sector][klass]++;}return {n:records.length,bins,calm};}
 let roseScaleCache=null,spatialScaleCache=null;
 function roseScale(grain){const key=[state.revision,grain,state.level,state.point].join(':');if(roseScaleCache?.key===key)return roseScaleCache.value;const total=grain==='half'?24:grain==='season'?4:12,peak=Math.max(...Array.from({length:total},(_,i)=>{const q=roseCounts(grain,i);return Math.max(...q.bins.map(b=>b.reduce((s,n)=>s+n,0)/q.n*100));}));const value=Math.max(10,Math.min(100,Math.ceil(peak/10)*10));roseScaleCache={key,value};return value;}
 function spatialScale(grain){const key=[state.revision,grain,state.spatialScale,state.spatialScale==='level'?state.level:'all'].join(':');if(spatialScaleCache?.key===key)return spatialScaleCache.value;const total=grain==='half'?24:12,peak=Math.max(...Array.from({length:total},(_,i)=>{const rows=statsFor(grain,i),levels=state.spatialScale==='level'?[rows[state.level]]:rows;return levels.flatMap(q=>q.locations.map(r=>r.s));}).flat());const value=Math.max(5,Math.ceil(peak/5)*5);spatialScaleCache={key,value};return value;}
 const scaleLabel=()=>state.spatialScale==='all'?'全高度・全期間共通':'この高度・全期間共通';
 function rose(grain,i){const {bins,n,calm}=roseCounts(grain,i),upper=roseScale(grain),cx=95,cy=79,radius=56;let b='';for(const n of [25,50,75,100])b+=`<circle cx="${cx}" cy="${cy}" r="${radius*n/100}" fill="none" stroke="#b6cacc" stroke-width=".7"/>`+text(cx+2,cy-radius*n/100+10,fmt(upper*n/100,(upper*n/100)%1?1:0)+'%',11);b+=line(cx-radius,cy,cx+radius,cy)+line(cx,cy-radius,cx,cy+radius);bins.forEach((cl,k)=>{let count=0;cl.forEach((q,j)=>{if(!q)return;const ri=radius*count/n*100/upper,ro=radius*(count+q)/n*100/upper,a=(k*22.5-10)*Math.PI/180,z=(k*22.5+10)*Math.PI/180,P=(r,t)=>`${cx+Math.sin(t)*r},${cy-Math.cos(t)*r}`,path=ri?`M${P(ri,a)} L${P(ro,a)} A${ro},${ro} 0 0 1 ${P(ro,z)} L${P(ri,z)} A${ri},${ri} 0 0 0 ${P(ri,a)} Z`:`M${cx},${cy} L${P(ro,a)} A${ro},${ro} 0 0 1 ${P(ro,z)} Z`;b+=`<path data-rose-bin="${k}" data-speed-class="${j}" data-count="${q}" d="${path}" fill="${classes[j].color}" stroke="white" stroke-width=".4"><title>来向 ${k*22.5}°・風速 ${classes[j].label} m/s：${q}件 / 全${n}件（${fmt(q/n*100)}%）</title></path>`;count+=q;});});b+=text(cx,13,'北 0°',11,'text-anchor="middle"')+text(161,83,'東',11)+text(cx,151,'南',11,'text-anchor="middle"')+text(16,83,'西',11)+text(cx,172,`N=${n} / 静穏 ${fmt(calm/n*100)}%`,11,'text-anchor="middle"');return svg(190,175,b,periodName(grain,i)+'の風配図',`data-rose="true" data-period="${i}" data-sample-count="${n}" data-radius-max="${upper}"`);}
 function monthly(){const isRose=state.monthly==='rose',grain=isRose?state.roseGrain:'month',total=grain==='half'?24:grain==='season'?4:12;$('#rose-controls').hidden=!isRose;$('#rose-legend').hidden=!isRose;$('#monthly-definition').textContent=isRose?`来向16方位×速度階級。半径0–${roseScale(grain)}%はこの高度・地点の全${total}期間で共通（頁間固定）。静穏<0.5m/sも分母に含む。`:'全域9元格子×選択気象時刻の等重み集計。青緑＝前半中央値、橙＝後半中央値、灰帯＝月全体p10–p90。全12月共通軸、上限は表示帯・線の最大＋余白。';if(isRose){miniMap();$('#rose-legend').innerHTML=classes.map(c=>`<span><i style="background:${c.color}"></i>${c.label} m/s</span>`).join('');}if(!$('#monthly-pager').innerHTML)$('#monthly-pager').innerHTML='<span>時期のページ</span>';const cfg=pageConfig('monthly',total,'monthlyPage');pager('monthly',cfg,'monthlyPage',grain,monthly);$('#monthly-plots').innerHTML=Array.from({length:cfg.end-cfg.start},(_,j)=>{const i=cfg.start+j;return `<article class="plot-card" data-figure="${isRose?17:15}"><h3 title="${esc(grain==='season'?'選択されたJST暦年内の季節':periodDescription(grain,i))}">${periodName(grain,i)}</h3>${isRose?rose(grain,i):profile(i)}</article>`;}).join('');pageConfig('monthly',total,'monthlyPage');}
 function spatialMap(grain,i){return spatialPlot(windView(),i,state.spatial,state.spatialScale,scope.local.backgroundEnabled);}
 function spatial(){const grain=state.mapGrain,total=grain==='half'?24:12;$('#spatial-definition').textContent=state.spatial==='wind'?'色＝各元格子の平均スカラー風速。等長矢印＝平均ベクトルの移流先（風配の来向とは逆）。R<0.3は灰。地理範囲は固定。色上限は選択した尺度で共通。':'色＝定常度R（0〜1）。向きの打消しと風の弱さは別です。平均風速・風配図と併読してください。全期間/高度で同じ尺度。';$('#scale-control').hidden=state.spatial!=='wind';$('#spatial-definition').textContent+=state.spatial==='wind'?` ${scaleLabel()}：0–${spatialScale(grain)} m/s（適用中の年・時刻・${grain==='half'?'半月':'月'}別）。母集団/区切り変更時は再評価。`:'';$('#spatial-definition').textContent+=' 標準地図を淡色加工。色は78%重ね、厳密値は格子に重ねて確認。';$('#spatial-legend').innerHTML=bar(state.spatial==='wind'?spatialScale(grain):1,state.spatial==='wind'?scaleLabel()+' [m/s]':'全期間・高度共通 定常度 R',190,43,.78);if(!$('#spatial-pager').innerHTML)$('#spatial-pager').innerHTML='<span>時期のページ</span>';const cfg=pageConfig('spatial',total,'spatialPage');pager('spatial',cfg,'spatialPage',grain,spatial);$('#spatial-plots').innerHTML=Array.from({length:cfg.end-cfg.start},(_,j)=>{const i=cfg.start+j;return `<article class="plot-card" data-figure="${state.spatial==='wind'?20:23}"><h3 title="${esc(grain==='season'?'選択されたJST暦年内の季節':periodDescription(grain,i))}">${periodName(grain,i)}</h3>${spatialMap(grain,i)}</article>`;}).join('');pageConfig('spatial',total,'spatialPage');}
 function ellipse(points){const n=points.length,m=[0,0];for(const p of points){m[0]+=p[0]/n;m[1]+=p[1]/n;}let a=0,b=0,c=0;for(const p of points){const x=p[0]-m[0],y=p[1]-m[1];a+=x*x/(n-1);b+=x*y/(n-1);c+=y*y/(n-1);}const theta=.5*Math.atan2(2*b,a-c),d=Math.sqrt((a-c)**2+4*b*b),l1=(a+c+d)/2,l2=Math.max(1e-8,(a+c-d)/2),ct=Math.cos(theta),st=Math.sin(theta),radii=points.map(p=>{const x=p[0]-m[0],y=p[1]-m[1];return Math.sqrt((x*ct+y*st)**2/l1+(-x*st+y*ct)**2/l2);}).sort((a,b)=>a-b),r=[.5,.9,.95].map(p=>radii[Math.ceil(p*n)-1]);return {n,mean:m,l1,l2,theta,r,coverage:r.map(q=>radii.filter(v=>v<=q+1e-12).length)};}
 function contour(e,k,P,color='#c56728'){const pts=[];for(let i=0;i<=90;i++){const t=2*Math.PI*i/90,a=e.r[k]*Math.sqrt(e.l1)*Math.cos(t),b=e.r[k]*Math.sqrt(e.l2)*Math.sin(t),x=e.mean[0]+a*Math.cos(e.theta)-b*Math.sin(e.theta),y=e.mean[1]+a*Math.sin(e.theta)+b*Math.cos(e.theta);pts.push(P(x,y).join(','));}return `<polygon data-contour="${[50,90,95][k]}" points="${pts.join(' ')}" fill="${color}" fill-opacity=".04" stroke="white" stroke-width="4"/><polygon points="${pts.join(' ')}" fill="none" stroke="${color}" stroke-width="2" ${k===1?'stroke-dasharray="8 4"':k===2?'stroke-dasharray="2 4"':''}/>`;}
 function trialAt(x,y,records,id){const cloud=records.map(r=>F.displacementAt(r,x,y));return{id,x,y,cloud,e:ellipse(cloud)};}
 function trialData(){const key=[state.revision,state.trialN,state.landingGrain,state.season].join(':');if(trialCache?.key===key)return trialCache;const records=rowsFor(state.landingGrain,state.season),points=[];for(let j=0;j<=state.trialN;j++)for(let i=0;i<=state.trialN;i++)points.push(trialAt(-40+80*i/state.trialN,-40+80*j/state.trialN,records,points.length));return trialCache={key,points,records};}
 function selectedTrial(data=trialData()){const [x,y]=state.trialPoint,key=[state.revision,state.landingGrain,state.season,x,y].join(':'),onGrid=data.points.find(p=>Math.abs(p.x-x)<1e-7&&Math.abs(p.y-y)<1e-7);if(onGrid){selectedTrialCache={key,point:onGrid};return onGrid;}if(selectedTrialCache?.key!==key)selectedTrialCache={key,point:trialAt(x,y,data.records,'retained')};return{...selectedTrialCache.point,id:'retained',retained:true};}
 function handoff(point){const geo=F.geo(point[0],point[1]),payload={version:1,kind:'synthetic-climate-proposal',launch:geo,provenance:{years:[state.from,state.to],weatherHoursJST:[...state.hours],season:{grain:state.landingGrain,index:state.season,label:periodName(state.landingGrain,state.season)},dataset:'synthetic-weather-v3-calendar',calendar:F.calendarDefinition,periodRanges:F.periodRanges(state.landingGrain,state.season,selectedYears())},flightTime:null,returnState:JSON.parse(JSON.stringify(state))};return {payload,url:'#season'};}
 let impact=null;
 function selectImpactPoint(x,y){if(!F.supported(x,y)){ $('#impact-selection-status').textContent='人工場の放球気柱範囲内で指定してください。旧選択は保持しています。';return false;}state.trialPoint=[x,y];landing();return true;}
 function landing(){const data=trialData(),selected=selectedTrial(data),displayPoints=selected.retained?[...data.points,selected]:data.points;$('#season-slider').max=state.landingGrain==='half'?23:11;$('#season-slider').value=state.season;$('#season-label').textContent=periodName(state.landingGrain,state.season);$('#season-label').title=periodDescription(state.landingGrain,state.season);if(!impact)impact=ImpactMap.create({element:'impact-map',state,F,selectPoint:selectImpactPoint});impact.render({data,selected,displayPoints,period:periodName(state.landingGrain,state.season)});$('#impact-legend').innerHTML=bar(80,'地点矢印の色：平均到達点まわりのRMS幅 [km]',330);const loc=F.geo(selected.x,selected.y),mean=F.geo(...selected.e.mean);$('#selected-site-name').textContent=`${fmt(loc.lat,4)}°N / ${fmt(loc.lon,4)}°E`;$('#impact-lat').value=fmt(loc.lat,5);$('#impact-lon').value=fmt(loc.lon,5);$('#selected-site-kind').textContent=selected.retained?'地図で指定した地点、または密度を変更する前の地点を保持しています。格子点数には含めません。':'現在の格子試算地点。分割Nを変えても選択した場所は保持します。';$('#selected-site-stats').innerHTML=`<dt>気象標本</dt><dd>${data.records.length}</dd><dt>平均到達位置</dt><dd>${fmt(mean.lat,3)}°N<br>${fmt(mean.lon,3)}°E</dd><dt>50 / 90 / 95%内</dt><dd>${selected.e.coverage.join(' / ')}</dd>`;const h=handoff(state.trialPoint);$('#open-planning').href=h.url;$('#open-planning').dataset.payload=JSON.stringify(h.payload);}
 function metadata(){return {version:'0.46',directionDefinition:D.definition,artificial:true,source:F.definition,view:state.view,years:[state.from,state.to],weatherValidHoursJST:[...state.hours],nativeGridPoints:9,selectedRecordCount:cache.selected.length,spatialWeight:'各気象時刻・9元格子を等重み、面積補正なし',annualAltitudeDefinition:'概算z[km]=7.2ln(1000/p[hPa])の線形座標。隣接面高度の中点で色帯を区切り、上下端は端の実面高度まで。表示上の近似で物理場の外挿ではない',roseRadiusMax:roseScale(state.roseGrain),spatialSpeedMax:spatialScale(state.mapGrain),spatialScaleMode:state.spatialScale,spatialDisplay:(scope.local.backgroundEnabled?'標準地図を淡色加工、色を78%重ねる。':'背景未接続、色を78%重ねる。')+scaleLabel()+'。対象年・時間mask・月/半月の変更では尺度を再評価。',annualGrain:state.annualGrain,calendar:F.calendarDefinition,annualPeriodDefinition:'JST月内階層分割。48/24区分。月目盛と原日付標本を使用しISO週ではない',periodMembership:Array.from({length:state.annualGrain==='quarter'?48:24},(_,i)=>({period:i,ranges:F.periodRanges(state.annualGrain,i,selectedYears()),weatherRecordCount:rowsFor(state.annualGrain,i).length})),halfPeriodMembership:Array.from({length:24},(_,i)=>({period:i,ranges:F.periodRanges('half',i,selectedYears()),weatherRecordCount:cache.half[i].length})),level:state.level,pressure:F.pressures[state.level],monthly:state.monthly,spatial:state.spatial,roseGrain:state.roseGrain,mapGrain:state.mapGrain,rosePoint:F.points[state.point],monthlyPage:state.monthlyPage,spatialPage:state.spatialPage,profileAxisMax:cache.profileMax,landingGrain:state.landingGrain,landingPeriod:state.season,trialN:state.trialN,trialGridPointCount:(state.trialN+1)**2,trialPoint:[...state.trialPoint],retainedTrialPoint:!!selectedTrial().retained,impactView:state.impactView,impactRoutes:state.impactRoutes,impactBasemap:state.impactBase,impactContourStyles:impact?.contourStyles,impactBackgroundAtCapture:impact?{...impact.tileState}:null,basemap:scope.local.backgroundEnabled?'国土地理院 地理院タイル（標準地図） https://maps.gsi.go.jp/development/ichiran.html#std':'未接続',contours:'共分散方向とceil(p*N)番目の経験Mahalanobis半径。有限標本包含であり将来予測被覆率/HDRではない。'};}
 function exportSVG(target){if(target==='annual-plots'||target==='spatial-plots'){const vm=windView();return createWindExport(vm,target==='annual-plots'?'annual':'spatial',[...$('#'+target).querySelectorAll('svg')],{mode:state.spatial,scale:state.spatialScale,page:state.spatialPage,background:scope.local.backgroundEnabled,legend:target==='annual-plots'?vm.annualDefinition:$('#spatial-definition').textContent});}const svgs=target==='landing-plots'?[new DOMParser().parseFromString(impact.exportSVG(),'image/svg+xml').documentElement]:[...$('#'+target).querySelectorAll('svg')],columns=target==='annual-plots'||target==='landing-plots'?1:Math.min(4,svgs.length),cellW=target==='annual-plots'?1100:target==='landing-plots'?1000:270,cellH=target==='annual-plots'?325:target==='landing-plots'?700:280,W=columns*cellW+30,meta=metadata(),heading=$('#'+state.view+' h2').textContent,legend=state.view==='monthly'?(state.monthly==='profile'?$('#monthly-definition').textContent:`16方位の来向・全標本を分母。半径0–${roseScale(state.roseGrain)}%（この高度・地点の全期間共通）。速度階級0.5–5 / 5–10 / 10–20 / 20–30 / 30–40 / 40+ m/s、色は画面と同じ。`+$('#rose-point-name').textContent):state.view==='spatial'?$('#spatial-definition').textContent:state.view==='annual'?`同じ月内${state.annualGrain==='quarter'?4:2}区分/高度軸。端数日は暦年で循環配分。平均速さ・来向・定常度・地点間の期間平均速さ幅。`:`同じ処方高度を使う凍結気柱の人工例。${$('#impact-route-note').textContent}`;let b=`<rect width="100%" height="100%" fill="white"/><metadata>${esc(JSON.stringify(meta))}</metadata>`+text(15,25,heading+' — 人工データ',18)+text(15,46,`${state.from}–${state.to}年 / ${state.hours.join('/')}時 JST / 全域9元格子 / 気象時刻N=${cache.selected.length}`,11);
  const lines=legend.match(/.{1,75}/gu)||[];lines.forEach((s,i)=>b+=text(15,65+i*15,s,10));let top=90+lines.length*15;if(state.view==='monthly'&&state.monthly==='rose'){b+=text(15,top,`${F.pressures[state.level]} hPa / 約${fmt(F.heights[state.level])}km / 元格子 ${pointNames[state.point]}`,11);classes.forEach((c,i)=>{const x=15+i*120;b+=`<rect x="${x}" y="${top+12}" width="14" height="10" fill="${c.color}"/>`+text(x+19,top+22,c.label+' m/s',10);});top+=55;}if(state.view==='spatial'){b+=text(15,top,`${F.pressures[state.level]} hPa / 約${fmt(F.heights[state.level])}km`,11)+`<g transform="translate(15 ${top+10})">${bar(state.spatial==='wind'?spatialScale(state.mapGrain):1,state.spatial==='wind'?scaleLabel()+' 平均風速 [m/s]':'全期間・高度共通 定常度 R',270,45,.78).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`;top+=75;}
  let annualY=top;svgs.forEach((el,i)=>{const vb=el.viewBox.baseVal,scale=target==='annual-plots'?(cellW-20)/vb.width:Math.min((cellW-20)/vb.width,(cellH-30)/vb.height),label=el.closest('.plot-card')?.querySelector('h3')?.textContent||el.getAttribute('aria-label'),x=15+i%columns*cellW,y=target==='annual-plots'?annualY:top+Math.floor(i/columns)*cellH;b+=text(x,y,label,12)+`<g transform="translate(${x} ${y+8}) scale(${scale})">${el.innerHTML}</g>`;if(target==='annual-plots')annualY+=vb.height*scale+30;});let footerY=(target==='annual-plots'?annualY:top+Math.ceil(svgs.length/columns)*cellH)+5;const credit=!scope.local.backgroundEnabled?'地理背景：未接続':state.view==='landing'?impact.creditText():'地理背景：国土地理院 地理院タイル（標準地図） https://maps.gsi.go.jp/development/ichiran.html#std',creditLines=credit.match(/.{1,90}/gu)||[];creditLines.forEach((value,i)=>b+=text(15,footerY+i*13,value,9));const height=footerY+creditLines.length*13+12,source=svg(W,height,b,heading).replace("<svg ",`<svg width="${W}" height="${height}" `);return {source,metadata:meta};}
 async function exportStandalone(target){if(target==='annual-plots'||target==='spatial-plots')return embedWindBackground(exportSVG(target));const r=exportSVG(target),urls=[...new Set([...r.source.matchAll(/href="(https:\/\/cyberjapandata\.gsi\.go\.jp[^" ]+)"/g)].map(m=>m[1]))];
  const entries=await Promise.all(urls.map(async url=>{const response=await fetch(url);if(!response.ok)throw new Error(`地図取得 ${response.status}`);const blob=await response.blob(),data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});return [url,data];}));
  for(const [url,data] of entries)r.source=r.source.split(url).join(data);r.metadata.embeddedMapTileCount=entries.length;if(r.metadata.view==='landing'&&scope.local.backgroundEnabled){r.metadata.impactBackgroundSaved={complete:true,embeddedTileCount:entries.length};r.source=r.source.replace(/(<text\b[^>]*\bdata-impact-background="true"[^>]*>)[\s\S]*?(<\/text>)/,(_,a,z)=>a+esc(`背景: ${r.metadata.impactBasemap==='photo'?'写真':'通常地図'} ${entries.length}枚を保存用に再取得・埋込済み`)+z);}r.metadata.mapCapture=scope.local.backgroundEnabled?'保存時の表示範囲のみ。国土地理院 '+(r.metadata.view==='landing'&&r.metadata.impactBasemap==='photo'?'写真':'標準地図'):'未接続。背景画像なし。';r.source=r.source.replace(/<metadata>[\s\S]*?<\/metadata>/,`<metadata>${esc(JSON.stringify(r.metadata))}</metadata>`);return r;
 }
 async function save(target){const buttons=$$('.save');buttons.forEach(b=>b.disabled=true);$('#work-status').textContent='図と、表示範囲の地図背景を保存用にまとめています…';try{const r=await exportStandalone(target);window.WindUI.lastExport=r;const u=URL.createObjectURL(new Blob([r.source],{type:'image/svg+xml;charset=utf-8'})),a=document.createElement('a');a.href=u;const saved=r.metadata,kind=saved.view==='monthly'?saved.monthly:saved.view==='spatial'?saved.spatial:null,label=saved.view==='annual'?'年間の高度構造':saved.view==='monthly'?(kind==='rose'?'月・季節の風配図':'月別の高度プロファイル'):saved.view==='spatial'?(kind==='steady'?'地域の風向定常度':'地域の平均風'):'放球地点の試算';a.download=`weather-${saved.view}${kind?'-'+kind:''}-046.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);$('#work-status').textContent=`${label}の図を、保存開始時の背景・対象・定義・凡例とともに単独表示できるSVGへ保存しました。`;}catch(e){$('#work-status').textContent='背景を取得できないため保存していません。接続を確認して再試行してください。';}finally{buttons.forEach(b=>b.disabled=false);}}
 const tileState=new Map();
 function monitorMaps(){if(disposed)return;const images=$$('[data-basemap]');if(!images.length)return;let changed=false;for(const el of images){const url=el.getAttribute('href'),status=tileState.get(url);if(status==='failed')el.setAttribute('visibility','hidden');else if(status==='loaded')el.removeAttribute('visibility');if(!status){changed=true;tileState.set(url,'loading');const probe=new Image();tileProbes.add(probe);probe.onload=()=>{tileProbes.delete(probe);if(disposed)return;tileState.set(url,'loaded');$$('[data-basemap]').filter(e=>e.getAttribute('href')===url).forEach(e=>e.removeAttribute('visibility'));mapStatus();};probe.onerror=()=>{tileProbes.delete(probe);if(disposed)return;tileState.set(url,'failed');$$('[data-basemap]').filter(e=>e.getAttribute('href')===url).forEach(e=>e.setAttribute('visibility','hidden'));mapStatus();};probe.src=url;}}if(changed)mapStatus();}
 function retryMaps(images){if(!images.length)return;const stamp=Date.now(),urls=new Map();for(const el of images){const original=el.getAttribute('href');if(!urls.has(original)){const u=new URL(original);u.searchParams.set('retry',stamp);urls.set(original,u.href);}el.setAttribute('href',urls.get(original));}monitorMaps();mapStatus();}
 function showMapDialog(id,closeId){$('#'+id).showModal();$('#'+closeId).focus();monitorMaps();retryMaps($$('#'+id+' [data-basemap]').filter(e=>tileState.get(e.getAttribute('href'))==='failed'));mapStatus();}
 let mapStatusSignature='';
 function mapStatus(){if(disposed)return;if(!scope.local.backgroundEnabled){const node=$('#map-status');node.hidden=false;const text='背景地図は未接続。地理院の背景へ接続すると表示地域のタイルを取得します。';if(node.textContent!==text)node.textContent=text;return;}const visible=$$('.view:not([hidden]) [data-basemap],dialog[open] [data-basemap]'),urls=[...new Set(visible.map(e=>e.getAttribute('href')))],failed=urls.filter(u=>tileState.get(u)==='failed').length,loading=urls.filter(u=>tileState.get(u)==='loading').length,node=$('#map-status'),dialogs=$$('dialog[data-map-dialog]');const signature=[state.view,...dialogs.map(d=>d.id+':'+d.open),...urls.map(u=>u+':'+tileState.get(u))].join('|');if(signature===mapStatusSignature)return;mapStatusSignature=signature;
  for(const d of dialogs){const local=[...new Set([...d.querySelectorAll('[data-basemap]')].map(e=>e.getAttribute('href')))],bad=local.filter(u=>tileState.get(u)==='failed').length,busy=local.filter(u=>tileState.get(u)==='loading').length,label=d.dataset.mapName;d.querySelector('[data-map-status]').textContent=d.open?(bad?`${label}地図 ${bad} 枚を取得できません。接続を確認して再読込してください。`:busy?`${label}の標準地図を読み込んでいます…`:`${label}の標準地図を読み込みました。`):'';d.querySelector('[data-map-retry]').hidden=!d.open||!bad;}
  node.hidden=!urls.length;node.classList.toggle('map-failed',failed>0);node.innerHTML=failed?`標準地図 ${failed} 枚を取得できません。地名・道路が欠けているため、周辺の判断には使えません。接続を確認して <button id="retry-map">再読込</button>`:loading?'標準地図を読み込んでいます…':'地理背景：<a href="https://maps.gsi.go.jp/development/ichiran.html#std" target="_blank" rel="noopener">国土地理院 標準地図</a>（地名・道路）／ 気象・試算値は人工';const retry=$('#retry-map');if(retry)retry.onclick=()=>retryMaps(visible.filter(e=>tileState.get(e.getAttribute('href'))==='failed'));}
 new MutationObserver(()=>{monitorMaps();mapStatus();}).observe($('main'),{childList:true,subtree:true});
 function focusWorkspace(){scrollTo({top:$('#population-line').getBoundingClientRect().bottom+scrollY+8,behavior:'instant'});} function renderAll(){document.querySelectorAll('.workspace-context').forEach(e=>e.textContent=`${state.from}–${state.to}年・${state.hours.map(h=>String(h).padStart(2,'0')).join('/')}時 JST・全域9元格子・${cache.selected.length.toLocaleString()}気象時刻（人工）`);levelLabels();annual();if(state.view==='monthly')monthly();if(state.view==='spatial')spatial();if(state.view==='landing')landing();document.documentElement.style.setProperty('--nav-h',$('#view-nav').getBoundingClientRect().height+'px');}
 for(const id of ['from-year','to-year'])$('#'+id).innerHTML=F.years.map(y=>`<option value="${y}">${y}年</option>`).join('');$('#from-year').value=state.from;$('#to-year').value=state.to;$('#hour-controls').innerHTML=F.hours.map(h=>`<label><input type="checkbox" value="${h}" checked>${String(h).padStart(2,'0')}時</label>`).join('');
 $$('[data-map-retry]').forEach(button=>button.onclick=()=>retryMaps([...button.closest('dialog').querySelectorAll('[data-basemap]')].filter(e=>tileState.get(e.getAttribute('href'))==='failed')));$('#close-point-dialog').onclick=()=>$('#point-dialog').close();$('#point-dialog').addEventListener('close',()=>{$('#choose-point')?.focus({preventScroll:true});mapStatus();});
 $('#apply').onclick=()=>{const from=+$('#from-year').value,to=+$('#to-year').value,hours=$$('#hour-controls input:checked').map(e=>+e.value);if(from>to||!hours.length){$('#population-status').textContent=from>to?'開始年は終了年以下にしてください。':'時刻を一つ以上選んでください。';return;}Object.assign(state,{from,to,hours});$('#apply').disabled=true;$('#population-status').textContent='原標本を再集計中…';setTimeout(()=>{try{rebuild();}finally{$('#apply').disabled=false;}},20);};
 $$('[data-view]').forEach(e=>e.onclick=()=>{state.view=e.dataset.view;$$('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b===e)));$$('.view').forEach(v=>v.hidden=v.id!==state.view);renderAll();focusWorkspace();});
 for(const group of ['monthly','spatial'])$$('[data-'+group+']').forEach(e=>e.onclick=()=>{state[group]=e.dataset[group];if(group==='monthly')state.monthlyPage=0;else state.spatialPage=0;$$('[data-'+group+']').forEach(b=>b.setAttribute('aria-pressed',String(e===b)));({monthly,spatial})[group]();});
 $$('.level-slider').forEach(e=>e.oninput=()=>{state.level=+e.value;levelLabels();cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(()=>{if(state.view==='monthly')monthly();else spatial();});});
 $('#annual-grain').onchange=e=>{state.annualGrain=e.target.value;annual();};$('#spatial-scale').onchange=e=>{state.spatialScale=e.target.value;spatial();};$('#impact-base').onchange=e=>{state.impactBase=e.target.value;impact?.setBase();landing();};$('#impact-routes').onchange=e=>{state.impactRoutes=e.target.checked;landing();};$('#impact-fit').onclick=()=>impact?.fit();$('#impact-pick').onclick=()=>impact?.togglePick();$('#impact-coordinate-apply').onclick=()=>{const lat=+$('#impact-lat').value,lon=+$('#impact-lon').value,[x,y]=F.xy(lat,lon);selectImpactPoint(x,y);};$('#rose-grain').onchange=e=>{state.roseGrain=e.target.value;state.monthlyPage=0;monthly();};$('#map-grain').onchange=e=>{state.mapGrain=e.target.value;state.spatialPage=0;spatial();};$('#landing-grain').onchange=e=>{const g=e.target.value;state.season=g==='half'?state.season*2:Math.floor(state.season/2);state.landingGrain=g;landing();};$('#season-slider').oninput=e=>{state.season=+e.target.value;cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(landing);};$('#trial-n').onchange=e=>{state.trialN=+e.target.value;landing();};$$('.save').forEach(e=>e.onclick=()=>save(e.dataset.target));
 addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{document.documentElement.style.setProperty('--nav-h',$('#view-nav').getBoundingClientRect().height+'px');if(state.view==='monthly')monthly();if(state.view==='spatial')spatial();if(!$('#population').open&&scrollY>0)focusWorkspace();});});
 window.WindUI={state,F,focusWorkspace,get cache(){return cache},get trials(){return trialData()},get selectedTrial(){return selectedTrial()},groupStats,roseCounts,roseScale,spatialScale,altitudeEdges,ellipse,metadata,exportSVG,exportStandalone,handoff,renderAll,get impact(){return impact},get tileState(){return Object.fromEntries(tileState)}};for(const h of $$('#hour-controls input'))h.checked=state.hours.includes(+h.value);$('#annual-grain').value=state.annualGrain;$('#spatial-scale').value=state.spatialScale;$('#impact-base').value=state.impactBase;$('#impact-routes').checked=state.impactRoutes;$('#rose-grain').value=state.roseGrain;$('#map-grain').value=state.mapGrain;$('#landing-grain').value=state.landingGrain;$('#trial-n').value=state.trialN;$$('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===state.view)));$$('.view').forEach(v=>v.hidden=v.id!==state.view);for(const group of ['monthly','spatial'])$$('[data-'+group+']').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[group]===state[group])));rebuild();if(restored){restored=false;requestAnimationFrame(focusWorkspace);}
return window.WindUI;})();

return {controller:window.WindUI,snapshot:()=>structuredClone(window.WindUI.state),dispose(){disposed=true;for(const image of tileProbes){image.onload=null;image.onerror=null;}tileProbes.clear();window.WindUI.impact?.destroy?.();scope.dispose();}};
}


