// Derived from the archived 0.40.1 r2 screen; see frontend/SCREEN_PROVENANCE.md.
export function install(scope) {
const {window,document}=scope; const L=scope.local.L;
/* Geographic presentation of already computed climate trials.
 * Statistics and period membership are owned by app.js / fixture.js.
 * One scene feeds the live map and the standalone SVG, preserving the view.
 */
'use strict';
window.ImpactMap=(()=>{
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const photoCredit='国土地理院 地理院タイル（写真）：Landsat8（GSI,TSIC,GEO Grid/AIST / U.S.Geological Survey）、GEBCO、該当詳細地域GRUS（©Axelspace）。低倍率：NASA LP DAAC / USGS EROS';
 const standardCredit='国土地理院 地理院タイル（標準地図）';
 const contourStyles=[{percent:50,dash:null,name:'実線'},{percent:90,dash:'8 4',name:'破線'},{percent:95,dash:'2 4',name:'点線'}];
 function create({element,state,F,selectPoint}){
  const $=id=>document.getElementById(id),map=L.map(element,{zoomSnap:.25,zoomDelta:.5,preferCanvas:true,zoomAnimation:false,fadeAnimation:false,minZoom:5,maxZoom:18}),layer=L.layerGroup().addTo(map);
  let disposed=false,tileLayer=null,current=null,scene=[],pick=false,first=true,routeCache=null,tileGeneration=0,good=0,bad=0,backgroundStatus='背景地図を読込中…';
  const geo=(x,y)=>{const p=F.geo(x,y);return[p.lat,p.lon];},view=()=>({center:[map.getCenter().lat,map.getCenter().lng],zoom:map.getZoom()});
  const creditText=()=>!scope.local.backgroundEnabled?'地理背景：未接続':state.impactBase==='photo'?photoCredit:standardCredit;
  const palette=()=>state.impactBase==='photo'?{up:'#42dcff',down:'#ffd35e',contour:'#ffdb75',point:'#fff1aa',halo:'#122c42'}:{up:'#0073ad',down:'#c46017',contour:'#a64e15',point:'#ba601d',halo:'white'};
  map.attributionControl.setPrefix('<a href="https://leafletjs.com/">Leaflet</a>');
  map.on('moveend zoomend',()=>{if(map._loaded)state.impactView=view();});
  map.on('zoomend',()=>{if(current)draw();});
  map.on('click',e=>{if(!pick)return;const [x,y]=F.xy(e.latlng.lat,e.latlng.lng);if(selectPoint(x,y)){togglePick(false);$('impact-selection-status').textContent='指定した地点を選択しました。拡大率と注目地域は保持しています。';}});
  function setBase(){const generation=++tileGeneration;if(tileLayer){tileLayer.off();map.removeLayer(tileLayer);}good=bad=0;if(!scope.local.backgroundEnabled){backgroundStatus='背景未接続 · ヘッダーから地理院背景を接続できます';return;}const photo=state.impactBase==='photo';$(element).classList.toggle('impact-photo',photo);tileLayer=L.tileLayer(`https://cyberjapandata.gsi.go.jp/xyz/${photo?'seamlessphoto':'std'}/{z}/{x}/{y}.${photo?'jpg':'png'}`,{minZoom:5,maxZoom:18,maxNativeZoom:18,attribution:`<a href="https://maps.gsi.go.jp/development/ichiran.html#${photo?'seamlessphoto':'std'}" target="_blank" rel="noopener">${esc(creditText())}</a>`});
   const status=()=>{if(disposed||generation!==tileGeneration)return;const node=$('impact-map-status'),name=photo?'写真':'通常地図',pending=tileLayer.isLoading();backgroundStatus=bad?`${name} ${bad}枚欠落${pending?'・読込中':''} — 背景のみ欠落。入力と結果は保持`:pending||!good?`${name}を読込中…`:`${name}を表示中`;node.classList.toggle('impact-map-failed',bad>0);node.innerHTML=esc(backgroundStatus)+(bad?' <button id="impact-retry">再読込</button>':'');const button=$('impact-retry');if(button)button.onclick=setBase;};
   tileLayer.on('tileload',()=>{if(disposed||generation!==tileGeneration)return;good++;status();}).on('tileerror',()=>{if(disposed||generation!==tileGeneration)return;bad++;status();}).on('loading',()=>{if(disposed||generation!==tileGeneration)return;good=bad=0;status();}).on('load',status).addTo(map);status();if(current)draw();
  }
  function togglePick(force){pick=force===undefined?!pick:force;$(element).classList.toggle('picking',pick);$('impact-pick').setAttribute('aria-pressed',String(pick));$('impact-pick').textContent=pick?'地点指定を終了':'地図で放球点を指定';$('impact-selection-status').textContent=pick?'放球気柱の破線範囲内をクリックして指定。ドラッグは地図移動です。Escで終了。':'地図のドラッグは移動、＋/−は拡大。地点マークを押すと選択します。';}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pick&&state.view==='landing')togglePick(false);});
  function routes(){const {selected,data}=current,key=[state.revision,state.landingGrain,state.season,selected.x,selected.y].join(':');if(routeCache?.key===key)return routeCache;const generated=F.generateSeason({lat:F.geo(selected.x,selected.y).lat,lon:F.geo(selected.x,selected.y).lon,years:[state.from,state.to],hours:state.hours,period:{grain:state.landingGrain,index:state.season}});if(generated.sourceCount!==data.records.length)throw new Error('軌道と落下統計の母集団が一致しません');const samples=generated.samples.map(s=>({up:s.history.slice(0,61).map(r=>geo(selected.x+r.e,selected.y+r.n)),down:s.history.slice(60).map(r=>geo(selected.x+r.e,selected.y+r.n))})),mean={up:[],down:[]};for(const phase of ['up','down'])for(let i=0;i<samples[0][phase].length;i++)mean[phase].push([0,1].map(k=>samples.reduce((n,p)=>n+p[phase][i][k],0)/samples.length));return routeCache={key,samples,mean};}
  function line(coords,color,weight=2,opacity=1,extra={}){scene.push({kind:'line',coords,color,weight,opacity,...extra});}
  function arrow(start,end,color){line([start,end],'white',4,.9);line([start,end],color,2.2,.95);const a=map.latLngToContainerPoint(start),z=map.latLngToContainerPoint(end),dx=z.x-a.x,dy=z.y-a.y,len=Math.hypot(dx,dy);if(len<2)return;const ux=dx/len,uy=dy/len,head=[[z.x-8*ux-4*uy,z.y-8*uy+4*ux],[z.x,z.y],[z.x-8*ux+4*uy,z.y-8*uy-4*ux]].map(q=>{const ll=map.containerPointToLatLng(q);return[ll.lat,ll.lng];});line(head,'white',4);line(head,color,2);}
  function buildScene(){scene=[];if(!current)return;const {data,selected,displayPoints}=current,c=palette(),bounds=[geo(-40,-40),geo(40,-40),geo(40,40),geo(-40,40),geo(-40,-40)];line(bounds,state.impactBase==='photo'?'white':'#294b5b',2,.9,{dash:'7 5'});
   for(const p of displayPoints){const rms=Math.sqrt((p.e.l1+p.e.l2)*(p.e.n-1)/p.e.n),f=Math.min(1,rms/80),color=`rgb(${Math.round(233-220*f)},${Math.round(246-159*f)},${Math.round(250-112*f)})`;arrow(geo(p.x,p.y),geo(...p.e.mean),color);}
   for(const k of [2,1,0]){const e=selected.e,coords=[];for(let i=0;i<=90;i++){const t=2*Math.PI*i/90,a=e.r[k]*Math.sqrt(e.l1)*Math.cos(t),b=e.r[k]*Math.sqrt(e.l2)*Math.sin(t);coords.push(geo(e.mean[0]+a*Math.cos(e.theta)-b*Math.sin(e.theta),e.mean[1]+a*Math.sin(e.theta)+b*Math.cos(e.theta)));}scene.push({kind:'polygon',coords,color:c.halo,weight:4,opacity:.9,fill:c.contour,fillOpacity:.025});line(coords,c.contour,2,1,{dash:contourStyles[k].dash,percent:contourStyles[k].percent});}
   if(state.impactRoutes){const r=routes();for(const s of r.samples)for(const phase of ['up','down'])line(s[phase],c[phase],.8,state.impactBase==='photo'?.14:.12,{sample:true,phase});for(const phase of ['up','down']){line(r.mean[phase],c.halo,6,.9,{mean:true,phase});line(r.mean[phase],c[phase],2.8,1,{mean:true,phase});}}
   for(const p of displayPoints)scene.push({kind:'site',coords:[geo(p.x,p.y)],selected:p===selected,point:p,color:p===selected?c.point:'#2a5568',radius:p===selected?6:4});scene.push({kind:'mean',coords:[geo(...selected.e.mean)],color:c.contour,radius:5});return scene;
  }
  function draw(){if(!map._loaded||!current)return;layer.clearLayers();buildScene();for(const f of scene){if(f.kind==='line'||f.kind==='polygon'){const style={color:f.color,weight:f.weight,opacity:f.opacity,dashArray:f.dash,interactive:false,lineCap:'round',fillColor:f.fill,fillOpacity:f.fillOpacity};(f.kind==='polygon'?L.polygon(f.coords,style):L.polyline(f.coords,style)).addTo(layer);}else if(f.kind==='site'){const p=f.point,loc=F.geo(p.x,p.y);L.marker(f.coords[0],{icon:L.divIcon({className:'impact-site-hit',html:`<span style="background:${f.color};width:${f.radius*2}px;height:${f.radius*2}px"></span>`,iconSize:[30,30],iconAnchor:[15,15]}),title:`${loc.lat.toFixed(4)}°N ${loc.lon.toFixed(4)}°Eを放球点に選ぶ`,keyboard:true}).addTo(layer).on('click',e=>{L.DomEvent.stopPropagation(e);selectPoint(p.x,p.y);});}else L.circleMarker(f.coords[0],{radius:f.radius,color:f.color,weight:2,fillColor:'white',fillOpacity:1,interactive:false}).addTo(layer);}
   const count=current.data.records.length,c=palette(),swatch=(color,dash)=>`<svg class="impact-line-key" viewBox="0 0 30 10" aria-hidden="true"><path d="M1 5H29" stroke="${c.halo}" stroke-width="4"/><path d="M1 5H29" stroke="${color}" stroke-width="2" ${dash?`stroke-dasharray="${dash}"`:''}/></svg>`;
   $('impact-line-legend').innerHTML=`<span>着地域 ${contourStyles.map(s=>`<span class="impact-key" title="${s.percent}% ${s.name}">${swatch(c.contour,s.dash)}${s.percent}%</span>`).join(' ')}</span>`+(state.impactRoutes?`<span><span class="impact-key">${swatch(c.up)}上昇</span> <span class="impact-key">${swatch(c.down)}下降</span> · 細線: 全${count}標本 / 太線: 平均</span>`:'<span>矢印: 放球点→平均到達点</span>');
   $('impact-route-note').textContent=state.impactRoutes?'全標本の経路を間引かず表示しています。人工の凍結気柱・処方高度による経路で、施設通過の判定は未実装です。':'矢印は平均到達点への直線で、飛翔経路ではありません。施設周辺の経路群を見るには「選択地点の標本軌道」を表示します。';$('impact-route-note').textContent+=' 着地域は50%実線 / 90%破線 / 95%点線。飛行中の包含域ではありません。';
  }
  function fit(){if(!current)return;const points=current.displayPoints.flatMap(p=>[geo(p.x,p.y),...p.cloud.map(q=>geo(...q))]);if(state.impactRoutes)points.push(...routes().samples.flatMap(s=>[...s.up,...s.down]));map.invalidateSize({pan:false});map.fitBounds(points,{padding:[35,35],animate:false});}
  function render(value){const held=map._loaded?view():null;current=value;const elementSize=$(element).getBoundingClientRect(),knownSize=map.getSize();if(Math.round(elementSize.width)!==knownSize.x||Math.round(elementSize.height)!==knownSize.y)map.invalidateSize({pan:false});if(first){first=false;if(state.impactView)map.setView(state.impactView.center,state.impactView.zoom,{animate:false});else fit();}else if(held)map.setView(held.center,held.zoom,{animate:false,reset:true});draw();}
  function exportSVG(){if(!current)throw new Error('地図がまだありません');buildScene();const size=map.getSize(),W=size.x,H=size.y,P=coord=>{const p=map.latLngToContainerPoint(coord);return`${p.x.toFixed(2)},${p.y.toFixed(2)}`;};let body=`<defs><clipPath id="impact-clip"><rect width="${W}" height="${H}"/></clipPath></defs><rect width="${W}" height="${H}" fill="#eaf1f0"/><g clip-path="url(#impact-clip)">`;
   for(const tile of Object.values(tileLayer._tiles)){if(!tile.current)continue;const p=map.latLngToContainerPoint(map.unproject([tile.coords.x*256,tile.coords.y*256],tile.coords.z)),q=map.latLngToContainerPoint(map.unproject([(tile.coords.x+1)*256,(tile.coords.y+1)*256],tile.coords.z));body+=`<image href="${esc(tile.el.src)}" x="${p.x}" y="${p.y}" width="${q.x-p.x+.1}" height="${q.y-p.y+.1}"/>`;}
   for(const f of scene){if(f.kind==='line'||f.kind==='polygon')body+=`<${f.kind==='polygon'?'polygon':'polyline'} points="${f.coords.map(P).join(' ')}" fill="${f.kind==='polygon'?f.fill:'none'}" fill-opacity="${f.fillOpacity||0}" stroke="${f.color}" stroke-width="${f.weight}" stroke-opacity="${f.opacity}" stroke-linecap="round" ${f.dash?`stroke-dasharray="${f.dash}"`:''}/>`;else{const [x,y]=P(f.coords[0]).split(',');body+=`<circle cx="${x}" cy="${y}" r="${f.radius}" fill="${f.kind==='mean'?'white':f.color}" stroke="${f.kind==='mean'?f.color:'white'}" stroke-width="2"/>`;}}
   body+='</g>';const c=palette(),keyLine=(x,y,color,dash)=>`<path d="M${x} ${y}h30" stroke="${c.halo}" stroke-width="4"/><path d="M${x} ${y}h30" stroke="${color}" stroke-width="2" ${dash?`stroke-dasharray="${dash}"`:''}/>`;let x=12;for(const s of contourStyles){body+=keyLine(x,H+15,c.contour,s.dash)+`<text x="${x+35}" y="${H+19}" font-size="11">${s.percent}% ${s.name}</text>`;x+=107;}if(state.impactRoutes){body+=keyLine(12,H+36,c.up)+`<text x="47" y="${H+40}" font-size="11">上昇</text>`+keyLine(81,H+36,c.down)+`<text x="116" y="${H+40}" font-size="11">下降 · 細線: 全${current.data.records.length}標本 / 太線: 平均</text>`;}else body+=`<text x="12" y="${H+40}" font-size="11">矢印: 放球点→平均到達点</text>`;body+=`<text data-impact-background="true" x="12" y="${H+59}" font-size="11">背景表示の取得時状態: ${esc(backgroundStatus)}</text>`;const legend=$('impact-legend').querySelector('svg');if(legend)body+=`<g transform="translate(12 ${H+69})">${legend.innerHTML}</g>`;return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H+125}" aria-label="${esc(current.period+'・選択地点の落下域と飛行条件')}" data-impact-export="true">${body}</svg>`;
  }
  setBase();return{destroy(){disposed=true;tileGeneration++;tileLayer?.off();map.remove();},map,render,fit,togglePick,setBase,exportSVG,creditText,get scene(){return scene},get routeCache(){return routeCache},get tileState(){return{good,bad,loading:!!tileLayer?.isLoading(),status:backgroundStatus}},get contourStyles(){return contourStyles.map(s=>({...s}))}};
 }
 return{create};
})();

}
