import {levelEdges,type WindViewModel,type GeoBounds,type WindValue} from './viewModel';
export const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const fmt=(x:unknown,n=1)=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(n):'—';
export const text=(x:number,y:number,s:unknown,size=10,extra='')=>`<text x="${x}" y="${y}" font-size="${size}" ${extra}>${esc(s)}</text>`;
export const line=(x1:number,y1:number,x2:number,y2:number,color='#c5d5d9',width=1,extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${extra}/>`;
export const svg=(w:number,h:number,b:string,label:string,extra='')=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" font-family="system-ui,Yu Gothic,sans-serif" role="img" aria-label="${esc(label)}" ${extra}>${b}</svg>`;
export const blue=(v:number,max:number)=>{const f=Math.max(0,Math.min(1,v/max));return `rgb(${Math.round(233-220*f)},${Math.round(246-159*f)},${Math.round(250-112*f)})`;};
export function colorbar(max:number,label:string,w=195,h=45,opacity=1){let b=text(0,10,label,10)+`<rect x="0" y="16" width="${w}" height="8" fill="white"/>`;for(let i=0;i<80;i++)b+=`<rect x="${i*w/80}" y="16" width="${w/80+.2}" height="8" fill="${blue(i/79*max,max)}" fill-opacity="${opacity}"/>`;for(let i=0;i<=4;i++)b+=text(i*w/4,37,fmt(max*i/4,max===1?2:(max*i/4)%1?2:0),9,`text-anchor="${i===0?'start':i===4?'end':'middle'}"`);return svg(w,h,b,label,`data-colorbar="${esc(label)}" data-scale-min="0" data-scale-max="${max}" data-colorbar-opacity="${opacity}"`);}
export function annualPlots(vm:WindViewModel,direction:any){const total=vm.annualPeriods.length,edges=levelEdges(vm.levels),metrics:[keyof WindValue,string,string,number][]=[['s','風速の平均','14',vm.annualSpeedMax],['dir','平均風向（来向）','14',360],['R','風向の定常度','16',1],['spatialRange','地点間の平均風速の幅','19',vm.annualRangeMax]];
 return metrics.map(([key,label,fig,max])=>{const W=1000,H=key==='dir'?332:275,x0=53,y0=20,pw=860,ph=188,zMax=Math.max(...vm.levels.map(l=>l.height)),Y=(z:number)=>y0+ph*(1-z/zMax);let b='';vm.annualPeriods.forEach((p,i)=>vm.levels.forEach((l,j)=>{const q=vm.annual[i][j],v=q?.[key],d=key==='dir'?direction.appearance(q):null,color=d?d.fill:typeof v!=='number'||!Number.isFinite(v)?'#e9eeee':blue(v,max),valueText=d?d.label:fmt(v)+(key==='R'?'':' m/s'),edge=edges[j],x=x0+i*pw/total,y=Y(edge.hi),w=pw/total+.1,h=Y(edge.lo)-y;b+=`<rect data-period="${p.id}" data-level="${l.id}" data-height-low="${edge.lo}" data-height-high="${edge.hi}" ${d?`data-direction-state="${d.kind}"`:''} x="${x}" y="${y}" width="${w}" height="${h}" fill="${color}"><title>${esc(`${p.label} / ${p.description} / ${l.pressure} hPa / ${l.heightDescription}: ${valueText} / 各格子${p.timeCount}気象時刻・対象${vm.cells.length}格子`)}</title></rect>`;if(d?.kind==='undefined'||(key==='R'&&q?.R===null))b+=line(x+w*.35,y+h*.5,x+w*.65,y+h*.5,'#61777c',.8,'pointer-events="none"');}));
 for(let m=0;m<(total===4?4:12);m++)b+=line(x0+m*pw/(total===4?4:12),y0,x0+m*pw/(total===4?4:12),y0+ph,'#fff',.6)+text(x0+(m+.5)*pw/(total===4?4:12),y0+ph+17,total===4?vm.annualPeriods[m].label:`${m+1}月`,11,'text-anchor="middle"');for(let z=0;z<=zMax;z+=5)b+=line(x0,Y(z),x0+pw,Y(z),'#fff',.5)+text(x0-7,Y(z)+3,z,10,'text-anchor="end"');b+=text(x0-7,Y(zMax)+3,fmt(zMax),10,'text-anchor="end"');const ticks=vm.kind==='fixture'?[0,4,8,10,12,14,15]:vm.levels.map((_,i)=>i).filter(i=>i===0||i===vm.levels.length-1||[700,500,300,100,30,10].includes(vm.levels[i].pressure));for(const i of ticks)b+=text(922,Y(vm.levels[i].height)+3,vm.levels[i].pressure,10);b+=text(3,11,vm.kind==='climate'?'ISA km':'概算km',10)+text(920,11,'hPa',10);
 if(key==='dir')b+=direction.legend();else b+=`<g transform="translate(55 226)">${colorbar(max,key==='s'?'平均風速 [m/s]':key==='R'?'定常度 R':'地点別の期間平均風速 max−min [m/s]',270).replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`+text(390,255,vm.kind==='climate'?`UTC${total===48?'月内4区分':total===24?'半月':total===12?'月':'季節'}・固定ISA高度軸 ／ Rの—は無風時の未定義`:`月内${total===48?4:2}区分・端数日は暦年で配分 ／ 概算高度は線形軸`,10);
 return `<article class="plot-card" data-figure="${fig}"><h3>${label}<span>原図${fig}</span></h3><div class="annual-scroll">${svg(W,H,b,label,`data-annual="true" data-period-count="${total}" data-height-axis="${vm.kind==='climate'?'linear-isa-km':'linear-approx-km'}"`)}</div></article>`;}).join('');}
let geoId=0;
const world=(lat:number,lon:number)=>[(lon+180)/360,(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2];
export function geographyFrame(w:number,h:number,bounds:GeoBounds,background:boolean){const a=world(bounds.north,bounds.west),z=world(bounds.south,bounds.east),pad=5,k=Math.min((w-pad*2)/(z[0]-a[0]),(h-pad*2)/(z[1]-a[1]));if(!Number.isFinite(k)||k<=0)throw new Error('地図の表示範囲が不正です。');const ox=(w-(z[0]-a[0])*k)/2,oy=(h-(z[1]-a[1])*k)/2,project=(lat:number,lon:number)=>{const q=world(lat,lon);return [ox+(q[0]-a[0])*k,oy+(q[1]-a[1])*k];};let b=`<rect width="${w}" height="${h}" fill="#e8f2f5"/>`,clip='geo-'+geoId++;b+=`<defs><clipPath id="${clip}"><rect x="0" y="0" width="${w}" height="${h}"/></clipPath></defs><g clip-path="url(#${clip})">`;const zoom=Math.max(5,Math.min(12,Math.ceil(Math.log2(k/256)))),n=2**zoom,ts=1/n;for(let x=Math.floor(a[0]*n);x<=Math.floor(z[0]*n);x++)for(let y=Math.floor(a[1]*n);y<=Math.floor(z[1]*n);y++)b+=`<image data-basemap="gsi-std" data-tile="${zoom}/${x}/${y}" x="${ox+(x/n-a[0])*k}" y="${oy+(y/n-a[1])*k}" width="${ts*k+.1}" height="${ts*k+.1}" href="${background?`https://cyberjapandata.gsi.go.jp/xyz/std/${zoom}/${x}/${y}.png`:''}"/>`;return {b:b+'</g>',project};}
export function boundaryMarkup(project:(lat:number,lon:number)=>number[],bounds:GeoBounds){const a=project(bounds.north,bounds.west),z=project(bounds.south,bounds.east);return `<rect data-acquisition-boundary="true" x="${a[0]}" y="${a[1]}" width="${z[0]-a[0]}" height="${z[1]-a[1]}" fill="none" stroke="#1b495c" stroke-width="1.5" stroke-dasharray="5 3"/>`;}
export function arrow(x:number,y:number,u:number,v:number,size=10,color='#193e51',stroke=1.4){const n=Math.hypot(u,v);if(n<1e-6)return '';const dx=u/n*size,dy=-v/n*size,ex=x+dx,ey=y+dy;return line(x-dx*.35,y-dy*.35,ex,ey,color,stroke)+`<path d="M${ex-dx*.35-dy*.28},${ey-dy*.35+dx*.28} L${ex},${ey} L${ex-dx*.35+dy*.28},${ey-dy*.35-dx*.28}" fill="none" stroke="${color}" stroke-width="${stroke}"/>`;}
export function glyphCells(vm:WindViewModel){const lat=[...new Set(vm.cells.map(c=>c.lat))].sort((a,b)=>a-b),lon=[...new Set(vm.cells.map(c=>c.lon))].sort((a,b)=>a-b),sx=Math.max(1,Math.ceil(lon.length/10)),sy=Math.max(1,Math.ceil(lat.length/7));return new Set(vm.cells.filter(c=>lon.indexOf(c.lon)%sx===0&&lat.indexOf(c.lat)%sy===0).map(c=>c.id));}
export function spatialPlot(vm:WindViewModel,index:number,mode:'wind'|'steady',scale:'all'|'level',background:boolean){const W=190,H=175,g=geographyFrame(W,154,vm.mapBounds,background),upper=scale==='all'?vm.spatialAllMax:vm.spatialLevelMax,filter='muted-'+geoId++,level=vm.levels[vm.levelIndex],period=vm.spatialPeriods[index],glyphs=glyphCells(vm);let b=`<defs><filter id="${filter}" color-interpolation-filters="sRGB"><feColorMatrix type="saturate" values="0"/><feComponentTransfer><feFuncR type="linear" slope=".7" intercept=".3"/><feFuncG type="linear" slope=".7" intercept=".3"/><feFuncB type="linear" slope=".7" intercept=".3"/></feComponentTransfer></filter></defs><g data-muted-basemap="true" filter="url(#${filter})">${g.b}</g>`;vm.cells.forEach((c,j)=>{const q=vm.spatial[index][j],a=g.project(c.north,c.west),z=g.project(c.south,c.east),v=mode==='wind'?q?.s:q?.R;b+=`<rect data-grid="${c.id}" x="${a[0]}" y="${a[1]}" width="${z[0]-a[0]}" height="${z[1]-a[1]}" fill="${typeof v==='number'?blue(v,mode==='wind'?upper:1):'#e9eeee'}" fill-opacity=".78"><title>${esc(`${c.label} / ${period.label} / ${period.description} / ${level.pressure} hPa：平均風速 ${fmt(q?.s)} m/s / 格子の時間定常度 R=${fmt(q?.R,2)} / ${period.timeCount}時刻`)}</title></rect>`;const [x,y]=g.project(c.lat,c.lon);if(q&&glyphs.has(c.id))b+=mode==='wind'?`<g data-wind-glyph="true" data-cell-id="${c.id}">${arrow(x,y,q.u,q.v,10,'white',4.2)}${arrow(x,y,q.u,q.v,10,q.R!==null&&q.R<.3?'#777':'#123044',1.7)}</g>`:`<circle cx="${x}" cy="${y}" r="${vm.kind==='fixture'?2:1}" fill="#285360"/>`;});b+=boundaryMarkup(g.project,vm.selectionBounds)+text(5,169,`${background?'地理院（淡色加工）':'背景未接続'} n=${period.timeCount}時刻`,10);return svg(W,H,b,period.label+'の地域図',`data-map="true" data-period="${period.id}" data-color-max="${mode==='wind'?upper:1}"`);}
export function spatialDefinition(vm:WindViewModel,mode:'wind'|'steady',scale:'all'|'level'){return (mode==='wind'?`色＝各元格子の平均スカラー風速。等長矢印＝平均ベクトルの移流先（来向とは逆）。R<0.3は灰。${scale==='all'?'全高度':'この高度'}・全期間共通 0–${scale==='all'?vm.spatialAllMax:vm.spatialLevelMax} m/s。`:'色＝各格子の時間定常度R（0–1）。—は全無風時の未定義。向きの相殺と風の弱さは別です。')+` 色${vm.cells.length}格子 / ${mode==='wind'?'矢印':'中心点'}表示${glyphCells(vm).size}地点。色は78%重ね、厳密値は格子に重ねて確認。${vm.spatialDefinition}`;}
