import {HistoricalEntry} from './HistoricalEntry';
import {projectForAnalysis,readHistoricalInterest,mergeHistoricalView} from './historicalWorkspace';
import {Component,useEffect,useRef,useState} from 'react';
import {useWorkspace} from './useWorkspace';
import {useEnsembleWorkspace} from './useEnsembleWorkspace';
import {ForecastScreen} from './screens/ForecastScreen';
import {WeatherScreen} from './screens/WeatherScreen';
import {stableString,jstInputToUtc} from './domain';
import {applyCandidateWeather,type ModelDrafts} from './modelDrafts';
import type {Candidate,Project} from './domain';
import './platform.css';

class ScreenBoundary extends Component<{children:any},{error:string}>{state={error:''};static getDerivedStateFromError(error:unknown){return {error:error instanceof Error?error.message:String(error)};}render(){return this.state.error?<div className="platform-error" role="alert"><b>画面処理を停止しました。</b><p>{this.state.error}</p><p>入力と固定結果は共通の計画に保持しています。上部から別の用途へ移動するか、保存した計画を読み直してください。</p></div>:this.props.children;}}

type Place='forecast_real'|'forecast_fixture'|'weather_fixture'|'weather_real'|'season_fixture'|'season_real';
export function App(){
 const ws=useWorkspace(),ref=useRef(ws);ref.current=ws;
 const [place,setPlace]=useState<Place>('forecast_real'),[library,setLibrary]=useState(false);
 const ui=ws.project.ui_state??{};
 function update(project:Project){ref.current.setProject(project);ref.current={...ref.current,project};}
 const ensemble=useEnsembleWorkspace(ws.project,ws.runs,ws.restoration,ws.loading,update,{claim:ws.claimSelection,current:ws.selectionToken});
 function keepView(key:Place,value:any){const current=ref.current.project;const nextView=key==='season_real'?mergeHistoricalView(current.ui_state?.[key],value):{...current.ui_state?.[key],...value};if(stableString(current.ui_state?.[key])===stableString(nextView))return;update({...current,ui_state:{...current.ui_state,schema:'balloon.ui/1',[key]:nextView}});}
 useEffect(()=>{if(ws.loading)return;const current=ref.current.project,view=current.ui_state?.forecast_real??{},codes={...view.codes};let changed=false;for(const c of current.candidates)if(!codes[c.id]){codes[c.id]='候補'+(Object.keys(codes).length+1);changed=true;}if(changed){const alias=(id:string)=>codes[id]??id;keepView('forecast_real',{codes,active:alias(view.active),groups:(view.groups??[]).map((g:any)=>({...g,members:g.members.map(alias)})),colors:Object.fromEntries(Object.entries(view.colors??{}).map(([id,v])=>[alias(id),v])),visibility:Object.fromEntries(Object.entries(view.visibility??{}).map(([id,v])=>[alias(id),v]))});}},[ws.loading,ws.restoration,ws.project.candidates]);
 function resolved(children:Candidate[],parent:Candidate){return children.map(c=>c.parent_id===parent.id?{...c,revision:c.revision+1,weather_source_id:parent.weather_source_id,sampling:structuredClone(parent.sampling??null),config:{...structuredClone(parent.config),launch:{...parent.config.launch,time_utc:new Date(Date.parse(parent.config.launch.time_utc)+(c.delay_minutes??0)*60000).toISOString()}}}:c);}
 function change(candidate:Candidate,models?:ModelDrafts){const current=ref.current.project;const viewKey=candidate.analysis_mode==='historical_windows'?'season_real':'forecast_real',view=current.ui_state?.[viewKey]??{};update({...current,candidates:resolved(current.candidates.map(c=>c.id===candidate.id?candidate:c),candidate),...(models?{ui_state:{...current.ui_state,[viewKey]:{...view,editor_models:{...view.editor_models,[candidate.id]:models}}}}:{})});}
 function newId(_candidates:Candidate[]){return 'C-'+crypto.randomUUID();}
 function action(type:string,data:any){
  const current=ref.current.project,c=current.candidates.find(x=>x.id===data.id);
  if(type==='save'){void ref.current.save();return;}
  if(type==='weather-return'){if(data.source?.returnState)keepView('weather_fixture',data.source.returnState);setPlace('weather_fixture');return;}
  if(type==='library'){setLibrary(true);return;}
  if(type==='config'){change(data.candidate,data.models);return;}
  if(type==='weather-apply'){update(applyCandidateWeather(current,data.ids,data.sourceId));return;}
  if(type==='run'){if(c?.sampling){void ensemble.prepare(c);return;}if(c)void ref.current.startFamily([c,...current.candidates.filter(x=>x.parent_id===c.id)]);return;}
  if(type==='rename'&&c){change({...c,label:data.name,revision:c.revision+1});return;}
  if(type==='edit'&&c){const config=structuredClone(c.config);if(data.key==='origin'){config.launch.latitude_deg=data.value[0];config.launch.longitude_deg=data.value[1];}change({...c,config,revision:c.revision+1});return;}
  if(type==='add'||type==='duplicate'){
   const source=data.source??ref.current.sources.find(s=>s.id===c?.weather_source_id)??ref.current.sources[0];if(!source){ref.current.setMessage('保存気象を読み込んでから候補を追加してください。');return;}
   const id=newId(current.candidates),config=structuredClone(c?.config??source.default_config);if(config)delete config.label;
   if(!config){ref.current.setMessage('新しい取得場は既存候補へ適用してください。放球・モデル条件を自動で作りません。');return;}
   const next:Candidate={id,label:c?c.label+' の比較案':'新しい候補',revision:1,weather_source_id:source.id,config,sampling:place==='season_real'?null:structuredClone(c?.sampling??null),...(place==='season_real'?{analysis_mode:'historical_windows' as const,parent_id:null,delay_minutes:null}:{})};
   const viewKey=place==='season_real'?'season_real':'forecast_real',view=current.ui_state?.[viewKey]??{},forecast=current.ui_state?.forecast_real??{},code='候補'+(Object.keys(forecast.codes??{}).length+1);
   const sourceDraft=c&&view.historicalPlans?.[c.id]?.draft;
   const nextView={...view,editor_models:{...view.editor_models,[id]:structuredClone(view.editor_models?.[c?.parent_id??c?.id??'']??{})},...(viewKey==='season_real'&&sourceDraft?{historicalPlans:{...view.historicalPlans,[id]:{draft:structuredClone(sourceDraft)}}}:{}),active:code,detail:false};
   update({...current,candidates:[...current.candidates,next],ui_state:{...current.ui_state,forecast_real:{...forecast,...(viewKey==='forecast_real'?nextView:{}),codes:{...forecast.codes,[id]:code}},...(viewKey==='season_real'?{historicalCandidateIds:[...new Set([...(current.ui_state?.historicalCandidateIds??[]),id])],season_real:nextView}:{})}});return;
  }
  if(type==='detach'&&c){change({...c,parent_id:null,delay_minutes:null,revision:c.revision+1},structuredClone(current.ui_state?.forecast_real?.editor_models?.[c.parent_id??'']??{}));return;}
  if(type==='delays'&&c&&c.analysis_mode!=='historical_windows'){
   const delays:number[]=data.delays;let candidates=current.candidates.filter(x=>x.parent_id!==c.id||delays.includes(x.delay_minutes??-1));
   for(const delay of delays)if(!candidates.some(x=>x.parent_id===c.id&&x.delay_minutes===delay)){const id=newId(candidates);candidates.push({...structuredClone(c),id,label:c.label+' ＋'+delay+'分',revision:1,parent_id:c.id,delay_minutes:delay});}
   candidates=resolved(candidates,c);
   const ids=new Set(candidates.map(x=>x.id));const view=current.ui_state?.forecast_real??{};const codes={...view.codes};for(const child of candidates)if(!codes[child.id])codes[child.id]='候補'+(Object.keys(codes).length+1);const aliases=new Set(candidates.map(x=>codes[x.id]??x.id));
   update({...current,candidates,compare_run_ids:current.compare_run_ids,ui_state:{...current.ui_state,forecast_real:{...view,codes,groups:(view.groups??[]).map((g:any)=>({...g,members:g.members.filter((id:string)=>aliases.has(id))}))}}});
   ref.current.setMessage('延期候補の草案を作りました。親の「この条件で計算」で親と延期列を実行します。旧結果は保持しています。');return;
  }
  if(type==='remove'){
   const removed=new Set(data.ids),candidates=current.candidates.filter(x=>!removed.has(x.id)&&!removed.has(x.parent_id)),codes=current.ui_state?.forecast_real?.codes??{};
   const cleaned=(key:'forecast_real'|'season_real')=>{const view=current.ui_state?.[key]??{},own=candidates.filter(x=>(x.analysis_mode==='historical_windows')===(key==='season_real')),aliases=new Set(own.map(x=>codes[x.id]??x.id));return {...view,active:aliases.has(view.active)?view.active:(codes[own[0]?.id]??own[0]?.id??''),detail:false,groups:(view.groups??[]).map((g:any)=>({...g,members:g.members.filter((id:string)=>aliases.has(id))})).filter((g:any)=>g.members.length>0)};};
   update({...current,candidates,ui_state:{...current.ui_state,forecast_real:cleaned('forecast_real'),season_real:cleaned('season_real')}});return;
  }
  if(type==='revert'&&c){const run=ref.current.runs.find(r=>r.candidate_id===c.id&&current.compare_run_ids.includes(r.run_id)),result=run&&ref.current.results[run.run_id];if(result)change({...c,revision:c.revision+1,config:structuredClone(run.spec?.submitted_input.config??result.result.config),weather_source_id:run.spec?.submitted_input.weather_source_id??run.weather_source_id??c.weather_source_id});}
 }
 const historical=place==='season_real',real=place==='forecast_real'||historical;
 const resultPlace=(id:string):Place=>ws.project.candidates.some(c=>c.id===id&&c.analysis_mode==='historical_windows')||(ui.historicalCandidateIds??[]).includes(id)?'season_real':'forecast_real';
 const screenProject=real?projectForAnalysis(ws.project,ws.runs,historical):ws.project,screenView=historical?{...ui.season_real,codes:ui.forecast_real?.codes}:ui[place];
 return <><header className="platform-header"><div><b>BALLOON LAB</b><span>{place.startsWith('weather')?'気象の性質':place.startsWith('season')?'季節の打上げ計画':'打上げ計画'} <small>0.58.0 開発版</small></span></div><nav><button className={place.startsWith('forecast')?'active':''} onClick={()=>setPlace('forecast_real')}>打上げ計画</button><button className={place.startsWith('weather')?'active':''} onClick={()=>setPlace('weather_real')}>気象を分析</button><button className={place.startsWith('season')?'active':''} onClick={()=>setPlace('season_real')}>季節計画</button><button onClick={()=>setLibrary(true)}>保存結果を開く</button><button disabled={ws.loading||ws.saving} onClick={()=>void ws.save()}>{ws.saving?'保存中…':ws.dirty?'計画を保存 ●':'計画を保存'}</button></nav></header>
 <div className="platform-status"><label>表示するデータ <select value={place.endsWith('_real')?'real':'fixture'} onChange={e=>setPlace(place.startsWith('season')?(e.target.value==='real'?'season_real':'season_fixture'):place.startsWith('weather')?(e.target.value==='real'?'weather_real':'weather_fixture'):(e.target.value==='real'?'forecast_real':'forecast_fixture'))}><option value="real">{place.startsWith('weather')?'保存した実気象集計':'保存気象・実計算'}</option><option value="fixture">画面確認用の人工データ</option></select></label><span role="status">{ws.loading?'保存状態を読込中':ws.saving?'保存中':ws.dirty?'未保存の変更あり':'保存済み'}</span>{ws.message&&<details><summary>処理の通知</summary>{ws.message}</details>}</div>
 {ws.error&&<div className="platform-error" role="alert">{ws.error}<button onClick={()=>void ws.load()}>保存済みの計画を読み直す（未保存の編集を置換）</button></div>}
 {ws.healthError&&<div className="platform-error" role="status">サービスの状態を確認できません：{ws.healthError}。保存した計算を失敗扱いにせず、最後に確認した結果を保持しています。<button onClick={()=>void ws.refreshHealth()}>サービスの状態を再確認</button></div>}
 {ws.serviceHealth?.flight_execution.available===false&&<div className="platform-error" role="alert"><b>飛行計算の処理系が停止しています。サービスの再起動が必要です。</b><p>保存結果は読めます。待機中の試行を自動で再送せず保持しています。再起動後に元の要求・台帳を確認して、未完了分の再開を明示的に選んでください。</p><p>{ws.serviceHealth.flight_execution.error?.message}</p><button onClick={()=>void ws.refreshHealth()}>処理系を再確認</button></div>}
 {ws.ledgerNotice&&<div className="platform-run-status" role="status">{ws.ledgerNotice}</div>}
 {!ws.loading&&ws.writeLease.state!=='owner'&&<section className="platform-run-status"><b>このタブは閲覧用です</b><p role="status">{ws.writeLease.message}</p><button disabled={ws.writeLease.state==='requesting'} onClick={()=>void ws.claimWriteLease()}>{ws.writeLease.state==='requesting'?'送信担当を確認中…':'このタブで送信権を取得'}</button></section>}
 {Object.entries(ws.readErrors).map(([kind,error])=><div className="platform-error" key={kind} role="status">{{weather:'気象一覧',runs:'計算履歴',project:'保存計画'}[kind]}を読めません：{error}。確認できた内容は保持しています。<button onClick={()=>void ws.retryRead(kind)}>この読取りを再確認{kind==='project'?'（保存した草案を復元）':''}</button></div>)}
 {ws.saveIntent&&<section className="platform-run-status"><b>保存受付が未確認の計画</b><p>送信時点の草案をブラウザに保持しています。現在の編集とは別です。</p><button disabled={ws.saving||ws.writeLease.state!=='owner'} onClick={()=>void ws.confirmSave()}>保存先と照合して記録</button>{ws.writeLease.state!=='owner'&&<small>照合はサーバーを読取り、未確認要求の記録を更新します。送信権を取得したタブで確定してください。</small>}<button onClick={ws.restoreSubmissionDraft}>未確認保存の草案を開く</button>{ws.saveIntent.payload.notApplied&&<button disabled={ws.saving} onClick={()=>void ws.retrySave()}>同じ固定内容で保存を再送</button>}{ws.saveIntent.payload.confirmedProject&&!ws.saveIntent.payload.notApplied&&<details><summary>保存先との相違を確認</summary><p>保存先の版 {ws.saveIntent.payload.confirmedRevision} と送信前の版 {ws.saveIntent.payload.revision} が異なります。下記を比較してから、現在の草案を再保存する基準を明示的に選んでください。</p><pre>{JSON.stringify(ws.saveIntent.payload.confirmedProject,null,2)}</pre><button disabled={ws.saving||ws.writeLease.state!=='owner'} onClick={ws.resolveSaveConflict}>確認した保存先の版を基準にして草案を保持</button></details>}</section>}
 {ws.families.map(f=><section className="platform-run-status" key={f.id}><b>固定した単便・延期列 · {f.payload.rows.length}件</b><p>{f.payload.paused?'受付の確認または続行操作を待っています。自動再送しません。':'一件ずつ計算しています。後続は固定した入力を使用します。'}</p><details><summary>対象と受付状況</summary>{f.payload.rows.map(r=><p key={r.requestId}>{r.candidate.label} · {{unsubmitted:'未送信',unknown:'受付未確認',accepted:'受付済み',finished:'終了',rejected:'受付拒否',cancelled:'未送信を取消'}[r.state]}{r.notFound?'（この確認時点で未受付）':''} {r.message??''}</p>)}</details><button onClick={()=>void ws.confirmFamily(f.id)}>受付を確認（読取りのみ）</button><button disabled={f.payload.rows.some(r=>r.state==='unknown'&&!r.notFound)} onClick={()=>void ws.resumeFamily(f.id)}>同じ固定条件で未完了分を続ける</button><button onClick={()=>ws.discardUnsent(f.id)}>まだ送信していない分を取り消す</button></section>)}
 {ensemble.pendingMutations.length>0&&<section className="platform-run-status"><b>集合に関する受付未確認の要求</b><p>保存した本文と同じ受付IDで確認・再送します。新しい入力や新しい標本へ置き換えません。</p>{ensemble.pendingMutations.map(entry=><p key={entry.id}>{entry.payload.path==='/ensemble-plans'?'標本計画':entry.payload.path==='/ensemble-analyses'?'固定結果の群分析':entry.payload.path.endsWith('/cancel')?'残る試行の取消':entry.payload.path.endsWith('/retry')?'未完了分の再開':'集合の開始'} · {entry.createdAt} <button disabled={!!ensemble.recoveryBusy} onClick={()=>void ensemble.recoverMutation(entry.id)}>保存した同じ要求で受付を確認・再送</button></p>)}</section>}
 {Object.keys(ws.observations).length>0&&<details className="platform-run-status"><summary>単便計算の状態 · {Object.values(ws.observations).some(s=>s.unavailable)?'確認できない処理があります':Object.keys(ws.observations).length+'件'}</summary><p>状態の再確認はGETだけを行います。入力や表示結果の選択を戻したり、計算を再送したりしません。</p>{Object.entries(ws.observations).map(([id,o])=>{const r=ws.runs.find(r=>r.run_id===id);return <div key={id}><b>{r?.label??r?.candidate_id??id.slice(-8)}</b> · {o.unavailable?'最後に確認した状態：':''}{{queued:'待機',running:'計算中',completed:'計算終了',failed:'計算失敗',cancelled:'取消済み',interrupted:'中断'}[String(r?.state)]??r?.state}<p role="status">{o.unavailable?'現在の状態や結果を確認できません。計算の失敗を意味しません。':o.checking?'確認中…':''}{o.lastConfirmedAt&&' 最終確認 '+new Date(o.lastConfirmedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',hour12:false})+' JST'}{o.unavailable&&o.nextRetryMs!==null&&` · 最大${o.nextRetryMs/1000}秒後に再確認`}</p>{o.message&&<p>{o.message}</p>}{r?.error!=null&&<p>保存された処理結果：{typeof r.error==='object'?JSON.stringify(r.error):String(r.error)}</p>}<button disabled={o.checking} onClick={()=>void ws.refreshRun(id)}>状態と結果を再確認（再計算なし）</button></div>;})}</details>}
 <ScreenBoundary key={place+ws.restoration}>{ws.loading?<p role="status">保存された入力・画面・結果を読み込んでいます。</p>:place.startsWith('weather')?<WeatherScreen key={place+ws.restoration} mode={place==='weather_real'?'climate':'fixture'} saved={ui[place]} onView={v=>keepView(place,v)} background={true} handoff={p=>{if(p.kind==='historical-flight-interest'){keepView('season_real',{historicalInterest:p.selection_context,weatherReturnState:p.returnState});setPlace('season_real');}else{keepView('season_fixture',{pendingProposal:p});setPlace('season_fixture');}}}/>:<>{historical&&<HistoricalEntry sources={ws.sources} context={readHistoricalInterest(ui.season_real)} onCreate={source=>action('add',{source})} onReturn={()=>{if(ui.season_real?.weatherReturnState)keepView('weather_real',ui.season_real.weatherReturnState);setPlace('weather_real');}}/>}<ForecastScreen key={place+ws.restoration} workspace={{...ws,project:screenProject,ensemble}} historical={historical} mode={real?'real':place==='season_fixture'?'season':'fixture'} saved={screenView} proposal={null} onView={v=>keepView(place,v)} action={action}/></>}</ScreenBoundary>
 {library&&<dialog className="platform-library" open><h2>保存した計画と固定結果</h2><p>保存草案と表示する結果の組合せを共通の計画へ保存します。人工画面の状態は別の名前空間で保持します。</p><button onClick={()=>{setLibrary(false);void ws.load();}}>保存した計画を読み直す</button><button onClick={()=>setLibrary(false)}>閉じる</button>{Object.values(ensemble.jobs).flatMap(job=>(job.snapshots?.length?job.snapshots:job.latest_snapshot_id?[{snapshot_id:job.latest_snapshot_id,epoch:job.epoch}]:[]).flatMap(snapshot=>job.cases.map(c=><p key={snapshot.snapshot_id+c.case_id}>集合 {job.ensemble_id.slice(-10)} · 第{snapshot.epoch}回 · {ui.forecast_real?.codes?.[c.case_id]??'保存候補'} <button onClick={()=>{void ensemble.select(snapshot.snapshot_id,c.case_id);setPlace(resultPlace(c.case_id));setLibrary(false);}}>固定集合を表示</button></p>)))}{ws.runs.filter(r=>r.kind!=='ensemble_trial'&&r.result_available).map(r=><p key={r.run_id}><b>{r.label??r.candidate_id}</b> · 計算時の版{r.candidate_revision} <button onClick={()=>{void ws.selectResult(r.run_id,r.candidate_id!);setPlace(resultPlace(r.candidate_id!));setLibrary(false);}}>この固定結果を表示</button></p>)}</dialog>}
 </>;
}
