import {climateGrainLabel,climateHoursLabel,climatePeriodLabel,climateYearsLabel,selectedClimateHours,type ClimateArtifact,type ClimateGrain,type ClimateView} from './climateDomain';
import {climateGrains,climatePeriods} from './screens/weather/sources/climateSummary';
export function climateInterest(a:ClimateArtifact,view:ClimateView){
 const available=climateGrains(a),preferred=view.interest_grain??view.monthly_grain??'half',grain=available.includes(preferred)?preferred:'half',periods=climatePeriods(a,grain),period=periods.find(p=>p.timebin_id===view.interest_period_id)??periods[0],bounds=a.query.bounds??a.summary.source.bounds;
 return {schema:'balloon.climate-flight-interest/1',analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:a.summary.source.dataset_sha256,label:`${climatePeriodLabel(period)} · ${bounds.south}–${bounds.north}°N / ${bounds.west}–${bounds.east}°E · 気象有効時刻 ${climateHoursLabel(a.query)}（原放球時刻は別に選択）`,bounds,grain,period:structuredClone(period),hours_utc:[...selectedClimateHours(a.query)],years:[...a.summary.population.years_fixed],date_convention:a.summary.population.date_convention};
}
export function ClimateFlightHandoff({artifact,view,onView,handoff}:{artifact:ClimateArtifact|null;view:ClimateView;onView:(v:Partial<ClimateView>)=>void;handoff:(v:any)=>void}){
 if(!artifact)return <p>まず保存した気象集計を開くか、対象を再集計してください。図と同じ対象・出典を試算へ渡します。</p>;
 const context=climateInterest(artifact,view),periods=climatePeriods(artifact,context.grain),available=climateGrains(artifact);
 return <div className="climate-flight-handoff"><h3>気になる時期を、原日時の飛行で確かめる</h3><p>平均図・代表地点の風配は時期や場所を絞る材料です。飛行には別に、原日時の高度・時間方向に連続な気象場が必要です。</p><label>関心の時期区切り<select value={context.grain} onChange={e=>onView({interest_grain:e.target.value as ClimateGrain,interest_period_id:undefined})}>{available.map(g=><option key={g} value={g}>{climateGrainLabel[g]}</option>)}</select></label><label>まず試したい時期（UTC暦）<select value={context.period.timebin_id} onChange={e=>onView({interest_period_id:Number(e.target.value)})}>{periods.map(p=><option key={p.timebin_id} value={p.timebin_id}>{climatePeriodLabel(p)}</option>)}</select></label><p>{context.label}。集計は{climateYearsLabel(context.years)}です。次画面で試す原年・原放球日時と取得済み場を明示し、共通の機体で実計算します。</p><p>UTC期間・気象有効時刻の関心を引き継ぎます。JSTへの換算で期間の所属を変えず、気象有効時刻を放球時刻に置き換えません。</p><button className="primary" onClick={()=>handoff({kind:'historical-flight-interest',returnState:{...view,interest_grain:context.grain,interest_period_id:context.period.timebin_id},selection_context:context})}>この関心条件を原日時の試算へ渡す</button><p>期間平均から瞬時場を再生成しません。少数の明示日時による試算と、多年を代表する季節分散は区別します。</p></div>;
}
