import {nativeRosePointMap,nearestRosePoint} from './screens/weather/climateDistributions';
import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
import {climateViewModel,nativeDisplayCells} from './screens/weather/sources/climateSummary';
import {annualPlots,spatialPlot,glyphCells,geographyFrame} from './screens/weather/plots';
import {createWindExport} from './screens/weather/export';
import {aggregateFixture,fixtureViewModel} from './screens/weather/sources/fixtureSummary';
import {install as installFixture} from './screens/weather/fixture.js';
import {queryIssue,validateClimateArtifact,queryKey,normalizeClimateQuery,type ClimateArtifact,type ClimateDescriptor} from './climateDomain';
const {h,apiMock}=vi.hoisted(()=>({h:{current:null as any},apiMock:{sources:vi.fn(),get:vi.fn(),create:vi.fn()}}));
vi.mock('./climateApi',()=>({climateApi:apiMock}));
vi.mock('react',()=>({useRef:(value:any)=>h.current.ref(value),useState:(value:any)=>h.current.state(value),useEffect:(f:any,d:any[])=>h.current.effect(f,d),useMemo:(f:any,d:any[])=>h.current.memo(f,d)}));
vi.mock('react-dom',()=>({createPortal:(node:any)=>node}));
vi.mock('./screens/weather/runtime',()=>({mountWeather:()=>({preparationElement:{},flightElement:null,sync:()=>{},dispose:()=>{}})}));
import {WeatherScreen} from './screens/WeatherScreen';
import {useClimateWorkspace} from './useClimateWorkspace';
import {claimWriteLease,releaseWriteLease} from './writeLease';
import {setServiceIdentity} from './serviceIdentity';
function sample():ClimateArtifact {const cells=[{cell_id:99,lat:40,lon:140,gauss_weight:1},{cell_id:7,lat:40,lon:141,gauss_weight:1},{cell_id:52,lat:41,lon:140,gauss_weight:1},{cell_id:3,lat:41,lon:141,gauss_weight:1}],levels=[{level_id:8,level_hpa:3,isa_alt_m:40000,alt_geom_mean_m:41000,alt_geom_min_m:39000,alt_geom_max_m:43000},{level_id:2,level_hpa:1000,isa_alt_m:100,alt_geom_mean_m:150,alt_geom_min_m:50,alt_geom_max_m:250}],periods=Array.from({length:24},(_,i)=>({timebin_id:i,month:Math.floor(i/2)+1,bin:i%2+1,start_day:i%2?16:1,end_day_min:i%2?28:15,end_day_max:i===3?29:i%2?28:15,n_days_total:i===3?133:150,n_analyses_expected:i===3?532:600})),bounds={west:140,east:141,south:40,north:41},query={source_id:'src1',level_id:2,bounds,grain:'half' as const},source={source_id:'src1',dataset_sha256:'dbhash',bounds,native_grid:cells,native_grid_count:4,levels,timebins:periods,capabilities:{annual:true,spatial:true,years_fixed:[2016,2025],date_convention:'UTC',native_hours_utc:[0,6,12,18],grain:'half'},attribution:{license:'supplier-declared'}} as ClimateDescriptor;return {schema:'balloon.climate.analysis-artifact/1',analysis_id:'a1',query,query_hash:'qh1',result_hash:'rh1',created_at:'2026-09-30T00:00:00Z',summary:{schema:'climate-summary/1',source,query,levels,population:{timebins:periods,selected_cell_ids:cells.map(c=>c.cell_id),selected_cell_count:4,native_grid_count:4,years_fixed:[2016,2025],date_convention:'UTC',native_hours_utc:[0,6,12,18],spatial_weighting:'provided_gaussian_grid_weights',count_definition:'time_count per cell'},annual:periods.flatMap(p=>levels.map(l=>({timebin_id:p.timebin_id,level_id:l.level_id,mean_u:0,mean_v:0,mean_speed:10,pooled_constancy:0,from_deg:null,spatial_mean_speed_range:0,cell_count:4,time_count:p.n_analyses_expected,valid_time_count:p.n_analyses_expected,missing_time_count:0}))),spatial:{level_id:2,grid:cells,rows:periods.flatMap(p=>cells.map((c,i)=>({timebin_id:p.timebin_id,cell_id:c.cell_id,mean_u:i%2?10:-10,mean_v:0,mean_speed:10,constancy:1,from_deg:i%2?270:90,time_count:p.n_analyses_expected,valid_time_count:p.n_analyses_expected,missing_time_count:0})))},display_scales:{all_level_cell_mean_speed_max:73,selected_level_cell_mean_speed_max:10,annual_mean_speed_max:10,spatial_mean_speed_range_max:0},provenance:{query_hash:'qh1',result_hash:'rh1'}}};}
const direction={appearance:(q:any)=>q?.dir===null?{fill:'#eee',kind:'undefined',label:'平均来向なし'}:{fill:'blue',kind:'direction',label:'来向'},legend:()=>'<g data-direction-key="from-circular"/>'};
describe('fixed climate to existing plots',()=>{
 it('uses native IDs and ascending fixed ISA without fabricating raw observations',()=>{const vm=climateViewModel(sample());expect(vm.levels.map(l=>l.id)).toEqual([2,8]);expect(vm.levelIndex).toBe(0);expect(vm.annualPeriods).toHaveLength(24);expect(vm.annualPeriods[3].timeCount).toBe(532);expect(vm.annualPeriods[3].description).toContain('閏年29');expect(vm.annual[0][0]?.R).toBe(0);expect(vm.spatial[0][0]?.R).toBe(1);expect('records' in vm).toBe(false);expect(vm.spatialAllMax).toBe(75);});
 it('keeps same native color cell when selected region changes',()=>{const a=sample(),full=climateViewModel(a),b=structuredClone(a);b.summary.population.selected_cell_ids=[99];b.summary.population.selected_cell_count=1;b.summary.spatial.grid=b.summary.spatial.grid.filter(c=>c.cell_id===99);b.summary.spatial.rows=b.summary.spatial.rows.filter(c=>c.cell_id===99);b.summary.annual.forEach(r=>r.cell_count=1);b.summary.query.bounds={west:140,east:140,south:40,north:40};const subset=climateViewModel(b);expect(subset.cells).toEqual([full.cells[0]]);expect(subset.mapBounds.east).toBeGreaterThan(subset.mapBounds.west);expect(glyphCells(subset).size).toBe(1);});
 it('does not turn undefined direction/constancy into numeric zero or discard rows',()=>{const a=sample();a.summary.annual[0].pooled_constancy=null;a.summary.annual[0].mean_speed=0;a.summary.spatial.rows[0].constancy=null;const vm=climateViewModel(a);expect(vm.annual[0][1]?.R).toBeNull();expect(vm.spatial[0][0]?.R).toBeNull();const html=annualPlots(vm,direction);expect(html).toContain('data-direction-key="from-circular"');expect(html.match(/data-annual="true"/g)).toHaveLength(4);expect(html.match(/data-level=/g)).toHaveLength(24*2*4);expect(html).toContain('ISA km');expect(html).toContain('532気象時刻');const map=spatialPlot(vm,0,'steady','all',false);expect(map.match(/data-grid=/g)).toHaveLength(4);expect(map).toContain('R=—');expect(map).toContain('背景未接続');});
 it('rejects missing keys, nonfinite values and nonrectangular native grids',()=>{const a=sample();a.summary.spatial.rows.pop();expect(()=>climateViewModel(a)).toThrow('欠落');const b=sample();b.summary.annual[0].mean_u=NaN;expect(()=>climateViewModel(b)).toThrow('有限');expect(()=>nativeDisplayCells(sample().summary.source.native_grid.slice(1),sample().summary.source.bounds)).toThrow('直交');});
 it('retains original fixture pooled calculation',()=>{const records=[[[3,4],[0,10]],[[-3,4],[0,-10]]],F={pressures:[1000],points:[{id:0},{id:1}],value:(r:any,p:number)=>r[p],summary:(vs:number[][])=>{const u=vs.reduce((a,v)=>a+v[0],0)/vs.length,v=vs.reduce((a,q)=>a+q[1],0)/vs.length,s=vs.reduce((a,q)=>a+Math.hypot(...q),0)/vs.length;return{u,v,s,R:Math.hypot(u,v)/s};}};const q=aggregateFixture(F,records)[0];expect(q.s).toBe(7.5);expect(q.v).toBe(2);expect(q.R).toBeCloseTo(2/7.5);expect(q.spatialRange).toBe(5);});
 it('retains the actual artificial calendar and all three summary groupings',()=>{const scope:any={window:{},document:{}};installFixture(scope);const F=scope.window.WindFixture,selected=F.select({years:[2020,2020],hours:[3]}),quarter=Array.from({length:48},(_,i)=>selected.filter((r:any)=>r.quarter===i)),half=Array.from({length:24},(_,i)=>selected.filter((r:any)=>r.bin===i)),months=Array.from({length:12},(_,i)=>selected.filter((r:any)=>r.month===i)),cache={selected,quarter,half,months,quarterStats:quarter.map(r=>aggregateFixture(F,r)),halfStats:half.map(r=>aggregateFixture(F,r)),monthStats:months.map(r=>aggregateFixture(F,r))},state={from:2020,to:2020,hours:[3],annualGrain:'quarter',mapGrain:'month',level:8,revision:1};const vm=fixtureViewModel(F,cache,state);expect(vm.annualPeriods).toHaveLength(48);expect(vm.spatialPeriods).toHaveLength(12);expect(vm.cells).toHaveLength(9);expect(vm.annualPeriods.reduce((n,p)=>n+p.timeCount,0)).toBe(366);const independent=F.summary(quarter[0].flatMap((r:any)=>F.points.map((p:any)=>F.value(r,p.id,8))));expect(vm.annual[0][8]?.s).toBe(independent.s);expect(vm.annual[0][8]?.R).toBe(independent.R);expect(vm.metadata.weatherValidHoursJST).toEqual([3]);expect(vm.metadata.selectedRecordCount).toBe(366);expect(annualPlots(vm,direction).match(/data-level=/g)).toHaveLength(48*16*4);expect(spatialPlot(vm,0,'wind','all',false).match(/data-grid=/g)).toHaveLength(9);});
 it('exports applied population/provenance and starts from captured figure not draft',()=>{const a=sample(),vm=climateViewModel(a),el={viewBox:{baseVal:{width:190,height:175}},closest:()=>null,getAttribute:()=> '1月前半',innerHTML:'<rect data-grid="99"/>'} as unknown as SVGSVGElement;const out=createWindExport(vm,'spatial',[el],{mode:'wind',scale:'all',page:0,background:false,legend:'legend'});a.summary.population.selected_cell_ids=[];expect(((out.metadata as any).population).selected_cell_ids).toHaveLength(4);expect((out.metadata as any).query_hash).toBe('qh1');expect(out.source).toContain('保存気象集計');expect(out.source).not.toContain('人工データ');expect(out.metadata.periods).toHaveLength(12);});
 it('annual export does not claim a map background when none is drawn',()=>{const vm=climateViewModel(sample()),el={viewBox:{baseVal:{width:1100,height:350}},closest:()=>null,getAttribute:()=> 'annual',innerHTML:'<rect data-level="18"/>'} as unknown as SVGSVGElement;const out=createWindExport(vm,'annual',[el],{mode:'wind',scale:'all',page:0,background:true,legend:'legend'});expect(out.metadata.background).toBe(false);expect(out.source).toContain('この年間図には使用していません');expect(out.source).not.toContain('地理背景：国土地理院');});
 it('checks query bounds and fixed envelope identities, key-order does not matter',()=>{const a=sample();expect(validateClimateArtifact(a)).toBe(a);expect(queryIssue({...a.query,bounds:{...a.query.bounds!,west:NaN}},a.summary.source)).toContain('有限');expect(queryKey({a:1,b:2})).toBe(queryKey({b:2,a:1}));expect(()=>validateClimateArtifact({...a,result_hash:'other'})).toThrow('一致');});
});
describe('actual climate API transport',()=>{
 const instance='climate-service';
 async function lease(owner:boolean){vi.stubGlobal('navigator',{locks:{request:(_name:string,_options:unknown,callback:(lock:object|null)=>Promise<void>)=>callback(owner?{}:null)}});await claimWriteLease();}
 beforeEach(()=>{releaseWriteLease();setServiceIdentity(null);});
 afterEach(()=>{releaseWriteLease();setServiceIdentity(null);vi.unstubAllGlobals();});
 it('rejects climate aggregation from a reader before any fetch while saved GET remains available',async()=>{
  const {climateApi:actual}=await vi.importActual<typeof import('./climateApi')>('./climateApi');const fetch=vi.fn().mockResolvedValue({ok:true,status:200,json:async()=>sample()});vi.stubGlobal('fetch',fetch);setServiceIdentity(instance);await lease(false);
  await expect(actual.create(sample().query,'reader-request')).rejects.toThrow('送信権');expect(fetch).not.toHaveBeenCalled();
  await actual.get('saved');expect(fetch).toHaveBeenCalledTimes(1);expect(fetch.mock.calls[0][1].method).toBeUndefined();
 });
 it('rejects owner climate aggregation until the service identity is confirmed',async()=>{
  const {climateApi:actual}=await vi.importActual<typeof import('./climateApi')>('./climateApi');const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await lease(true);
  await expect(actual.create(sample().query,'unknown-service-request')).rejects.toThrow('保存先の識別');expect(fetch).not.toHaveBeenCalled();
 });
 it('uses explicit owner create and separate encoded GET paths with the confirmed write identity',async()=>{
  const {climateApi:actual}=await vi.importActual<typeof import('./climateApi')>('./climateApi');const {request}=await import('./api');const fetch=vi.fn().mockResolvedValue({ok:true,status:200,json:async()=>sample()});vi.stubGlobal('fetch',fetch);setServiceIdentity(instance);await lease(true);
  await actual.create(sample().query,'same-request');expect(fetch.mock.calls[0][0]).toBe('/api/v1/climate-analyses');expect(JSON.parse(fetch.mock.calls[0][1].body)).toEqual({client_request_id:'same-request',query:sample().query});expect(fetch.mock.calls[0][1].headers['X-Balloon-Instance-Id']).toBe(instance);
  await actual.get('a /x');expect(fetch.mock.calls[1][0]).toBe('/api/v1/climate-analyses/a%20%2Fx');expect(fetch.mock.calls[1][1].method).toBeUndefined();
  await request('/climate-analyses',{method:'post',headers:{'X-Balloon-Instance-Id':'another-state'},body:JSON.stringify({client_request_id:'same-request',query:sample().query})});expect(fetch.mock.calls[2][1].headers['X-Balloon-Instance-Id']).toBe(instance);expect(fetch).toHaveBeenCalledTimes(3);
 });
});
// Deliberately small actual-hook scheduler: no React DOM or browser acceptance is claimed.
function harness(saved:any,screen=false){let cursor=0;const slots:any[]=[],effects:(()=>void)[]=[],cleanups:(()=>void)[]=[];const onView=vi.fn();const owner={ref:(v:any)=>{const i=cursor++;return slots[i]??(slots[i]={current:v});},state:(v:any)=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],(n:any)=>{slots[i]=typeof n==='function'?n(slots[i]):n;}];},memo:(f:any,d:any[])=>{const i=cursor++;if(!slots[i]||d.some((v,j)=>!Object.is(v,slots[i].d[j])))slots[i]={d,v:f()};return slots[i].v;},effect:(f:any,d:any[])=>{const i=cursor++;if(!slots[i]){slots[i]=d;effects.push(()=>{const cleanup=f();if(cleanup)cleanups.push(cleanup);});}}};const render=()=>{cursor=0;h.current=owner;if(screen){const el=WeatherScreen({saved,onView,handoff:vi.fn(),background:false,mode:'climate'});return (el.type as any)(el.props);}return useClimateWorkspace(saved,onView);};const api=render();effects.splice(0).forEach(f=>f());return{render,api,onView,unmount:()=>cleanups.forEach(f=>f())};}
const deferred=<T,>()=>{let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
describe('actual climate hook finite async boundaries',()=>{
 beforeEach(()=>{vi.useFakeTimers();apiMock.sources.mockReset().mockResolvedValue({sources:[sample().summary.source],errors:[]});apiMock.get.mockReset();apiMock.create.mockReset();});afterEach(()=>vi.useRealTimers());
 it('keeps an unavailable saved source visibly selected until explicit current-source choice, without recalculation',async()=>{const a=sample(),next={...a.summary.source,source_id:'src2'};apiMock.sources.mockResolvedValue({sources:[next],errors:[]});apiMock.get.mockResolvedValue(a);const x=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:'dbhash',source_id:'src1'}},true);await flush();const nodes=(node:any):any[]=>Array.isArray(node)?node.flatMap(nodes):node&&typeof node==='object'?[node,...nodes(node.props?.children)]:[];const controls=nodes(x.render()),select=controls.find(n=>n.type==='select'&&n.props.value==='src1'),selected=nodes(select).find(n=>n.type==='option'&&n.props.value==='src1');expect(selected.props.disabled).toBe(true);expect(selected.props.children).toContain('現在の一覧にありません');expect(nodes(select).find(n=>n.type==='option'&&n.props.value==='src2').props.disabled).not.toBe(true);expect(apiMock.create).not.toHaveBeenCalled();expect(x.onView).not.toHaveBeenCalled();select.props.onChange({target:{value:'src2'}});const after=nodes(x.render()),newSelect=after.find(n=>n.type==='select'&&n.props.value==='src2');expect(newSelect).toBeTruthy();expect(nodes(newSelect).some(n=>n.type==='option'&&n.props.value==='src1')).toBe(false);expect(x.onView.mock.calls.at(-1)![0].applied.source_id).toBe('src1');expect(apiMock.get).toHaveBeenCalledOnce();expect(apiMock.create).not.toHaveBeenCalled();x.unmount();});
 function resolvedResponse(q:import('./climateDomain').ClimateQuery,id='resolved'){const a=sample();a.analysis_id=id;a.query={...structuredClone(q),bounds:structuredClone(q.bounds??a.summary.source.bounds)};a.summary.query=a.query;a.summary.spatial.level_id=q.level_id;return a;}
 it.each([false,true])('accepts initial full-domain resolution without rewriting the submitted query (explicit=%s)',async(explicit)=>{const x=harness(undefined);await flush();if(explicit)x.render().editQuery({...x.render().view.draft_query!,bounds:structuredClone(sample().summary.source.bounds)});const sent=structuredClone(x.render().view.draft_query!);apiMock.create.mockImplementation(async(q:any)=>resolvedResponse(q));await x.render().calculate();expect(apiMock.create.mock.calls[0][0]).toEqual(sent);expect(x.render().artifact?.analysis_id).toBe('resolved');expect(x.render().view.draft_query?.bounds).toEqual(sample().summary.source.bounds);expect(x.render().error).toBe('');expect(x.render().view.applied?.analysis_id).toBe('resolved');x.unmount();});
 it('retries a null-bounds unknown response with the same ID and bytes before accepting the resolved result',async()=>{const x=harness(undefined);await flush();apiMock.create.mockRejectedValueOnce(new Error('response lost')).mockImplementationOnce(async(q:any)=>resolvedResponse(q));const sent=structuredClone(x.render().view.draft_query!);await x.render().calculate();expect(x.render().artifact).toBeNull();expect(x.render().view.draft_query).toEqual(sent);vi.advanceTimersByTime(5000);await flush();expect(apiMock.create).toHaveBeenCalledOnce();await x.render().calculate();expect(apiMock.create.mock.calls[0][0]).toEqual(sent);expect(apiMock.create.mock.calls[1][0]).toEqual(sent);expect(apiMock.create.mock.calls[0][1]).toBe(apiMock.create.mock.calls[1][1]);expect(x.render().artifact?.analysis_id).toBe('resolved');x.unmount();});
 it.each(['partial-bounds','other-query-source','other-summary-source','other-dataset','other-hours','other-level','subset-expanded'])('rejects a mismatched resolved response: %s',async(kind)=>{const a=sample();apiMock.get.mockResolvedValue(a);const x=harness({schema:'balloon.climate-view/1',draft_query:{...a.query,bounds:null},applied:{analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:'dbhash',source_id:'src1'}});await flush();if(kind==='subset-expanded')x.render().editQuery({...a.query,bounds:{west:140,east:140,south:40,north:40}});const sent=structuredClone(x.render().view.draft_query!);apiMock.create.mockImplementation(async(q:any)=>{const bad=resolvedResponse(q);if(kind==='partial-bounds')bad.query.bounds={west:140,east:140,south:40,north:40};if(kind==='other-query-source')bad.query.source_id='wrong';if(kind==='other-summary-source')bad.summary.source.source_id='wrong';if(kind==='other-dataset')bad.summary.source.dataset_sha256='wrong';if(kind==='other-hours')bad.query.hours_utc=[0];if(kind==='other-level')bad.query.level_id=8;if(kind==='subset-expanded')bad.query.bounds=structuredClone(a.summary.source.bounds);return bad;});await x.render().calculate();expect(x.render().error).toContain('要求した条件');expect(x.render().artifact?.analysis_id).toBe('a1');expect(x.render().view.draft_query).toEqual(sent);expect(x.onView.mock.calls.some(([v])=>v.applied?.analysis_id==='resolved')).toBe(false);x.unmount();});
 it('captures descriptor bounds before POST so a later catalog mutation cannot redefine full domain',async()=>{const d=sample().summary.source;apiMock.sources.mockResolvedValue({sources:[d],errors:[]});const late=deferred<ClimateArtifact>();apiMock.create.mockReturnValue(late.promise);const x=harness(undefined);await flush();const sent=structuredClone(x.render().view.draft_query!),pending=x.render().calculate();d.bounds.east=140;late.resolve(resolvedResponse(sent));await pending;expect(x.render().artifact?.query.bounds?.east).toBe(141);expect(x.render().error).toBe('');expect(apiMock.create.mock.calls[0][0].bounds).toBeNull();x.unmount();});
 it('does not adopt resolved success over a later region and UTC draft edit',async()=>{const late=deferred<ClimateArtifact>();apiMock.create.mockReturnValue(late.promise);const x=harness(undefined);await flush();const sent=structuredClone(x.render().view.draft_query!),pending=x.render().calculate(),draft={...sent,bounds:{west:140,east:140,south:40,north:40},hours_utc:[6]};x.render().editQuery(draft);late.resolve(resolvedResponse(sent));await pending;expect(x.render().view.draft_query).toEqual(draft);expect(x.render().artifact).toBeNull();expect(x.render().view.applied).toBeUndefined();x.unmount();});
 it('restores a fixed artifact through GET even when DB listing fails; no POST or dirty echo',async()=>{apiMock.sources.mockRejectedValue(new Error('DB unavailable'));apiMock.get.mockResolvedValue(sample());const a=sample(),x=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:'dbhash',source_id:'src1'}});await flush();expect(x.render().artifact?.analysis_id).toBe('a1');expect(apiMock.create).not.toHaveBeenCalled();expect(x.onView).not.toHaveBeenCalled();x.unmount();});
 it('draft edits do not discard the saved fixed figure restore; restore does not clear POST errors',async()=>{const old=deferred<ClimateArtifact>();apiMock.get.mockReturnValue(old.promise);const a=sample(),x=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,source_id:'src1',query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:'dbhash'}});await flush();x.render().editQuery({...a.query,level_id:8});apiMock.create.mockRejectedValue(new Error('POST deliberately failed'));await x.render().calculate();old.resolve(a);await flush();expect(x.render().artifact?.analysis_id).toBe('a1');expect(x.render().view.draft_query?.level_id).toBe(8);expect(x.render().error).toContain('POST deliberately failed');expect(apiMock.create).toHaveBeenCalledTimes(1);x.unmount();});
 it('edited draft still shows restored A without any calculation POST',async()=>{const old=deferred<ClimateArtifact>();apiMock.get.mockReturnValue(old.promise);const a=sample(),x=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,source_id:'src1',query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:'dbhash'}});await flush();x.render().editQuery({...a.query,bounds:{west:140,east:140,south:40,north:40}});old.resolve(a);await flush();expect(x.render().artifact?.analysis_id).toBe('a1');expect(x.render().view.draft_query?.bounds?.east).toBe(140);expect(apiMock.create).not.toHaveBeenCalled();x.unmount();});
 it('restored A can display while B remains busy with its own status',async()=>{const old=deferred<ClimateArtifact>(),next=deferred<ClimateArtifact>();apiMock.get.mockReturnValue(old.promise);apiMock.create.mockReturnValue(next.promise);const a=sample(),x=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,source_id:'src1',query_hash:a.query_hash,result_hash:a.result_hash,dataset_sha256:'dbhash'}});await flush();x.render().editQuery({...a.query,level_id:8});const pending=x.render().calculate();old.resolve(a);await flush();expect(x.render().artifact?.analysis_id).toBe('a1');expect(x.render().busy).toBe(true);expect(x.render().status).toContain('読み出しています');const completed=sample();completed.analysis_id='B';completed.query={...completed.query,level_id:8};completed.summary.query=completed.query;next.resolve(completed);await pending;expect(x.render().artifact?.analysis_id).toBe('B');expect(x.render().busy).toBe(false);x.unmount();});
 it('late requested A cannot replace edited B or overwrite query; explicit B wins',async()=>{const x=harness(undefined);await flush();const A=deferred<ClimateArtifact>(),B=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(A.promise).mockReturnValueOnce(B.promise);let w=x.render();const startA=w.calculate();w=x.render();w.editQuery({...w.view.draft_query!,level_id:8});const startB=x.render().calculate();const b=sample();b.analysis_id='b';b.query={...b.query,level_id:8};b.summary.query=b.query;b.summary.spatial.level_id=8;expect(apiMock.create).toHaveBeenCalledTimes(1);A.resolve(sample());await startA;await flush();expect(x.render().artifact).toBeNull();expect(apiMock.create).toHaveBeenCalledTimes(2);B.resolve(b);await startB;expect(x.render().artifact?.analysis_id).toBe('b');expect(x.render().view.draft_query?.level_id).toBe(8);x.unmount();});
 it('restoration response cannot override a new request; same failure retries receipt',async()=>{const old=deferred<ClimateArtifact>();apiMock.get.mockReturnValue(old.promise);const y=harness({schema:'balloon.climate-view/1',draft_query:sample().query,applied:{analysis_id:'a1',query_hash:'qh1',result_hash:'rh1',dataset_sha256:'dbhash',source_id:'src1'}});await flush();apiMock.create.mockRejectedValueOnce(new Error('temporarily unavailable')).mockResolvedValueOnce({...sample(),analysis_id:'new'});await y.render().calculate();await y.render().calculate();expect(apiMock.create.mock.calls[0][1]).toBe(apiMock.create.mock.calls[1][1]);old.resolve(sample());await flush();expect(y.render().artifact?.analysis_id).toBe('new');y.unmount();});
 it('unmount aborts and releases timers; late success does not save',async()=>{const late=deferred<ClimateArtifact>();apiMock.create.mockReturnValue(late.promise);const x=harness(undefined);await flush();const pending=x.render().calculate(),signal=apiMock.create.mock.calls[0][2] as AbortSignal;expect(vi.getTimerCount()).toBe(1);x.unmount();expect(signal.aborted).toBe(true);expect(vi.getTimerCount()).toBe(0);late.resolve(sample());await pending;expect(x.onView).not.toHaveBeenCalled();});
 async function pressureHarness(owner=true){vi.stubGlobal('navigator',{locks:{request:(_name:string,_options:unknown,fn:any)=>fn(owner?{}:null)}});await claimWriteLease();const a=sample();apiMock.get.mockResolvedValue(a);const x=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,source_id:'src1',dataset_sha256:'dbhash'}});await flush();return x;}
 function atLevel(level:number,id:string){const a=sample();a.analysis_id=id;a.query={...a.query,level_id:level};a.summary.query=a.query;a.summary.spatial.level_id=level;return a;}
 it('debounces pressure only, preserves invalid draft population, and saves only the accepted reference',async()=>{const x=await pressureHarness();try{x.render().editQuery({...sample().query,hours_utc:[0],bounds:{west:150,east:140,south:40,north:41}});x.render().selectPressure(8);vi.advanceTimersByTime(200);x.render().selectPressure(2);vi.advanceTimersByTime(300);await flush();expect(apiMock.create).not.toHaveBeenCalled();expect(x.render().artifact.analysis_id).toBe('a1');x.render().selectPressure(8);const response=deferred<ClimateArtifact>();apiMock.create.mockReturnValue(response.promise);vi.advanceTimersByTime(299);await flush();expect(apiMock.create).not.toHaveBeenCalled();vi.advanceTimersByTime(1);await flush();expect(apiMock.create.mock.calls[0][0]).toEqual({...sample().query,level_id:8});expect(x.render().artifact.query.level_id).toBe(2);x.render().editQuery({...x.render().view.draft_query,hours_utc:[18]});response.resolve(atLevel(8,'pressure8'));await flush();expect(x.render().artifact.analysis_id).toBe('pressure8');expect(x.render().view.draft_query.hours_utc).toEqual([18]);expect(x.render().view.draft_query.bounds.west).toBe(150);expect(x.render().view.draft_query.level_id).toBe(8);expect(x.onView.mock.calls.at(-1)![0].applied.analysis_id).toBe('pressure8');expect(x.render().pressure).toBeNull();}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('never overlaps pressure POSTs and drops a late plane after returning to the displayed plane',async()=>{const x=await pressureHarness();try{const old=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(old.promise);x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().selectPressure(2);vi.advanceTimersByTime(500);await flush();expect(apiMock.create).toHaveBeenCalledTimes(1);old.resolve(atLevel(8,'obsolete'));await flush();expect(x.render().artifact.analysis_id).toBe('a1');expect(x.render().pressure).toBeNull();expect(x.render().view.draft_query.level_id).toBe(2);expect(x.render().status).toContain('気圧面に戻りました');}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('coalesces the latest pressure while one is in flight and does not flash the stale response',async()=>{const x=await pressureHarness();try{const d={...sample().summary.source,levels:[...sample().summary.source.levels,{level_id:5,level_hpa:500,isa_alt_m:5000,alt_geom_mean_m:5000,alt_geom_min_m:4900,alt_geom_max_m:5100}]};apiMock.sources.mockResolvedValue({sources:[d],errors:[]});await x.render().refreshSources();const first=deferred<ClimateArtifact>(),last=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(first.promise).mockReturnValueOnce(last.promise);x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().selectPressure(5);vi.advanceTimersByTime(300);await flush();expect(apiMock.create).toHaveBeenCalledTimes(1);first.resolve(atLevel(8,'stale'));await flush();expect(x.render().artifact.analysis_id).toBe('a1');expect(apiMock.create).toHaveBeenCalledTimes(2);expect(apiMock.create.mock.calls[1][0].level_id).toBe(5);last.resolve(atLevel(5,'latest'));await flush();expect(x.render().artifact.analysis_id).toBe('latest');}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('manual population apply supersedes pressure and waits for its active request to settle',async()=>{const x=await pressureHarness();try{const first=deferred<ClimateArtifact>(),manual=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(first.promise).mockReturnValueOnce(manual.promise);x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().editQuery({...x.render().view.draft_query,level_id:2,bounds:null});const work=x.render().calculate();expect(apiMock.create).toHaveBeenCalledTimes(1);first.resolve(atLevel(8,'stale'));await flush();expect(x.render().artifact.analysis_id).toBe('a1');expect(apiMock.create).toHaveBeenCalledTimes(2);const a=atLevel(2,'manual');manual.resolve(a);await work;expect(x.render().artifact.analysis_id).toBe('manual');}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('does not overwrite a later explicit draft plane and cancels queued work on restore and disposal',async()=>{const x=await pressureHarness();try{const response=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(response.promise);x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().editQuery({...x.render().view.draft_query,level_id:2});response.resolve(atLevel(8,'stale'));await flush();expect(x.render().view.draft_query.level_id).toBe(2);expect(x.render().artifact.analysis_id).toBe('a1');x.render().selectPressure(8);await x.render().restoreSaved();vi.advanceTimersByTime(400);await flush();expect(apiMock.create).toHaveBeenCalledTimes(1);x.render().selectPressure(8);x.unmount();vi.advanceTimersByTime(400);await flush();expect(apiMock.create).toHaveBeenCalledTimes(1);}finally{releaseWriteLease();vi.unstubAllGlobals();}});
 it('blocks reader, missing source and unsupported frozen hours without POST; ownership alone does not resume',async()=>{const x=await pressureHarness(false);try{x.render().selectPressure(8);vi.advanceTimersByTime(400);await flush();expect(apiMock.create).not.toHaveBeenCalled();expect(x.render().pressure.state).toBe('blocked');vi.stubGlobal('navigator',{locks:{request:(_n:any,_o:any,fn:any)=>fn({})}});await claimWriteLease();vi.advanceTimersByTime(400);await flush();expect(apiMock.create).not.toHaveBeenCalled();apiMock.sources.mockResolvedValue({sources:[],errors:[]});await x.render().refreshSources();x.render().retryPressure();expect(x.render().pressure.message).toContain('資料');expect(apiMock.create).not.toHaveBeenCalled();}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}const a=sample();a.query.hours_utc=[0];apiMock.sources.mockResolvedValue({sources:[a.summary.source],errors:[]});apiMock.get.mockResolvedValue(a);vi.stubGlobal('navigator',{locks:{request:(_n:any,_o:any,fn:any)=>fn({})}});await claimWriteLease();const y=harness({schema:'balloon.climate-view/1',draft_query:a.query,applied:{analysis_id:a.analysis_id,query_hash:a.query_hash,result_hash:a.result_hash,source_id:'src1',dataset_sha256:'dbhash'}});try{await flush();y.render().selectPressure(8);vi.advanceTimersByTime(400);await flush();expect(apiMock.create).not.toHaveBeenCalled();expect(y.render().pressure.message).toContain('全4時刻');}finally{y.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('retries an uncertain pressure response with the same receipt and no automatic retries',async()=>{const x=await pressureHarness();try{apiMock.create.mockRejectedValueOnce(new Error('network unknown')).mockResolvedValueOnce(atLevel(8,'retried'));x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();expect(x.render().pressure.state).toBe('failed');const id=apiMock.create.mock.calls[0][1];vi.advanceTimersByTime(5000);await flush();expect(apiMock.create).toHaveBeenCalledTimes(1);x.render().retryPressure();vi.advanceTimersByTime(300);await flush();expect(apiMock.create.mock.calls[1][1]).toBe(id);expect(x.render().artifact.analysis_id).toBe('retried');}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});

 it('starts within the first 300ms under continuous input and can return to a valid stale-response cache without POST',async()=>{const x=await pressureHarness();try{const d={...sample().summary.source,levels:[...sample().summary.source.levels,{level_id:5,level_hpa:500,isa_alt_m:5000,alt_geom_mean_m:5000,alt_geom_min_m:4900,alt_geom_max_m:5100}]};apiMock.sources.mockResolvedValue({sources:[d],errors:[]});await x.render().refreshSources();const first=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(first.promise);x.render().selectPressure(8);vi.advanceTimersByTime(100);x.render().selectPressure(5);vi.advanceTimersByTime(100);x.render().selectPressure(8);vi.advanceTimersByTime(100);await flush();expect(apiMock.create).toHaveBeenCalledOnce();expect(apiMock.create.mock.calls[0][0].level_id).toBe(8);x.render().selectPressure(5);first.resolve(atLevel(8,'valid-but-stale'));await flush();expect(x.render().artifact.analysis_id).toBe('a1');x.render().selectPressure(8);await flush();expect(x.render().artifact.analysis_id).toBe('valid-but-stale');expect(x.render().status).toContain('追加の再集計は行っていません');vi.advanceTimersByTime(500);await flush();expect(apiMock.create).toHaveBeenCalledOnce();}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('bounds the same-population cache to six planes and clears it on restore',async()=>{const x=await pressureHarness();try{const source=sample().summary.source;source.levels=Array.from({length:7},(_,i)=>({level_id:i+2,level_hpa:1000-i*100,isa_alt_m:i*1000,alt_geom_mean_m:i*1000,alt_geom_min_m:i*1000,alt_geom_max_m:i*1000}));apiMock.sources.mockResolvedValue({sources:[source],errors:[]});await x.render().refreshSources();apiMock.create.mockImplementation(async(q:any)=>atLevel(q.level_id,'plane'+q.level_id));for(const level of [3,4,5,6,7,8]){x.render().selectPressure(level);vi.advanceTimersByTime(300);await flush();}expect(apiMock.create).toHaveBeenCalledTimes(6);x.render().selectPressure(7);await flush();expect(apiMock.create).toHaveBeenCalledTimes(6);x.render().selectPressure(2);vi.advanceTimersByTime(300);await flush();expect(apiMock.create).toHaveBeenCalledTimes(7);expect(x.render().artifact.analysis_id).toBe('plane2');apiMock.get.mockResolvedValue(atLevel(2,'plane2'));await x.render().restoreSaved();x.render().selectPressure(7);vi.advanceTimersByTime(300);await flush();expect(apiMock.create).toHaveBeenCalledTimes(8);}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('does not retain an old active response in the cache after a manual request resets its generation',async()=>{const x=await pressureHarness();try{const active=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(active.promise).mockResolvedValueOnce(atLevel(2,'manual2')).mockResolvedValueOnce(atLevel(8,'fresh8'));x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().editQuery({...sample().query});const manual=x.render().calculate();active.resolve(atLevel(8,'old8'));await manual;expect(x.render().artifact.analysis_id).toBe('manual2');x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();expect(apiMock.create).toHaveBeenCalledTimes(3);expect(x.render().artifact.analysis_id).toBe('fresh8');expect(x.render().view.draft_query).not.toBe(x.render().artifact.query);}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});

 async function pointHarness(owner=true){const x=await pressureHarness(owner);const d=sample().summary.source;d.capabilities.wind_rose_point_select=true;apiMock.sources.mockResolvedValue({sources:[d],errors:[]});await x.render().refreshSources();return x;}
 it('native point selection keeps region, UTC and pressure drafts separate from the applied query',async()=>{const x=await pointHarness();try{x.render().editQuery({...sample().query,level_id:8,hours_utc:[0],bounds:{west:150,east:140,south:40,north:41}});const response=deferred<ClimateArtifact>();apiMock.create.mockReturnValue(response.promise);x.render().selectPoint(7);expect(apiMock.create.mock.calls[0][0]).toEqual({...sample().query,rose_cell_id:7});expect(x.render().artifact.analysis_id).toBe('a1');x.render().selectPressure(8);expect(apiMock.create).toHaveBeenCalledOnce();expect(x.render().point.state).toBe('running');x.render().editQuery({...x.render().view.draft_query,hours_utc:[18]});response.resolve(resolvedResponse({...sample().query,rose_cell_id:7},'point7'));await flush();expect(x.render().artifact.query.rose_cell_id).toBe(7);expect(x.render().artifact.query.level_id).toBe(2);expect(x.render().view.draft_query).toEqual({...sample().query,level_id:8,hours_utc:[18],bounds:{west:150,east:140,south:40,north:41},rose_cell_id:7});expect(x.render().point).toBeNull();}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('point selection supersedes active pressure through the same queue without showing the late plane',async()=>{const x=await pointHarness();try{const plane=deferred<ClimateArtifact>(),point=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(plane.promise).mockReturnValueOnce(point.promise);x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().selectPoint(52);expect(apiMock.create).toHaveBeenCalledOnce();plane.resolve(atLevel(8,'obsolete-plane'));await flush();expect(x.render().artifact.analysis_id).toBe('a1');expect(apiMock.create).toHaveBeenCalledTimes(2);expect(apiMock.create.mock.calls[1][0]).toEqual({...sample().query,rose_cell_id:52});point.resolve(resolvedResponse(apiMock.create.mock.calls[1][0],'point52'));await flush();expect(x.render().artifact.analysis_id).toBe('point52');expect(x.render().view.draft_query.level_id).toBe(8);}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('point retries keep the request ID, and a later point wins without overlapping requests',async()=>{const x=await pointHarness();try{apiMock.create.mockRejectedValueOnce(new Error('lost point response'));x.render().selectPoint(7);await flush();expect(x.render().point.state).toBe('failed');const id=apiMock.create.mock.calls[0][1];vi.advanceTimersByTime(5000);await flush();expect(apiMock.create).toHaveBeenCalledOnce();const old=deferred<ClimateArtifact>();apiMock.create.mockReturnValueOnce(old.promise).mockImplementationOnce(async(q:any)=>resolvedResponse(q,'latest52'));x.render().retryPoint();expect(apiMock.create.mock.calls[1][1]).toBe(id);x.render().selectPoint(52);expect(apiMock.create).toHaveBeenCalledTimes(2);old.resolve(resolvedResponse({...sample().query,rose_cell_id:7},'late7'));await flush();expect(x.render().artifact.analysis_id).toBe('latest52');expect(apiMock.create).toHaveBeenCalledTimes(3);expect(x.render().view.draft_query.rose_cell_id).toBe(52);}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('does not reuse pressure cache from another point and restores the saved point without POST',async()=>{const x=await pointHarness();try{apiMock.create.mockImplementation(async(q:any)=>resolvedResponse(q,'p'+q.level_id+'-'+q.rose_cell_id));x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();x.render().selectPressure(2);await flush();expect(apiMock.create).toHaveBeenCalledOnce();x.render().selectPoint(7);await flush();x.render().selectPressure(8);vi.advanceTimersByTime(300);await flush();expect(apiMock.create).toHaveBeenCalledTimes(3);expect(apiMock.create.mock.calls[2][0].rose_cell_id).toBe(7);const applied=structuredClone(x.render().artifact);apiMock.get.mockResolvedValue(applied);await x.render().restoreSaved();expect(x.render().artifact.query.rose_cell_id).toBe(7);expect(apiMock.create).toHaveBeenCalledTimes(3);}finally{x.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('blocks a reader, legacy fixed-point source, and unknown native ID before any POST',async()=>{const reader=await pointHarness(false);try{reader.render().selectPoint(7);await flush();expect(reader.render().point.state).toBe('blocked');expect(apiMock.create).not.toHaveBeenCalled();}finally{reader.unmount();releaseWriteLease();vi.unstubAllGlobals();}apiMock.sources.mockResolvedValue({sources:[sample().summary.source],errors:[]});const old=await pressureHarness();try{old.render().selectPoint(7);expect(old.render().point.state).toBe('blocked');expect(apiMock.create).not.toHaveBeenCalled();const d=sample().summary.source;d.capabilities.wind_rose_point_select=true;apiMock.sources.mockResolvedValue({sources:[d],errors:[]});await old.render().refreshSources();old.render().selectPoint(999);expect(old.render().point.state).toBe('blocked');expect(apiMock.create).not.toHaveBeenCalled();}finally{old.unmount();releaseWriteLease();vi.unstubAllGlobals();}});
 it('preserves omitted point bytes and selects sparse native IDs from the actual projected grid',()=>{const a=sample(),vm=climateViewModel(a),g=geographyFrame(440,300,vm.nativeBounds,false);expect(queryKey(normalizeClimateQuery({...a.query,rose_cell_id:undefined}))).toBe(queryKey(a.query));for(const c of a.summary.source.native_grid){const [x,y]=g.project(c.lat,c.lon);expect(nearestRosePoint(vm,x,y)).toBe(c.cell_id);}expect(nearestRosePoint(vm,-1,200)).toBeNull();const markup=nativeRosePointMap(vm,52,false);expect(markup.match(/data-native-rose-cell=/g)).toHaveLength(4);expect(markup).toContain('data-selected-native-cell="52"');expect(markup).not.toContain('https://cyberjapandata');});

});
