import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {climateHoursLabel,normalizeClimateQuery,queryIssue,queryKey,type ClimateArtifact,type ClimatePeriod,type ClimateGrain,type ClimateWindRose} from './climateDomain';
import {climateGrains,climateViewModel,annualQuarterViewModel} from './screens/weather/sources/climateSummary';
import {climateDisplayState} from './screens/weather/climateController';
import {annualPlots} from './screens/weather/plots';
import {checkedRose,climateRosePlot,meanProfilePlot,roseLegend,rosePointLabel,roseScale,roseUnavailable,rosePopulationLabel,roseMethod} from './screens/weather/climateDistributions';
import {createWindExport,createPreparedWindDownload,windDownloadConditions} from './screens/weather/export';
import {climateInterest} from './ClimateFlightHandoff';
import {readHistoricalInterest,mergeHistoricalView} from './historicalWorkspace';

const directions={appearance:()=>({fill:'blue',kind:'direction',label:'来向'}),legend:()=>'<g data-direction-key="from-circular"/>'};
function sample():ClimateArtifact {
 const cells=[{cell_id:285,lat:40,lon:140,gauss_weight:1},{cell_id:7,lat:40,lon:141,gauss_weight:1},{cell_id:52,lat:41,lon:140,gauss_weight:1},{cell_id:3,lat:41,lon:141,gauss_weight:1}],levels=[1000,300,100].map((h,i)=>({level_id:i,level_hpa:h,isa_alt_m:i*7000+100,alt_geom_mean_m:i*7000+150,alt_geom_min_m:i*7000,alt_geom_max_m:i*7000+200})),timebins:ClimatePeriod[]=Array.from({length:24},(_,i)=>({timebin_id:i,month:Math.floor(i/2)+1,bin:i%2+1,label:`${Math.floor(i/2)+1}月${i%2?'後半':'前半'}`,member_timebin_ids:[i],start_day:i%2?16:1,end_day_min:i%2?31:15,end_day_max:i%2?31:15,n_days_total:i+1,n_analyses_expected:(i+1)*4}));
 const bounds={west:140,east:141,south:40,north:41},query={source_id:'fixed',level_id:1,bounds,grain:'half' as const},source={source_id:'fixed',dataset_sha256:'data-fixed',bounds,native_grid:cells,native_grid_count:4,levels,timebins,capabilities:{annual:true,spatial:true,years_fixed:[2016,2025],native_hours_utc:[0,6,12,18],date_convention:'UTC',grain:'half',hour_filter:true,hour_level_ids:[0,1]},attribution:{license:'supplied'}};
 const scales={all_level_cell_mean_speed_max:25,selected_level_cell_mean_speed_max:20,annual_mean_speed_max:30,spatial_mean_speed_range_max:4};
 function rows(periods:ClimatePeriod[],value:number){return {annual:periods.flatMap(p=>levels.map(l=>({timebin_id:p.timebin_id,level_id:l.level_id,mean_u:value,mean_v:0,mean_speed:value+1,pooled_constancy:value/(value+1),from_deg:270,spatial_mean_speed_range:4,cell_count:4,time_count:p.n_analyses_expected,valid_time_count:p.n_analyses_expected,missing_time_count:0}))),spatial_rows:periods.flatMap(p=>cells.map(c=>({timebin_id:p.timebin_id,cell_id:c.cell_id,mean_u:value,mean_v:0,mean_speed:value+1,constancy:value/(value+1),from_deg:270,time_count:p.n_analyses_expected,valid_time_count:p.n_analyses_expected,missing_time_count:0}))) };}
 function rose(periods:ClimatePeriod[]):ClimateWindRose {return {available:true,point:cells[0],point_in_selected_region:true,level_id:1,native_hours_utc:[0,6,12,18],date_convention:'UTC',definition:'FROM; no separate calm category',sectors:Array.from({length:16},(_,i)=>({sector:i,centre_deg:i*22.5,lo_deg:(i*22.5-11.25+360)%360,hi_deg:i*22.5+11.25,wraps_north:i===0,compass_16:String(i)})),speed_classes:[['0-5',0,5],['5-10',5,10],['10-20',10,20],['20-30',20,30],['30-50',30,50],['50+',50,null]].map(([label,lo,hi],i)=>({speed_class:i,label:String(label),lo_ms:Number(lo),hi_ms:hi===null?null:Number(hi)})),rows:periods.flatMap(p=>Array.from({length:96},(_,i)=>({timebin_id:p.timebin_id,sector:Math.floor(i/6),speed_class:i%6,count:i===0?p.n_analyses_expected/4:i===7?p.n_analyses_expected*3/4:0,time_count:p.n_analyses_expected,frequency:i===0?.25:i===7?.75:0})))};}
 function group(grain:'month'|'season'){const sets=grain==='month'?Array.from({length:12},(_,i)=>[i+1]):[[12,1,2],[3,4,5],[6,7,8],[9,10,11]],periods=sets.map((months,i)=>{const members=timebins.filter(p=>months.includes(p.month!));return {timebin_id:i,label:grain==='month'?`${i+1}月`:['冬（12–2月）','春（3–5月）','夏（6–8月）','秋（9–11月）'][i],months,member_timebin_ids:members.map(p=>p.timebin_id),n_days_total:members.reduce((a,p)=>a+p.n_days_total,0),n_analyses_expected:members.reduce((a,p)=>a+p.n_analyses_expected,0)};});return {timebins:periods,...rows(periods,grain==='month'?11:21),display_scales:scales,wind_rose:rose(periods)};}
 const half=rows(timebins,1);return {schema:'balloon.climate.analysis-artifact/1',analysis_id:'fixed-analysis',query,query_hash:'fixed-query',result_hash:'fixed-result',created_at:'2026-10-02',summary:{schema:'climate-summary/1',source,query,levels,population:{timebins,selected_cell_ids:cells.map(c=>c.cell_id),selected_cell_count:4,native_grid_count:4,years_fixed:[2016,2025],date_convention:'UTC',native_hours_utc:[0,6,12,18],spatial_weighting:'gauss',count_definition:'per-point times'},annual:half.annual,spatial:{level_id:1,grid:cells,rows:half.spatial_rows},display_scales:scales,provenance:{query_hash:'fixed-query',result_hash:'fixed-result'},wind_rose:rose(timebins),summaries_by_grain:{month:group('month'),season:group('season')}}};
}

describe('fixed real-climate display extensions',()=>{
 it('uses independently supplied 48-period annual values without changing half-month spatial or flight interest',()=>{
  const a=sample(),base=climateViewModel(a),halfSnapshot=JSON.stringify(a.summary.annual);
  const timebins=Array.from({length:48},(_,i)=>{const month=Math.floor(i/4)+1,k=i%4,start=[1,8,16,23][k],end=[7,15,22,new Date(Date.UTC(2024,month,0)).getUTCDate()][k];return{timebin_id:i,month,bin:k+1,label:`${month}月 第${k+1}区分`,start_day:start,end_day_min:end,end_day_max:end,n_days_total:end-start+1,n_analyses_expected:4*(end-start+1)};});
  a.summary.annual_quarters={schema:'climate-annual-quarters/1',date_convention:'UTC',calendar_definition:{version:'utc-half-nested-quarters/1',description:'UTC calendar days'},timebins,display_scales:a.summary.display_scales,annual:timebins.flatMap(p=>a.summary.levels.map(l=>({...a.summary.annual.find(r=>r.level_id===l.level_id)!,timebin_id:p.timebin_id,time_count:p.n_analyses_expected,valid_time_count:p.n_analyses_expected,mean_speed:10+p.timebin_id}))).reverse()};
  const vm=annualQuarterViewModel(base,a),plot=annualPlots(vm,directions);
  expect(vm.annual).toHaveLength(48);expect(vm.annual[1][0]!.s).toBe(11);expect(vm.annual[47][0]!.s).toBe(57);
  expect(plot).toContain('data-period-count="48"');expect(plot).toContain('UTC月内4区分');expect(plot).not.toContain('UTC季節');expect(vm.metadata.period_membership).toEqual(timebins);expect(vm.annualPeriods[7].description).toContain('23–29日');
  expect(JSON.stringify(a.summary.annual)).toBe(halfSnapshot);expect(climateGrains(a)).toEqual(['half','month','season']);
  const view=climateDisplayState({annual_grain:'quarter',monthly_grain:'month',spatial_grain:'season'});expect(climateDisplayState(JSON.parse(JSON.stringify(view))).annual_grain).toBe('quarter');expect(climateInterest(a,{schema:'balloon.climate-view/1',annual_grain:view.annual_grain,monthly_grain:view.monthly_grain}).grain).toBe('month');
  for(const damage of [(x:any)=>x.annual.pop(),(x:any)=>x.annual[0]=x.annual[1],(x:any)=>x.annual[0].time_count++,(x:any)=>x.timebins[0].month=2,(x:any)=>x.date_convention='JST']){const broken=structuredClone(a);damage(broken.summary.annual_quarters);expect(()=>annualQuarterViewModel(base,broken)).toThrow();}
  delete a.summary.annual_quarters;expect(()=>annualQuarterViewModel(base,a)).toThrow();expect(climateViewModel(a).annual).toHaveLength(24);
 });
 it('projects supplied groups with their actual labels and rows, retaining old half artifacts',()=>{const a=sample();expect(climateGrains(a)).toEqual(['half','month','season']);const month=climateViewModel(a,'month'),season=climateViewModel(a,'season');expect(month.annual).toHaveLength(12);expect(month.annual[0][0]!.s).toBe(12);expect(season.annual[0][0]!.s).toBe(22);expect(season.annualPeriods[0].label).toBe('冬（12–2月）');expect(annualPlots(season,directions)).toContain('冬（12–2月）');expect(annualPlots(season,directions)).not.toContain('UTC半月');delete a.summary.summaries_by_grain;delete a.summary.wind_rose;expect(climateGrains(a)).toEqual(['half']);expect(climateViewModel(a).annual).toHaveLength(24);expect(()=>climateViewModel(a,'month')).toThrow('ありません');expect(roseUnavailable(climateViewModel(a))).toContain('保存結果');});
 it('puts each period name in visible SVG text, independent of HTML headings or accessible titles',()=>{const a=sample();for(const grain of climateGrains(a)){const vm=climateViewModel(a,grain);for(const index of [0,vm.annualPeriods.length-1])for(const draw of [meanProfilePlot,climateRosePlot]){const figure=draw(vm,index);const visible=figure.match(/<text\b[^>]*data-period-label="true"[^>]*>([^<]+)<\/text>/)?.[1];expect(visible).toBe(vm.annualPeriods[index].label);expect(figure).toContain('viewBox="0 0 190 196"');}}});
 it('exports exactly one visible period heading for real profile and rose, while retaining a fallback for other figures',()=>{const vm=climateViewModel(sample(),'season'),label=vm.annualPeriods[0].label;for(const [view,draw] of [['profile',meanProfilePlot],['rose',climateRosePlot]] as const){const body=draw(vm,0).replace(/^<svg[^>]*>|<\/svg>$/g,''),el={viewBox:{baseVal:{width:190,height:196}},closest:()=>({querySelector:()=>({textContent:label})}),getAttribute:()=>label,querySelector:()=>({}),innerHTML:body} as unknown as SVGSVGElement;const out=createWindExport(vm,view,[el],{mode:'wind',scale:'all',page:0,background:false,legend:'fixed'});expect([...out.source.matchAll(/<text\b[^>]*>([^<]*)<\/text>/g)].filter(m=>m[1]===label)).toHaveLength(1);const fallback={...el,innerHTML:'<path d="M0 0L1 1"/>',querySelector:()=>null} as unknown as SVGSVGElement;expect(createWindExport(vm,view,[fallback],{mode:'wind',scale:'all',page:0,background:false,legend:'fixed'}).source).toContain('>'+label+'</text>');}});
 it('keeps independent view partitions across save/restore',()=>{const state=climateDisplayState({annual_grain:'half',spatial_grain:'season',monthly_grain:'month',monthly_mode:'rose',monthly_page:1});expect(climateDisplayState(JSON.parse(JSON.stringify(state)))).toEqual(state);expect(state.annual_grain).toBe('half');expect(state.spatial_grain).toBe('season');});
 it('canonicalizes the four hours without changing the original request; rejects invalid/unsupported drafts',()=>{const a=sample(),q=a.query;expect(queryKey(normalizeClimateQuery({...q,hours_utc:[18,0,12,6]}))).toBe(queryKey(q));expect(normalizeClimateQuery({...q,hours_utc:undefined})).not.toHaveProperty('hours_utc');expect(normalizeClimateQuery({...q,hours_utc:[18,0]}).hours_utc).toEqual([0,18]);expect(queryIssue({...q,hours_utc:[]},a.summary.source)).toContain('一つ以上');expect(queryIssue({...q,hours_utc:[3]},a.summary.source)).toContain('一つ以上');const draft={...q,level_id:2,hours_utc:[0]};expect(queryIssue(draft,a.summary.source)).toContain('300');expect(draft.level_id).toBe(2);expect(queryIssue({...q,hours_utc:[0]},a.summary.source)).toBeNull();expect(climateHoursLabel(draft)).toBe('UTC 00時');});
 it('does not paint a whole-day rose for a subset or invent quantile bands',()=>{const a=sample();a.query.hours_utc=[18];a.summary.wind_rose={available:false,reason:'hour_subset_not_available'};const vm=climateViewModel(a);expect(checkedRose(vm)).toBeNull();expect(()=>climateRosePlot(vm,0)).toThrow('時刻を絞った');const mean=meanProfilePlot(vm,0);expect(mean).toContain('data-profile="mean"');expect(mean).not.toContain('<polygon');expect(mean).not.toContain('p90');});
 it('uses original six speed classes/counts, one common radius, and a fixed point outside the selected region',()=>{const a=sample(),r=a.summary.summaries_by_grain!.month!.wind_rose;if(r?.available)r.point_in_selected_region=false;const vm=climateViewModel(a,'month'),rose=checkedRose(vm)!;expect(rosePointLabel(rose)).toContain('選択地域外');expect(roseLegend(rose)).toContain('0-5 m/s');expect(roseLegend(rose)).toContain('50+ m/s');expect(roseScale(vm)).toBe(80);expect(climateRosePlot(vm,0)).toContain('data-radius-max="80"');expect(climateRosePlot(vm,11)).toContain('data-radius-max="80"');expect(climateRosePlot(vm,0)).toContain('data-count="9"');});
 it('rejects missing, duplicated, inconsistent and nonfinite rose bins instead of displaying a partial distribution',()=>{for(const mutate of [(r:any)=>r.rows.pop(),(r:any)=>r.rows[1]={...r.rows[0]},(r:any)=>r.rows[0].frequency=NaN,(r:any)=>r.rows[0].count++,(r:any)=>r.rows[0].time_count++]){const a=sample();mutate(a.summary.wind_rose);expect(()=>checkedRose(climateViewModel(a))).toThrow();}});
 it('captures seasonal membership, original point and counts in an independent SVG with its colored key',()=>{const a=sample(),vm=climateViewModel(a,'season'),r=checkedRose(vm)!,element={viewBox:{baseVal:{width:190,height:178}},closest:()=>null,getAttribute:()=> '冬',innerHTML:climateRosePlot(vm,0)} as unknown as SVGSVGElement;const result=createWindExport(vm,'rose',[element],{mode:'wind',scale:'all',page:0,background:true,legend:rosePointLabel(r),keySvg:roseLegend(r)});a.query.hours_utc=[0];expect(((result.metadata as any).query as any).hours_utc).toBeUndefined();expect(result.metadata.background).toBe(false);expect((result.metadata as any).grain).toBe('season');expect(((result.metadata as any).wind_rose as any).point.cell_id).toBe(285);expect(result.source).toContain('50+ m/s');expect(result.source).toContain('fixed-analysis');expect(result.source).not.toContain('p10');});
 it('hands off fixed hours and UTC member periods without translating them into a launch clock',()=>{const a=sample();a.query.hours_utc=[0,18];const interest=climateInterest(a,{schema:'balloon.climate-view/1',interest_grain:'season',interest_period_id:0});expect(interest.period.member_timebin_ids).toEqual([0,1,2,3,22,23]);expect(interest.hours_utc).toEqual([0,18]);expect(interest.label).toContain('原放球時刻は別');expect(readHistoricalInterest({historicalInterest:interest})).toEqual(interest);const view=mergeHistoricalView({historicalInterest:interest},{detail:true,selectionContext:{label:'選択試行'}});expect(readHistoricalInterest(JSON.parse(JSON.stringify(view)))).toEqual(interest);expect(readHistoricalInterest({historicalInterest:{...interest,period:{...interest.period,member_timebin_ids:[0,0]}}})).toBeUndefined();});
});

// Optional finite integration probe: externally supplied real artifacts, never checked in.
const realDirectory=process.env.BALLOON_CLIMATE_SAMPLE_DIR;
describe.skipIf(!realDirectory)('received real summary projection (finite supplied DB)',()=>{
 for(const file of ['summary-full.json','summary-hours.json'])it(file,()=>{const summary=JSON.parse(readFileSync(join(realDirectory!,file),'utf8'));const a={schema:'balloon.climate.analysis-artifact/1',analysis_id:'external-probe',query:summary.query,query_hash:summary.provenance.query_hash,result_hash:summary.provenance.result_hash,created_at:'probe',summary} as ClimateArtifact;for(const grain of climateGrains(a)){const vm=climateViewModel(a,grain as ClimateGrain);expect(vm.annualPeriods.length).toBe(grain==='half'?24:grain==='month'?12:4);expect(vm.levels.length).toBe(file==='summary-full.json'?38:20);expect(meanProfilePlot(vm,0)).toContain('data-profile="mean"');const rose=checkedRose(vm);if(file==='summary-full.json'){expect(rose!.point.cell_id).toBe(285);expect(climateRosePlot(vm,0)).toContain('data-rose="true"');}else expect(rose).toBeNull();}});
});

describe('prepared SVG link lifecycle without assuming browser file receipt',()=>{
 it('retains the previous generated link through failure, replaces only after generation succeeds, and cleans up once',()=>{
  const anchor={hidden:false,href:'',download:'',textContent:'',title:'',onclick:null as any,removeAttribute:(name:string)=>{if(name==='href')anchor.href='';}},note={textContent:''},conditions={textContent:'',hidden:false};
  const create=vi.spyOn(URL,'createObjectURL').mockReturnValueOnce('blob:first').mockImplementationOnce(()=>{throw Error('allocation failed');}).mockReturnValueOnce('blob:next'),revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});
  vi.useFakeTimers();
  try{const link=createPreparedWindDownload(anchor as unknown as HTMLAnchorElement,note as HTMLElement,conditions as HTMLElement);expect(anchor.hidden).toBe(true);link.begin();expect(revoke).not.toHaveBeenCalled();expect(link.publish('<svg>first</svg>','first.svg','冬 / fixed1','UTC 00/06/12/18 / 300 hPa')).toBe(true);expect(anchor.href).toBe('blob:first');expect(anchor.hidden).toBe(false);expect(note.textContent).toContain('準備しました');expect(note.textContent).not.toContain('保存しました');vi.advanceTimersByTime(3600_000);expect(revoke).not.toHaveBeenCalled();anchor.onclick();expect(note.textContent).toContain('保存を要求');expect(anchor.href).toBe('blob:first');link.begin();expect(note.textContent).toContain('前回生成分');expect(()=>link.publish('<svg>bad</svg>','bad.svg','bad','UTC 00 / 1000 hPa')).toThrow('allocation failed');link.failed();expect(anchor.href).toBe('blob:first');expect(anchor.download).toBe('first.svg');expect(note.textContent).toContain('前回生成分');expect(revoke).not.toHaveBeenCalled();link.publish('<svg>next</svg>','next.svg','春 / fixed2','UTC 00 / 1000 hPa');expect(anchor.href).toBe('blob:next');expect(revoke.mock.calls).toEqual([['blob:first']]);link.dispose();link.dispose();expect(revoke.mock.calls).toEqual([['blob:first'],['blob:next']]);expect(anchor.hidden).toBe(true);expect(anchor.href).toBe('');expect(anchor.onclick).toBeNull();expect(link.publish('<svg/>','late.svg','late','late')).toBe(false);expect(create).toHaveBeenCalledTimes(3);}finally{vi.useRealTimers();create.mockRestore();revoke.mockRestore();}
 });
 it('keeps visible generated population and plane with an old rose link after current hours change or replacement fails',()=>{const a=sample(),vm=climateViewModel(a,'season'),output=createWindExport({...vm,populationLabel:vm.populationLabel.replace(/対象\d+\/\d+元格子/,'風配は代表1元格子')},'rose',[],{mode:'wind',scale:'all',page:0,background:false,legend:'fixed'}),anchor={hidden:true,href:'',onclick:null as any,removeAttribute:()=>{}} as unknown as HTMLAnchorElement,note={textContent:''} as HTMLElement,conditions={textContent:'',hidden:true} as HTMLElement,link=createPreparedWindDownload(anchor,note,conditions),create=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:whole-day'),revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});try{link.publish(output.source,'full.svg','風配 / 固定A',windDownloadConditions(output.metadata));const captured=conditions.textContent;expect(captured).toContain('生成時の条件：');expect(captured).toContain('保存気象集計');expect(captured).toContain('2016');expect(captured).toContain('UTC 00/06/12/18時');expect(captured).toContain('代表1元格子');expect(captured).toContain('300 hPa');expect(captured).toContain('風配の元格子 '+(output.metadata as any).wind_rose.point.cell_id);const priorPoint=(output.metadata as any).wind_rose.point;(output.metadata as any).wind_rose.point={...priorPoint,cell_id:999};expect(windDownloadConditions(output.metadata)).toContain('風配の元格子 999');expect(conditions.textContent).toBe(captured);expect(conditions.hidden).toBe(false);output.metadata.populationLabel='新しいUTC 00時の対象';output.metadata.selectedLevel={...output.metadata.selectedLevel,pressure:1000};link.begin();link.failed();(anchor.onclick as any)();expect(conditions.textContent).toBe(captured);expect(anchor.href).toBe('blob:whole-day');expect(create).toHaveBeenCalledOnce();expect(revoke).not.toHaveBeenCalled();expect(windDownloadConditions({...output.metadata,view:'profile'})).not.toContain('1000 hPa');expect(windDownloadConditions({...output.metadata,view:'spatial'})).toContain('1000 hPa');}finally{link.dispose();create.mockRestore();revoke.mockRestore();}});
 it('does not manufacture a link or success state before the first generation succeeds',()=>{const anchor={hidden:false,onclick:null,removeAttribute:()=>{}} as unknown as HTMLAnchorElement,note={textContent:''} as HTMLElement,conditions={textContent:'',hidden:false} as HTMLElement,link=createPreparedWindDownload(anchor,note,conditions);link.begin();link.failed();expect(anchor.hidden).toBe(true);expect(note.textContent).toContain('準備を完了できません');expect(note.textContent).not.toContain('前回生成分');link.dispose();});
});


describe('raw wind-rose calm counts',()=>{
 function withCalm(){const a=sample(),r=a.summary.wind_rose;if(!r?.available)throw Error('fixture');r.calm_counts=a.summary.population.timebins.map(p=>({timebin_id:p.timebin_id,count:p.n_analyses_expected/4,time_count:p.n_analyses_expected,frequency:.25}));for(const row of r.rows)if(row.sector===0&&row.speed_class===0){row.count=0;row.frequency=0;}return a;}
 it('counts directionless calm in the denominator without drawing it as north, preserving shared radius and original point',()=>{
  const a=withCalm(),r=a.summary.wind_rose;if(!r?.available)throw Error('fixture');r.native_hours_utc=[0,18];a.query.hours_utc=[0,18];const vm=climateViewModel(a),checked=checkedRose(vm)!;
  expect(rosePopulationLabel(checked)).toBe('UTC 00/18時・代表地点の経験頻度');expect(roseMethod(checked)).toContain('方向を持たず');expect(roseLegend(checked)).toContain('静穏（0 m/s）は方向なし');expect(roseScale(vm)).toBe(80);
  const svg=climateRosePlot(vm,0);expect(svg).toContain('静穏1/4');expect(svg).not.toContain('data-rose-bin="0"');expect(svg).toContain('data-count="3"');expect(rosePointLabel(checked)).toContain('285');
  const out=createWindExport(vm,'rose',[],{mode:'wind',scale:'all',page:0,background:false,legend:roseMethod(checked),keySvg:roseLegend(checked)});r.calm_counts![0].count=0;expect((out.metadata as any).wind_rose.calm_counts[0].count).toBe(1);
 });
 it('shows an all-calm period as zero directional bars and retains its actual sample count',()=>{
  const a=withCalm(),r=a.summary.wind_rose;if(!r?.available)throw Error('fixture');for(const c of r.calm_counts!){c.count=c.time_count;c.frequency=1;}for(const row of r.rows){row.count=0;row.frequency=0;}const vm=climateViewModel(a);expect(checkedRose(vm)).not.toBeNull();expect(roseScale(vm)).toBe(10);expect(climateRosePlot(vm,0)).toContain('静穏4/4');expect(climateRosePlot(vm,0)).not.toContain('data-rose-bin');
 });
 it.each([
  ['missing period',(r:any)=>r.calm_counts.pop()],['duplicate period',(r:any)=>r.calm_counts[1]={...r.calm_counts[0]}],
  ['fraction mismatch',(r:any)=>r.calm_counts[0].frequency=.5],['wrong denominator',(r:any)=>r.calm_counts[0].time_count++],
  ['double-counted calm',(r:any)=>{r.rows[0].count=1;r.rows[0].frequency=.25;}],['negative calm',(r:any)=>r.calm_counts[0].count=-1],['different hours',(r:any)=>r.native_hours_utc=[0,18]],
 ])('rejects %s instead of normalizing inconsistent calm data',(_name,mutate)=>{const a=withCalm();mutate(a.summary.wind_rose);expect(()=>checkedRose(climateViewModel(a))).toThrow();});
 it('retains legacy no-separate-calm interpretation when the field is absent',()=>{const vm=climateViewModel(sample()),r=checkedRose(vm)!;expect(roseLegend(r)).toContain('静穏の独立区分なし');expect(climateRosePlot(vm,0)).not.toContain('静穏');});
});
