export type ClimateBounds={west:number;east:number;south:number;north:number};
export type ClimateGrain='half'|'month'|'season';
export type ClimateAnnualGrain=ClimateGrain|'quarter';
export type ClimateAnnualQuarters={schema:'climate-annual-quarters/1';date_convention:'UTC';timebins:ClimatePeriod[];annual:ClimateAnnualRow[];display_scales:ClimateScales;calendar_definition:{version:string;description:string}};
export const climateGrainLabel:Record<ClimateGrain,string>={half:'半月',month:'月',season:'季節'};
export const climateHours=[0,6,12,18];
export type ClimateQuery={source_id:string;level_id:number;bounds:ClimateBounds|null;grain:'half';hours_utc?:number[];rose_cell_id?:number};
export type ClimateLevel={level_id:number;level_hpa:number;isa_alt_m:number;alt_geom_mean_m:number|null;alt_geom_min_m:number|null;alt_geom_max_m:number|null};
export type ClimateCell={cell_id:number;lat:number;lon:number;gauss_weight:number};
export type ClimatePeriod={timebin_id:number;month?:number;months?:number[];bin?:number;start_day?:number;end_day_min?:number;end_day_max?:number;n_days_total:number;n_analyses_expected:number;label?:string;member_timebin_ids?:number[]};
export type ClimateWeighting='gaussian-area-equal-times'|'spherical-area-equal-times';
export type ClimateDescriptor={provider?:string;label?:string;weighting?:ClimateWeighting;source_id:string;dataset_sha256:string;bounds:ClimateBounds;native_grid:ClimateCell[];native_grid_count:number;levels:ClimateLevel[];timebins:ClimatePeriod[];capabilities:{years_fixed:number[];date_convention:string;native_hours_utc:number[];grain:string;annual:boolean;spatial:boolean;[key:string]:unknown};attribution:unknown;[key:string]:unknown};
export type ClimateMoment={mean_u:number;mean_v:number;mean_speed:number;from_deg:number|null;time_count:number;valid_time_count:number;missing_time_count:number};
export type ClimateAnnualRow=ClimateMoment&{timebin_id:number;level_id:number;pooled_constancy:number|null;spatial_mean_speed_range:number;cell_count:number};
export type ClimateSpatialRow=ClimateMoment&{timebin_id:number;cell_id:number;constancy:number|null};
export type ClimateScales={all_level_cell_mean_speed_max:number;selected_level_cell_mean_speed_max:number;annual_mean_speed_max:number;spatial_mean_speed_range_max:number;[key:string]:unknown};
export type ClimateWindRose={available:false;reason:string}|{available:true;point:Pick<ClimateCell,'cell_id'|'lat'|'lon'>;point_in_selected_region:boolean;level_id:number;sectors:{sector:number;centre_deg:number;lo_deg?:number;hi_deg?:number;wraps_north?:boolean;compass_16:string}[];speed_classes:{speed_class:number;lo_ms:number;hi_ms:number|null;label:string}[];rows:{timebin_id:number;sector:number;speed_class:number;count:number;time_count:number;frequency:number}[];native_hours_utc:number[];date_convention:string;definition:string;calm_counts?:{timebin_id:number;count:number;frequency:number;time_count:number}[]};
export type ClimateGrainSummary={timebins:ClimatePeriod[];annual:ClimateAnnualRow[];spatial_rows:ClimateSpatialRow[];display_scales:ClimateScales;wind_rose?:ClimateWindRose};
export type ClimateProfileRow={level_id:number;p10:number;p90:number;half_medians:[number,number]};
export type ClimateProfileMonth={month:number;expected_time_count:number}&({available:false;reason:'month_not_acquired'}|{available:true;time_count:number;half_time_counts:[number,number];cell_count:number;sample_count:number;rows:ClimateProfileRow[]});
export type ClimateMonthlyProfiles={schema:'climate-month-profiles/1';method:'inverted_cdf';weighting:ClimateWeighting;date_convention:'UTC';population:{years_fixed:[number,number];hours_utc:number[];selected_cell_ids:number[];level_ids:number[]};months:ClimateProfileMonth[];provenance:{bundle_sha256:string;manifest_schema:'balloon.climate.raw-months/1'|'balloon.wind-samples/1';numpy_version:string}};
export type ClimateSummary={schema:'climate-summary/1';source:ClimateDescriptor;query:ClimateQuery;levels:ClimateLevel[];population:{timebins:ClimatePeriod[];selected_cell_ids:number[];selected_cell_count:number;native_grid_count:number;years_fixed:number[];date_convention:string;native_hours_utc:number[];spatial_weighting:string;count_definition:string;[key:string]:unknown};annual:(ClimateMoment&{timebin_id:number;level_id:number;pooled_constancy:number|null;spatial_mean_speed_range:number;cell_count:number})[];spatial:{level_id:number;grid:ClimateCell[];rows:(ClimateMoment&{timebin_id:number;cell_id:number;constancy:number|null})[]};display_scales:{all_level_cell_mean_speed_max:number;selected_level_cell_mean_speed_max:number;annual_mean_speed_max:number;spatial_mean_speed_range_max:number;[key:string]:unknown};provenance:{query_hash:string;result_hash:string;[key:string]:unknown};annual_quarters?:ClimateAnnualQuarters;summaries_by_grain?:Partial<Record<'month'|'season',ClimateGrainSummary>>;wind_rose?:ClimateWindRose;monthly_profiles?:ClimateMonthlyProfiles};
export type ClimateArtifact={schema:'balloon.climate.analysis-artifact/1';analysis_id:string;query:ClimateQuery;query_hash:string;result_hash:string;created_at:string;summary:ClimateSummary};
export type ClimateView={schema:'balloon.climate-view/1';draft_query?:ClimateQuery;applied?:{analysis_id:string;source_id:string;dataset_sha256:string;query_hash:string;result_hash:string};view?:'annual'|'monthly'|'spatial'|'landing';annual_grain?:ClimateAnnualGrain;spatial_grain?:ClimateGrain;monthly_grain?:ClimateGrain;monthly_mode?:'profile'|'rose'|'quantiles';monthly_page?:number;spatial_mode?:'wind'|'steady';spatial_scale?:'all'|'level';spatial_page?:number;interest_grain?:ClimateGrain;interest_period_id?:number};
/** All four hours retain the original query bytes and request binding. */
export function normalizeClimateQuery(q:ClimateQuery):ClimateQuery {const next={...q};if(q.rose_cell_id===undefined)delete next.rose_cell_id;if(q.hours_utc===undefined)delete next.hours_utc;else{const hours=[...new Set(q.hours_utc)].sort((a,b)=>a-b);if(hours.length===4&&hours.every((h,i)=>h===climateHours[i]))delete next.hours_utc;else next.hours_utc=hours;}return next;}
export function selectedClimateHours(q:ClimateQuery):number[]{return q.hours_utc??climateHours;}
export function climateHoursLabel(q:ClimateQuery):string{return 'UTC '+selectedClimateHours(q).map(h=>String(h).padStart(2,'0')).join('/')+'時';}
export function climateYearsLabel(years:number[]):string {if(!years.length)return '対象年未記載';const first=Math.min(...years),last=Math.max(...years);return first===last?`${first}年`:`${first}–${last}年`;}
export function climateSourceLabel(value:unknown):string {const d=value&&typeof value==='object'?value as {label?:unknown;provider?:unknown;profile?:unknown}:{};return typeof d.label==='string'&&d.label?d.label:typeof d.provider==='string'&&d.provider?`${d.provider} 保存集計`:d.profile==='provided-hokkaido-2016-2025-half-v1'?'提供JRA-3Q期間集計':'保存気象集計';}
export function climateWeightLabel(weight:unknown):string {return weight==='spherical-area-equal-times'?'球面格子面積重み（緯度のcosに比例）':['gaussian-area-equal-times','provided_gaussian_grid_weights','gauss'].includes(String(weight))?'Gaussian面積重み':'資料に記録された面積重み';}
export function climateHourSupport(d:ClimateDescriptor):string {const supported=d.levels.filter(l=>hourLevelIds(d).includes(l.level_id)),pressures=supported.map(l=>l.level_hpa);if(!d.capabilities.hour_filter||!pressures.length)return 'この資料は全4時刻の集計に対応します。';const lo=Math.min(...pressures),hi=Math.max(...pressures),range=lo===hi?`${hi} hPa`:`${hi}–${lo} hPa`;return `時刻を絞る集計は${range}の${supported.length}面。`+(d.capabilities.wind_rose_hour_filter===true?'風配も選択したUTC時刻で集計します。':'風配は全4時刻のみです。');}
export function climatePeriodLabel(p:ClimatePeriod):string{return p.label??`${p.month}月${p.bin===1?'前半':'後半'}`;}
export function hourLevelIds(d:ClimateDescriptor):number[]{return Array.isArray(d.capabilities.hour_level_ids)?d.capabilities.hour_level_ids.filter((x:unknown)=>Number.isInteger(x)):[];}
export function queryKey(value:unknown):string {if(Array.isArray(value))return '['+value.map(queryKey).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+queryKey(v)).join(',')+'}';return JSON.stringify(value);}
export function queryIssue(q:ClimateQuery,d:ClimateDescriptor):string|null {
 if(q.source_id!==d.source_id)return '選択した資料と集計条件が一致しません。';
 if(q.rose_cell_id!==undefined&&(d.capabilities.wind_rose_point_select!==true||!Number.isInteger(q.rose_cell_id)||!d.native_grid.some(c=>c.cell_id===q.rose_cell_id)))return 'この資料で選択できる風配の元格子点を指定してください。';
 if(q.grain!=='half'||!d.levels.some(l=>l.level_id===q.level_id))return 'この資料が対応していない時期区分または気圧面です。';
 if(q.hours_utc&&(!q.hours_utc.length||q.hours_utc.some(h=>!climateHours.includes(h))))return '気象有効時刻をUTC 00 / 06 / 12 / 18時から一つ以上選んでください。';
 if(normalizeClimateQuery(q).hours_utc&&!hourLevelIds(d).includes(q.level_id))return climateHourSupport(d)+' 対応する気圧面を明示的に選ぶか、全時刻へ戻してください。';
 const b=q.bounds??d.bounds;if(!Object.values(b).every(Number.isFinite)||b.west>b.east||b.south>b.north)return '範囲は有限値で、西≦東・南≦北となるよう指定してください。';
 if(b.west<d.bounds.west||b.east>d.bounds.east||b.south<d.bounds.south||b.north>d.bounds.north)return '指定範囲が元格子中心の範囲を超えています。';
 if(!d.native_grid.some(c=>c.lon>=b.west&&c.lon<=b.east&&c.lat>=b.south&&c.lat<=b.north))return '範囲内に元格子の中心がありません。';return null;
}
export function defaultClimateQuery(d:ClimateDescriptor):ClimateQuery {const l=d.levels.find(l=>l.level_hpa===300)??d.levels[0];if(!l)throw new Error('資料の気圧面がありません。');return {source_id:d.source_id,level_id:l.level_id,bounds:null,grain:'half'};}
export function validateClimateArtifact(a:ClimateArtifact):ClimateArtifact {if(a?.schema!=='balloon.climate.analysis-artifact/1'||a.summary?.schema!=='climate-summary/1'||!a.analysis_id)throw new Error('保存気象集計の形式を読めません。');if(a.query_hash!==a.summary.provenance.query_hash||a.result_hash!==a.summary.provenance.result_hash||queryKey(a.query)!==queryKey(a.summary.query))throw new Error('固定集計の識別情報と本文が一致しません。');return a;}
export function climateError(error:unknown):string {if(error instanceof Error&&error.name==='AbortError')return '応答待ちの上限時間を超えました。固定結果は保持しています。再試行で同じ要求の受付を確認できます。';const m=error instanceof Error?error.message:String(error);const known:Record<string,string>={CLIMATE_UNAVAILABLE:'実風統計DBを現在利用できません。保存済み集計は参照IDから読み直せます。',CLIMATE_CORRUPT:'保存集計の整合性を確認できません。部分的な図へ置き換えず、固定結果を保持します。',CLIMATE_STORAGE:'気象集計の保存先を利用できません。表示中の結果は保持しています。',CLIMATE_DATABASE:'実DBの読取りに失敗しました。部分的な集計は表示していません。',CLIMATE_NOT_FOUND:'指定した保存集計がありません。自動で再集計は行いません。',CLIMATE_SOURCE_CHANGED:'元DBが登録時から変化したか、利用できません。保存済みの図は保持しています。',CLIMATE_EMPTY_REGION:'範囲内に元格子の中心がありません。',CLIMATE_BOUNDS:'範囲がこの資料の元格子中心範囲を超えています。',CLIMATE_COUNTS:'欠測または時刻数の不一致を検出したため、部分的な結果は表示しません。',CLIMATE_DEPENDENCY:'実気象集計に必要なDuckDBをサービス側で利用できません。',CLIMATE_UNSUPPORTED:'この資料では指定した操作に対応していません。'};const k=Object.keys(known).find(k=>m.includes(k));return k?known[k]:m;}
