import {describe,it,expect} from 'vitest';
import {historicalInput,historicalMatches,historicalSelectionMatches,sourceWindowIssue} from './historicalDomain';
import {projectForAnalysis,readHistoricalInterest,mergeHistoricalView} from './historicalWorkspace';
import type {Candidate,Project,WeatherSource} from './domain';
const candidate:Candidate={id:'H',label:'原日時試算',revision:1,analysis_mode:'historical_windows',weather_source_id:'historical-a',config:{schema:'balloon.flight.config/1',launch:{time_utc:'2024-01-01T00:00:00Z',latitude_deg:43,longitude_deg:141.5,altitude_m:100},ascent:{mode:'constant_speed',speed_m_s:5},burst:{mode:'altitude',altitude_m:30000},descent:{mode:'rated_speed',reference_speed_m_s:5},integration:{max_duration_s:14400}}};
const window={window_id:'w',label:'日1',weather_source_id:'historical-a',launch_time_utc:'2024-07-01T01:17:13Z',reason:'明示比較'};
const source:WeatherSource={id:'historical-a',default_config:null,time_kind:'analysis_valid_utc',valid_times_utc:['2024-07-01T00:00:00Z','2024-07-01T06:00:00Z'],bounds:{lat:[40,46],lon:[139.5,148]}};
describe('original-date flight bridge',()=>{
 it('preserves a recognized legacy climate interest across detail selection and saving without changing fixed plan provenance',()=>{
  const interest={schema:'balloon.climate-flight-interest/1',analysis_id:'a',query_hash:'q',result_hash:'r',dataset_sha256:'d',label:'1月前半・北海道',bounds:{south:40,north:46,west:139,east:148},period:{timebin_id:1,month:1,bin:1}},fixed={draft:{windows:[window],reason:'固定理由',selection_context:structuredClone(interest)},plan_id:'fixed-plan'},view={selectionContext:interest,historicalPlans:{H:fixed}};
  const detail=mergeHistoricalView(view,{detail:true,selectionContext:{label:'全予定試行',resultId:'snapshot:case'}}),saved=JSON.parse(JSON.stringify(detail));
  expect(readHistoricalInterest(saved)).toEqual(interest);expect(saved.selectionContext.label).toBe('全予定試行');expect(detail.historicalPlans.H).toBe(fixed);expect(saved.historicalPlans.H.draft.selection_context).toEqual(interest);expect(view).not.toHaveProperty('historicalInterest');
  const next=mergeHistoricalView(saved,{selectionContext:{label:'指定領域への着地',resultId:'snapshot:case'}});expect(readHistoricalInterest(next)).toEqual(interest);
 });
 it('never upgrades an ordinary sample-selection label or an unidentifiable legacy object into climate interest',()=>{
  for(const selectionContext of [{label:'全予定試行',resultId:'s'},{label:'1月前半・北海道'},{schema:'balloon.climate-flight-interest/1',label:'missing provenance'}]){
   const view=mergeHistoricalView({selectionContext},{detail:true});expect(readHistoricalInterest(view)).toBeUndefined();expect(view).not.toHaveProperty('historicalInterest');expect(view.selectionContext).toEqual(selectionContext);
  }
 });
 it('detects window edits without treating equivalent UTC strings or runtime metadata as edits',()=>{const draft={windows:[window],reason:'日時比較',selection_context:{analysis_id:'a'}};const saved={weather_windows:[{...window,launch_time_utc:'2024-07-01T01:17:13+00:00',availability:'registered'}],sampling:{reason:'日時比較'},selection_context:{analysis_id:'a'}} as any;expect(historicalSelectionMatches(draft,saved)).toBe(true);expect(historicalSelectionMatches({...draft,windows:[{...window,launch_time_utc:'2024-07-01T01:17:14Z'}]},saved)).toBe(false);expect(historicalSelectionMatches({...draft,windows:[]},saved)).toBe(false);expect(historicalSelectionMatches({...draft,selection_context:{analysis_id:'b'}},saved)).toBe(false);expect(historicalSelectionMatches(undefined,saved)).toBe(true);});
 it('retains original seconds and does not invent a sampling distribution',()=>{const v=historicalInput(candidate,{windows:[window],reason:'手で選んだ日時',selection_context:{analysis_id:'fixed'}});expect(v.windows[0].launch_time_utc).toBe(window.launch_time_utc);expect(v).not.toHaveProperty('sampling');expect(v.selection_context.analysis_id).toBe('fixed');});
 it('shows missing, temporal and spatial support before calculation',()=>{expect(sourceWindowIssue(window,candidate.config,[])).toContain('未登録');expect(sourceWindowIssue(window,candidate.config,[source])).toBeNull();expect(sourceWindowIssue({...window,launch_time_utc:'2024-07-01T03:00:00Z'},candidate.config,[source])).toContain('最大計算時間');expect(sourceWindowIssue(window,{...candidate.config,launch:{...candidate.config.launch,latitude_deg:34}},[source])).toContain('領域外');});
 it('compares common vehicle while launch UTC belongs to each window',()=>{const changed=structuredClone(candidate);changed.config.launch.time_utc='2025-01-01T00:00:00Z';expect(historicalMatches(changed,candidate.config)).toBe(true);changed.config.launch.longitude_deg=140;expect(historicalMatches(changed,candidate.config)).toBe(false);});
 it('projects both modes without deleting the complete saved project or old result refs',()=>{const project:Project={schema:'balloon.project/1',title:'共通',candidates:[candidate,{...candidate,id:'F',analysis_mode:'forecast'}],compare_run_ids:[],compare_results:[{kind:'ensemble_case',case_id:'H',ensemble_id:'a',snapshot_id:'s'},{kind:'ensemble_case',case_id:'removed-history',ensemble_id:'b',snapshot_id:'s2'},{kind:'ensemble_case',case_id:'F',ensemble_id:'c',snapshot_id:'s3'}],ui_state:{historicalCandidateIds:['H','removed-history']}};expect(projectForAnalysis(project,[],true).compare_results).toHaveLength(2);expect(projectForAnalysis(project,[],false).candidates.map(c=>c.id)).toEqual(['F']);expect(project.candidates).toHaveLength(2);expect(project.compare_results).toHaveLength(3);});
});
