import {claimWriteLease,releaseWriteLease} from './writeLease';
import {setServiceIdentity} from './serviceIdentity';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {createJobObserver} from './jobObservation';
const {h,normal}=vi.hoisted(()=>({h:{current:null as any},normal:{health:vi.fn(),weather:vi.fn(),project:vi.fn(),runs:vi.fn(),run:vi.fn(),result:vi.fn(),start:vi.fn(),save:vi.fn(),inventories:vi.fn(),acquisitions:vi.fn(),weatherStatus:vi.fn(),acquisition:vi.fn(),refreshInventory:vi.fn(),cancelAcquisition:vi.fn(),retryAcquisition:vi.fn(),acquireWeather:vi.fn(),weatherPlan:vi.fn()}}));
vi.mock('react',()=>({useRef:(v:any)=>h.current.ref(v),useState:(v:any)=>h.current.state(v),useEffect:(f:any,d:any[])=>h.current.effect(f,d),useReducer:(f:any,a:any,init:any)=>h.current.reducer(f,a,init)}));
vi.mock('./api',async()=>({...await vi.importActual<any>('./api'),api:normal}));
import {request,readRequest,WriteResponseUnknown} from './api';
import {acquisitionRequest} from './weatherAcquisition';
import {putSubmission} from './submissionLedger';
import {useWorkspace} from './useWorkspace';
import {WeatherPreparation,InventoryObservation} from './WeatherPreparation';
function harness(fn:()=>any){let cursor=0;const slots:any[]=[],effects:any[]=[],cleanups:any[]=[];const owner={ref:(v:any)=>{const i=cursor++;return slots[i]??(slots[i]={current:v});},state:(v:any)=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return [slots[i],(n:any)=>{slots[i]=typeof n==='function'?n(slots[i]):n;}];},reducer:(f:any,v:any,init:any)=>{const [s,set]=owner.state(()=>init(v));return [s,(a:any)=>set((old:any)=>f(old,a))];},effect:(f:any,d:any[])=>{const i=cursor++;if(!slots[i]||d.some((v,j)=>!Object.is(v,slots[i][j]))){slots[i]=d;effects.push(()=>{cleanups[i]?.();cleanups[i]=f();});}}};return {render:()=>{cursor=0;h.current=owner;const r=fn();effects.splice(0).forEach(f=>f());return r;},unmount:()=>cleanups.forEach(f=>f?.())};}
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
const deferred=()=>{let resolve!:(v:any)=>void,reject!:(e:any)=>void;const promise=new Promise<any>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const nodes=(node:any):any[]=>Array.isArray(node)?node.flatMap(nodes):node&&typeof node==='object'?[node,...nodes(node.props?.children)]:[];
const text=(node:any):string=>Array.isArray(node)?node.map(text).join(''):node&&typeof node==='object'?text(node.props?.children):node===null||node===undefined||typeof node==='boolean'?'':String(node);
const click=(tree:any,label:string)=>{const node=nodes(tree).find(n=>n.type==='button'&&text(n)===label);expect(node,label).toBeTruthy();return node.props.onClick();};
const config:any={launch:{time_utc:'2026-09-30T01:17:13Z',latitude_deg:34,longitude_deg:135},ascent:{mode:'constant_speed',speed_m_s:5},burst:{mode:'altitude',altitude_m:30000},descent:{mode:'rated_speed'}};
const candidate:any={id:'A',label:'original',revision:1,weather_source_id:'w',config};
const savedProject:any={schema:'balloon.project/1',title:'p',candidates:[candidate],compare_run_ids:['old']};
const run=(id='new',state='running',available=false)=>({run_id:id,candidate_id:'A',label:'A',state,result_available:available});
const result=(id='new')=>({run_id:id,result:{status:'landed',config},weather_snapshot:{id:'w'}});
beforeEach(async()=>{releaseWriteLease();vi.stubGlobal('navigator',{locks:{request:(_name:any,_options:any,callback:any)=>Promise.resolve(callback({name:'test-lock'}))}});await claimWriteLease();setServiceIdentity('test-instance');vi.useFakeTimers();const storage=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)});vi.stubGlobal('window',{addEventListener:vi.fn(),removeEventListener:vi.fn()});Object.values(normal).forEach(f=>f.mockReset());normal.health.mockResolvedValue({instance_id:'test-instance',status:'ok',flight_execution:{available:true,restart_required:false,queued_policy:'preserved_without_automatic_resubmission'}});});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
describe('read-only bounded observation',()=>{
 it('does not begin a read after disposal wins its deferred start',async()=>{const read=vi.fn(),o=createJobObserver({read,accept:vi.fn(),observe:vi.fn(),active:()=>true,isCurrent:()=>true});const p=o.refresh('j');o.dispose();await p;expect(read).not.toHaveBeenCalled();});
 it('retains confirmed state through a failed read and retries with bounded backoff',async()=>{let value='running',observation:any;const read=vi.fn().mockResolvedValueOnce('running').mockRejectedValueOnce(new Error('offline')).mockResolvedValue('completed'),accept=vi.fn((_id,v)=>{value=v;});const o=createJobObserver({read,accept,active:()=>value==='running',observe:(_id,v)=>{observation=v;},isCurrent:()=>true});await o.refresh('j');const stamp=observation.lastConfirmedAt;await vi.advanceTimersByTimeAsync(900);expect(observation.unavailable).toBe(true);expect(observation.lastConfirmedAt).toBe(stamp);expect(value).toBe('running');expect(observation.nextRetryMs).toBe(1800);await vi.advanceTimersByTimeAsync(1800);expect(value).toBe('completed');expect(observation.unavailable).toBe(false);expect(observation.nextRetryMs).toBeNull();o.dispose();});
 it('deduplicates manual reads and discards a late response after disposal',async()=>{const d=deferred(),read=vi.fn((_id:string,_signal:AbortSignal)=>d.promise),accept=vi.fn(),observe=vi.fn(),o=createJobObserver({read,accept,observe,active:()=>true,isCurrent:()=>true});const a=o.refresh('j'),b=o.refresh('j');expect(a).toBe(b);await flush();const signal=read.mock.calls[0][1];o.dispose();expect(signal.aborted).toBe(true);d.resolve('late');await a;expect(accept).not.toHaveBeenCalled();});
 it('bounds a stalled GET at 20 seconds and never resends it',async()=>{const fetch=vi.fn((_url,init)=>new Promise((_a,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('aborted')))));vi.stubGlobal('fetch',fetch);const assertion=expect(readRequest('/runs/j')).rejects.toThrow('20秒');await vi.advanceTimersByTimeAsync(20000);await assertion;expect(fetch).toHaveBeenCalledOnce();});
 it('also settles when the JSON body ignores abort, and ignores that late body',async()=>{const d=deferred(),fetch=vi.fn().mockResolvedValue({ok:true,status:200,json:()=>d.promise});vi.stubGlobal('fetch',fetch);const assertion=expect(readRequest('/runs/j')).rejects.toThrow('20秒');await vi.advanceTimersByTimeAsync(20000);await assertion;expect(fetch.mock.calls[0][1].signal.aborted).toBe(true);d.resolve({state:'completed'});await flush();expect(fetch).toHaveBeenCalledOnce();});
 it('does not add an observation deadline or retry to explicit POST',async()=>{const d=deferred(),fetch=vi.fn((_url:string,_init:RequestInit)=>d.promise);vi.stubGlobal('fetch',fetch);const p=request('/runs',{method:'POST',body:'{}'});await vi.advanceTimersByTimeAsync(21000);expect(fetch).toHaveBeenCalledOnce();expect(fetch.mock.calls[0][1].signal).toBeUndefined();d.resolve({ok:true,status:202,json:async()=>({ok:true})});expect(await p).toEqual({ok:true});});
});
describe('single-run recovery preserves edited drafts and explicit result selection',()=>{
 async function setup(){normal.weather.mockResolvedValue({sources:[]});normal.project.mockResolvedValue({revision:1,project:structuredClone(savedProject)});normal.runs.mockResolvedValue({runs:[run('old','completed',true)]});normal.run.mockResolvedValue(run('old','completed',true));normal.result.mockResolvedValue(result('old'));normal.start.mockResolvedValue(run('new','queued'));const x=harness(useWorkspace);x.render();await flush();x.render();return x;}
 it('recovers run and result GET failures without POST replay or overwriting intervening edits/selection',async()=>{const x=await setup();normal.run.mockRejectedValueOnce(new Error('offline')).mockResolvedValue(run('new','completed',true));normal.result.mockRejectedValueOnce(new Error('result offline')).mockResolvedValue(result());await x.render().start(candidate);expect(x.render().observations.new.unavailable).toBe(true);expect(x.render().pending.A).toContain('未確認');x.render().updateCandidate({...candidate,label:'edited',revision:2});x.render();x.render().claimSelection('A');await vi.advanceTimersByTimeAsync(1800);expect(x.render().observations.new.unavailable).toBe(true);await vi.advanceTimersByTimeAsync(3600);const w=x.render();expect(w.observations.new.unavailable).toBe(false);expect(w.results.new.run_id).toBe('new');expect(w.project.candidates[0].label).toBe('edited');expect(w.project.compare_run_ids).toEqual(['old']);expect(w.pending.A).toBeUndefined();expect(normal.start).toHaveBeenCalledOnce();expect(normal.project).toHaveBeenCalledOnce();x.unmount();});
 it('terminal physical failure stops automatic observation but remains manually readable',async()=>{const x=await setup();normal.run.mockResolvedValue({...run('new','failed'),error:{code:'INPUT_ERROR'}});await x.render().start(candidate);const w=x.render();expect(w.runs.find((r:any)=>r.run_id==='new').state).toBe('failed');expect(w.observations.new.unavailable).toBe(false);expect(w.observations.new.nextRetryMs).toBeNull();expect(w.pending.A).toBeUndefined();await w.refreshRun('new');expect(normal.start).toHaveBeenCalledOnce();expect(x.render().project.compare_run_ids).toEqual(['old']);x.unmount();});
 it('aborts and ignores a prior project observation when saved state is explicitly reloaded',async()=>{const x=await setup(),d=deferred();normal.run.mockReturnValueOnce(d.promise);const work=x.render().start(candidate);await flush();const signal=normal.run.mock.calls.at(-1)![1];normal.run.mockResolvedValue(run('old','completed',true));normal.result.mockResolvedValue(result('old'));await x.render().load();expect(signal.aborted).toBe(true);d.resolve(run('new','failed'));await work;expect(x.render().observations.new).toBeUndefined();expect(x.render().runs.some((r:any)=>r.run_id==='new')).toBe(false);x.unmount();});
 it.each(['cancelled','completed'])('restores all older active runs behind a newer %s without transferring result ownership',async latestState=>{
  const x=await setup(),older={...run('older','running'),created_at:'2026-09-30T00:00:00Z'},middle={...run('middle','queued'),created_at:'2026-09-30T00:01:00Z'},latest={...run('latest',latestState,latestState==='completed'),created_at:'2026-09-30T00:02:00Z'};
  const states:Record<string,any>={old:run('old','completed',true),older,middle,latest};
  normal.runs.mockResolvedValue({runs:Object.values(states)});normal.run.mockImplementation(async id=>states[id]);normal.result.mockImplementation(async id=>result(id));
  await x.render().load();await flush();let w=x.render();expect(w.observations.older).toBeTruthy();expect(w.observations.middle).toBeTruthy();expect(w.latestRun.A).toBe('latest');expect(w.pending.A).toBe('待機中');expect(w.project.compare_run_ids).toEqual(['old']);
  states.middle={...middle,state:'failed'};await w.refreshRun('middle');w=x.render();expect(w.pending.A).toBe('計算中');expect(w.latestRun.A).toBe('latest');
  states.older={...older,state:'completed',result_available:true};await w.refreshRun('older');w=x.render();expect(w.pending.A).toBeUndefined();expect(w.results.older.run_id).toBe('older');expect(w.project.compare_run_ids).toEqual(['old']);expect(w.latestRun.A).toBe('latest');expect(normal.start).not.toHaveBeenCalled();x.unmount();
 });
});
describe('weather acquisition observation and explicit forecast choice',()=>{
 const job:any={acquisition_id:'j',plan_id:'p',state:'running',attempt:1,progress:{phase:'downloading',completed_files:1,total_files:3,bytes_downloaded:100,bytes_reused:0},weather_source_id:null,reused:false,cancellable:true,retryable:false,error:null};
 const form:any={inventoryId:'i',runUtc:'2026-09-30T00:00:00Z',fixedRun:'',latitude:34,longitude:135,halfWidth:50,halfHeight:50,maxMB:50,memoryMB:256,targetIds:['A']};
 async function setup(){normal.inventories.mockResolvedValue({inventories:[]});normal.acquisitions.mockResolvedValue({acquisitions:[job]});normal.weatherStatus.mockResolvedValue({dependencies:{available:true,missing:[]}});const props:any={candidates:[candidate],sources:[],saved:{jobId:'j',form},onState:vi.fn(),refreshSources:vi.fn().mockResolvedValue([]),apply:vi.fn(),add:vi.fn(),active:candidate,focusPreview:vi.fn()},x=harness(()=>WeatherPreparation(props));x.render();await flush();x.render();x.render();return {...x,props};}
 it('invalidates a fixed plan after location or delay changes and never starts the old area',async()=>{
  normal.acquisition.mockResolvedValue(job);const x=await setup(),fixed=acquisitionRequest(form,[candidate]);
  normal.weatherPlan.mockResolvedValue({plan_id:'p2',request:fixed,status:'ready',normalized_request:{run_utc:form.runUtc,bounds:{west:134,east:136,south:33,north:35},lead_hours:[1,2,3,4,5,6]},required_window:{start_utc:config.launch.time_utc,end_utc:'2026-09-30T05:17:13Z'},estimate:{grid_points:81,time_count:6,float64_bytes:10,estimated_working_memory_bytes:20,max_download_bytes:50000000},missing_leads:[],issues:[]});
  await click(x.render(),'取得計画を確認');await flush();expect(nodes(x.render()).find(n=>n.type==='button'&&text(n)==='この固定計画で気象を取得').props.disabled).toBe(false);
  x.props.candidates=[{...candidate,config:{...config,launch:{...config.launch,latitude_deg:43}}}];const moved=x.render();expect(text(moved)).toContain('取得範囲外の放球点');expect(text(moved)).toContain('放球地点・時間窓');expect(nodes(moved).find(n=>n.type==='button'&&text(n)==='この固定計画で気象を取得').props.disabled).toBe(true);await click(moved,'この固定計画で気象を取得');expect(normal.acquireWeather).not.toHaveBeenCalled();
  x.props.candidates=[candidate,{...candidate,id:'delay',parent_id:'A',delay_minutes:60,config:{...config,launch:{...config.launch,time_utc:'2026-09-30T02:17:13Z'}}}];expect(nodes(x.render()).find(n=>n.type==='button'&&text(n)==='この固定計画で気象を取得').props.disabled).toBe(true);x.unmount();
 });
 it('reopens an uncertain fixed acquisition and resubmits the same ID despite changed drafts',async()=>{
  putSubmission({id:'fixed-id',kind:'weather-acquisition',createdAt:'2026-09-30T00:00:00Z',payload:{plan_id:'old-fixed-plan',client_request_id:'fixed-id'}});
  normal.acquisition.mockResolvedValue(job);normal.acquireWeather.mockRejectedValueOnce(new WriteResponseUnknown()).mockResolvedValue({...job,acquisition_id:'existing',plan_id:'old-fixed-plan',state:'completed'});
  const x=await setup();await click(x.render(),'この同じ要求IDで受付を確認');await flush();expect(text(x.render())).toContain('応答未確認');x.unmount();
  const y=await setup();y.props.candidates=[{...candidate,config:{...config,launch:{...config.launch,latitude_deg:43}}}];await click(y.render(),'この同じ要求IDで受付を確認');await flush();
  expect(normal.acquireWeather.mock.calls).toEqual([['old-fixed-plan','fixed-id'],['old-fixed-plan','fixed-id']]);expect(text(y.render())).not.toContain('受付未確認の固定取得要求が');expect(y.props.apply).not.toHaveBeenCalled();y.unmount();
 });
 it('automatically resumes status GET after a temporary failure without restarting acquisition',async()=>{normal.acquisition.mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({...job,progress:{...job.progress,completed_files:2}}).mockResolvedValue({...job,state:'completed',cancellable:false,progress:{...job.progress,completed_files:3}});const x=await setup();await vi.advanceTimersByTimeAsync(900);expect(text(x.render())).toContain('取得の失敗を意味しません');await vi.advanceTimersByTimeAsync(1800);expect(text(x.render())).toContain('2/3');await vi.advanceTimersByTimeAsync(900);expect(text(x.render())).toContain('取得完了');expect(normal.acquireWeather).not.toHaveBeenCalled();expect(x.props.apply).not.toHaveBeenCalled();x.unmount();});
 it('keeps the selected older cycle even when a refreshed partial observation omits it',async()=>{normal.acquisition.mockResolvedValue(job);normal.refreshInventory.mockResolvedValue({inventory_id:'new-i',observed_at_utc:'2026-09-30T08:00:00Z',selection:'latest_observed',runs:[{run_utc:'2026-09-30T06:00:00Z',available_leads:[0,1],complete_lead_set:false}],observation_status:'partial',observation_errors:[{stage:'run',run_utc:form.runUtc,url:'https://nomads.invalid',code:'HTTP_ERROR',message:'503'}]});const x=await setup();click(x.render(),'配布一覧を更新');await flush();x.render();expect(x.props.onState.mock.calls.at(-1)[0].form.runUtc).toBe(form.runUtc);expect(x.props.onState.mock.calls.at(-1)[0].form.inventoryId).toBe('new-i');const panel=InventoryObservation({inventory:await normal.refreshInventory(),selectedRun:form.runUtc,select:vi.fn()});expect(text(panel)).toContain('一部の一覧を確認できません');expect(text(panel)).toContain('未配布とは断定しません');expect(text(panel)).toContain('この初期時刻を選ぶ');x.unmount();});
 it('late pre-cancel GET cannot overwrite the explicitly acknowledged cancelling state',async()=>{const d=deferred();normal.acquisition.mockReturnValueOnce(d.promise).mockResolvedValue({...job,state:'cancelled'});normal.cancelAcquisition.mockResolvedValue({...job,state:'cancelling',cancellable:false});const x=await setup();await vi.advanceTimersByTimeAsync(900);click(x.render(),'取得を取り消す');await flush();x.render();d.resolve(job);await flush();expect(text(x.render())).toContain('取消処理中');expect(text(x.render())).toContain('操作前の状態応答');await vi.advanceTimersByTimeAsync(1800);expect(text(x.render())).toContain('取消済');expect(normal.cancelAcquisition).toHaveBeenCalledOnce();x.unmount();});
 it('restores and observes a saved active acquisition when the independent inventory read fails',async()=>{
  normal.inventories.mockRejectedValueOnce(new Error('inventory offline'));normal.acquisition.mockResolvedValue(job);const x=await setup();
  expect(text(x.render())).toContain('保存した配布一覧を確認できません');expect(text(x.render())).toContain('取得中');expect(text(x.render())).not.toContain('まだ取得を開始していません');
  await vi.advanceTimersByTimeAsync(900);expect(normal.acquisition).toHaveBeenCalledOnce();click(x.render(),'保存した配布一覧を再読込');await flush();
  expect(text(x.render())).not.toContain('inventory offline');expect(normal.inventories).toHaveBeenCalledTimes(2);expect(normal.acquisitions).toHaveBeenCalledOnce();expect(normal.weatherStatus).toHaveBeenCalledOnce();expect(normal.acquireWeather).not.toHaveBeenCalled();x.unmount();
 });
 it('retries only an unread acquisition list and distinguishes unknown saved work from never started',async()=>{
  normal.acquisitions.mockRejectedValueOnce(new Error('acquisitions offline'));normal.acquisition.mockResolvedValue(job);const x=await setup();
  expect(text(x.render())).toContain('未開始とは判断しません');expect(text(x.render())).not.toContain('まだ取得を開始していません');expect(normal.acquisition).not.toHaveBeenCalled();
  click(x.render(),'取得履歴を再読込');await flush();x.render();await vi.advanceTimersByTimeAsync(900);expect(text(x.render())).toContain('取得中');expect(normal.acquisitions).toHaveBeenCalledTimes(2);expect(normal.inventories).toHaveBeenCalledOnce();expect(normal.weatherStatus).toHaveBeenCalledOnce();expect(normal.acquireWeather).not.toHaveBeenCalled();x.unmount();
 });
 it('keeps acquisition monitoring when the dependency GET is slow and then fails',async()=>{
  const d=deferred();normal.weatherStatus.mockReturnValueOnce(d.promise);normal.acquisition.mockResolvedValue(job);const x=await setup();
  expect(text(x.render())).toContain('取得中');await vi.advanceTimersByTimeAsync(900);expect(normal.acquisition).toHaveBeenCalledOnce();d.reject(new Error('dependency status offline'));await flush();
  expect(text(x.render())).toContain('取得環境を確認できません');click(x.render(),'取得環境を再読込');await flush();expect(text(x.render())).not.toContain('dependency status offline');expect(normal.weatherStatus).toHaveBeenCalledTimes(2);expect(normal.acquireWeather).not.toHaveBeenCalled();x.unmount();
 });
});
