import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {fixedResultLabel,readFailure,waitingDetail} from './fixedResultRead';
import {projectTabs} from './screens/forecast/projection';
const {h,ensemble,climate,normal}=vi.hoisted(()=>({h:{current:null as any},ensemble:{case:vi.fn(),jobs:vi.fn(),getPlan:vi.fn()},climate:{sources:vi.fn(),get:vi.fn(),create:vi.fn()},normal:{weather:vi.fn(),project:vi.fn(),runs:vi.fn(),run:vi.fn(),result:vi.fn()}}));
vi.mock('react',()=>({useRef:(v:any)=>h.current.ref(v),useState:(v:any)=>h.current.state(v),useEffect:(f:any,d:any[])=>h.current.effect(f,d),useReducer:(reducer:any,arg:any,init:any)=>h.current.reducer(reducer,arg,init)}));
vi.mock('./ensembleApi',()=>({ensembleApi:ensemble}));
vi.mock('./climateApi',()=>({climateApi:climate}));
vi.mock('./api',async()=>({...await vi.importActual<any>('./api'),api:normal}));
import {ApiError} from './api';
import {useEnsembleWorkspace} from './useEnsembleWorkspace';
import {useClimateWorkspace} from './useClimateWorkspace';
import {useWorkspace} from './useWorkspace';
function harness(fn:()=>any){let cursor=0;const slots:any[]=[],effects:any[]=[],cleanups:any[]=[];const owner={ref:(v:any)=>{const i=cursor++;return slots[i]??(slots[i]={current:v});},state:(v:any)=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return [slots[i],(n:any)=>{slots[i]=typeof n==='function'?n(slots[i]):n;}];},reducer:(f:any,v:any,init:any)=>{const [state,set]=owner.state(()=>init(v));return [state,(a:any)=>set((old:any)=>f(old,a))];},effect:(f:any,deps:any[])=>{const i=cursor++;if(!slots[i]||deps.some((v,j)=>!Object.is(v,slots[i][j]))){slots[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=f();});}}};const render=()=>{cursor=0;h.current=owner;const result=fn();effects.splice(0).forEach(f=>f());return result;};return {render,unmount:()=>cleanups.forEach(f=>f?.())};}
const deferred=()=>{let resolve!:(v:any)=>void,reject!:(e:any)=>void;const promise=new Promise<any>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
const config:any={launch:{time_utc:'2026-09-30T00:00:00Z',latitude_deg:34,longitude_deg:135},ascent:{mode:'constant_speed',speed_m_s:5},burst:{mode:'altitude',altitude_m:30000},descent:{mode:'rated_speed'}};
const candidate:any={id:'A',label:'A',revision:1,weather_source_id:'w',config};
const reference:any={kind:'ensemble_case',ensemble_id:'e',snapshot_id:'S',case_id:'A'};
const project:any={schema:'balloon.project/1',candidates:[candidate],compare_results:[reference],compare_run_ids:[],ui_state:{}};
const result=(snapshot='S')=>({snapshot_id:snapshot,case_id:'A',ensemble_id:'e',candidate:{id:'A',label:'A',revision:1},trials:[]});
let generation=1,loading=false,currentProject:any,selectionToken=0;
function collection(){const onProject=vi.fn((p:any)=>{currentProject=p;});const x=harness(()=>useEnsembleWorkspace(currentProject,[],generation,loading,onProject,{claim:()=>++selectionToken,current:()=>selectionToken}));return {...x,onProject};}
beforeEach(()=>{vi.useFakeTimers();vi.stubGlobal('window',{addEventListener:vi.fn(),removeEventListener:vi.fn()});generation=1;loading=false;selectionToken=0;currentProject=structuredClone(project);ensemble.jobs.mockReset().mockResolvedValue({ensembles:[]});ensemble.case.mockReset();ensemble.getPlan.mockReset();climate.sources.mockReset().mockResolvedValue({sources:[],errors:[]});climate.get.mockReset();climate.create.mockReset();});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
describe('saved result observation rather than fabricated absence',()=>{
 it('marks loading before the delayed saved case response, without changing input or selection',async()=>{const d=deferred();ensemble.case.mockReturnValue(d.promise);const x=collection();x.render();await flush();expect(x.render().caseReads['S:A'].state).toBe('loading');expect(fixedResultLabel(x.render().caseReads['S:A'])).toContain('読込中');currentProject={...currentProject,candidates:[{...candidate,label:'edited',revision:2}]};x.render();d.resolve(result());await flush();expect(x.render().caseReads['S:A'].state).toBe('ready');expect(currentProject.candidates[0].label).toBe('edited');expect(currentProject.compare_results).toEqual([reference]);expect(x.onProject).not.toHaveBeenCalled();x.unmount();});
 it('distinguishes confirmed 404 from transport failure; retry GET keeps the fixed reference and deduplicates',async()=>{ensemble.case.mockRejectedValueOnce(new ApiError('absent',404));const x=collection();x.render();await flush();expect(x.render().caseReads['S:A'].state).toBe('missing');const d=deferred();ensemble.case.mockReturnValue(d.promise);const a=x.render().reloadCase('S','A'),b=x.render().reloadCase('S','A');expect(ensemble.case).toHaveBeenCalledTimes(2);d.reject(new Error('offline'));await Promise.all([a,b]);expect(x.render().caseReads['S:A'].state).toBe('error');ensemble.case.mockResolvedValue(result());await x.render().reloadCase('S','A');expect(x.render().cases['S:A'].snapshot_id).toBe('S');expect(x.onProject).not.toHaveBeenCalled();x.unmount();});
 it('late restoration caches A but cannot replace the explicit newer selection B',async()=>{const a=deferred();ensemble.case.mockImplementation((s:string)=>s==='S'?a.promise:Promise.resolve(result('B')));const x=collection();x.render();await flush();await x.render().select('B','A');expect(currentProject.compare_results[0].snapshot_id).toBe('B');a.resolve(result());await flush();expect(currentProject.compare_results[0].snapshot_id).toBe('B');expect(x.onProject).toHaveBeenCalledTimes(1);x.unmount();});
 it('aborts prior project reads and ignores late errors after new restoration',async()=>{const old=deferred();ensemble.case.mockReturnValueOnce(old.promise).mockResolvedValue(result('T'));const x=collection();x.render();await flush();const signal=ensemble.case.mock.calls[0][2];generation++;currentProject={...currentProject,compare_results:[{...reference,snapshot_id:'T'}]};x.render();await flush();expect(signal.aborted).toBe(true);old.reject(new Error('old failure'));await flush();expect(x.render().caseReads['S:A']).toBeUndefined();expect(x.render().caseReads['T:A'].state).toBe('ready');expect(x.render().error).toBe('');x.unmount();});
 it('does not accept an artifact returned under the wrong snapshot identity',async()=>{ensemble.case.mockResolvedValue(result('wrong'));const x=collection();x.render();await flush();expect(x.render().cases['S:A']).toBeUndefined();expect(x.render().caseReads['S:A'].state).toBe('error');x.unmount();});
 it('n1 restoration failure is observable and GET retry does not replace edited input',async()=>{normal.weather.mockResolvedValue({sources:[]});normal.project.mockResolvedValue({revision:1,project:{...project,compare_results:[{kind:'single_run',run_id:'r'}],compare_run_ids:['r']}});normal.runs.mockResolvedValue({runs:[{run_id:'r',candidate_id:'A'}]});normal.run.mockResolvedValue({run_id:'r',candidate_id:'A'});normal.result.mockRejectedValueOnce(new ApiError('missing',404));const x=harness(useWorkspace);x.render();await flush();let w=x.render();expect(w.resultReads.r.state).toBe('missing');w.updateCandidate({...candidate,label:'edited'});x.render();normal.result.mockResolvedValue({run_id:'r',result:{config},weather_snapshot:{id:'w'}});await x.render().reloadResult('r');w=x.render();expect(w.project.candidates[0].label).toBe('edited');expect(w.resultReads.r.state).toBe('ready');expect(w.project.compare_run_ids).toEqual(['r']);x.unmount();});
 it('ordinary uncomputed candidate is distinct from a saved n1 waiting for bytes',()=>{const run:any={run_id:'r',candidate_id:'A',spec:{submitted_input:{config,weather_source_id:candidate.weather_source_id}}};const absent=projectTabs([candidate],[],{},[])[0],pending=projectTabs([candidate],[run],{},['r'],{}, {r:{state:'loading'}})[0];expect(fixedResultLabel(absent.resultRead)).toBe('未計算');expect(fixedResultLabel(pending.resultRead)).toContain('読込中');expect(pending.pending).toBe(false);expect(absent.pending).toBe(true);const unknown=projectTabs([candidate],[{run_id:'r',candidate_id:'A'} as any],{},['r'])[0];expect(unknown.resultRead?.state).toBe('loading');expect(unknown.pending).toBe(true);});
});
describe('saved detail waits for complete fixed artifacts',()=>{
 it('keeps waiting/error distinct from genuinely uncomputed group members',()=>{const state:any={detail:true,active:'G',groups:[{id:'G',members:['A','B']}],tabs:[{id:'A',result:{}},{id:'B',result:null,resultRead:{state:'error'}}]};expect(waitingDetail(state)).toBe(true);state.tabs[1].result={};expect(waitingDetail(state)).toBe(false);state.tabs[1]={id:'B',result:null};expect(waitingDetail(state)).toBe(false);});
});
describe('climate fixed restore GET is independent of edited draft and POST',()=>{
 const bounds={west:0,east:1,south:0,north:1},query={source_id:'s',level_id:1,grain:'half',bounds};const a:any={analysis_id:'A',query_hash:'qh',result_hash:'rh',query,summary:{query,source:{source_id:'s',dataset_sha256:'db',bounds}}};const saved:any={schema:'balloon.climate-view/1',draft_query:{...query,bounds:null},applied:{analysis_id:'A',query_hash:'qh',result_hash:'rh',source_id:'s',dataset_sha256:'db'}};
 it('retries missing saved figure without recalculating or overwriting the edited draft',async()=>{climate.get.mockRejectedValueOnce(new ApiError('not found',404));const onView=vi.fn(),x=harness(()=>useClimateWorkspace(saved,onView));x.render();await flush();expect(x.render().restoreRead.state).toBe('missing');x.render().editQuery({...a.query,level_id:7});const count=onView.mock.calls.length;climate.get.mockResolvedValue(a);await x.render().restoreSaved();expect(x.render().artifact.analysis_id).toBe('A');expect(x.render().restoreRead.state).toBe('ready');expect(x.render().view.draft_query.level_id).toBe(7);expect(onView).toHaveBeenCalledTimes(count);expect(climate.create).not.toHaveBeenCalled();x.unmount();});
 it('a late restored artifact never replaces a successfully applied newer artifact',async()=>{const old=deferred();climate.get.mockReturnValue(old.promise);const descriptor:any={source_id:'s',dataset_sha256:'db',levels:[{level_id:1}],bounds:structuredClone(bounds),native_grid:[{lat:0,lon:0}]};climate.sources.mockResolvedValue({sources:[descriptor],errors:[]});climate.create.mockResolvedValue({...a,analysis_id:'B'});const x=harness(()=>useClimateWorkspace(saved,vi.fn()));x.render();await flush();await x.render().calculate();expect(x.render().artifact.analysis_id).toBe('B');old.resolve(a);await flush();expect(x.render().artifact.analysis_id).toBe('B');expect(x.render().restoreRead.state).toBe('ready');x.unmount();});
});
